const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q131'] = "เด็ก 1 ขวบ มี recurrent cyanosis และ increased muscle tone 2-3 วินาทีหลังร้องไห้ เดินเองได้ พูดคำได้บ้าง ตรวจร่างกายปกติ no cyanosis no murmur no adventitious sound\n\nRecurrent cyanosis หลังร้อง 2-3 วินาที ในเด็ก 1 ขวบที่ developmentally normal + ตรวจร่างกายปกติ → cyanotic breath-holding spells\n\nBreath-holding spells (BHS) เป็นภาวะ benign ที่พบในเด็กอายุ 6 เดือน - 6 ปี (peak 1-2 ปี) เกิดจาก involuntary reflex apnea หลัง prolonged crying มี 2 ชนิด: cyanotic type (85% จากร้องไห้/หงุดหงิด → apnea → cyanosis → LOC) และ pallid type (15% จาก pain/surprise → vagal response → bradycardia → pallor → LOC)\n\nKey point คือ developmental milestones ปกติ + ตรวจร่างกายปกติ + เกิดหลังร้องไห้ทุกครั้ง + duration สั้นมาก (วินาที) + recover เอง\n\n✅ A. Reassure ถูกต้อง BHS เป็น benign self-limited condition ที่หายเองเมื่อเด็กโตขึ้น (อายุ 5-6 ปี) ไม่ต้องรักษาเฉพาะ เพียง reassure ผู้ปกครอง ตรวจ CBC ดู iron deficiency (อาจ trigger BHS) ถ้าพบให้ iron supplement\n\n❌ B. EEG ไม่ถูกต้อง ไม่จำเป็นเมื่อ history classic สำหรับ BHS ที่เกิดหลังร้องเสมอ ต่างจาก epileptic seizure ที่เกิดโดยไม่มี trigger\n\n❌ C. Chest x-ray ไม่ถูกต้อง Heart/lung exam ปกติ ไม่มี indication สำหรับ CXR\n\n❌ D. Serum calcium ไม่ถูกต้อง Hypocalcemic tetany มี prolonged muscle spasm ไม่เหมือน brief BHS ที่เกิดหลังร้อง\n\n❌ E. Echocardiography ไม่ถูกต้อง No murmur no cyanosis at rest ไม่มี cardiac cause ที่ต้อง echo";

reasons['NL2-2023-Q132'] = "ทารก 6 เดือน altered consciousness + fever BT 39 Brudzinski sign positive CSF: opening pressure 210 WBC (PMN 75% Lymph 25%) protein 120 mg/dL ถาม management\n\nFever + altered consciousness + meningeal sign (Brudzinski positive) + CSF findings: elevated opening pressure 210, PMN predominant 75%, elevated protein 120 → bacterial meningitis\n\nCSF ที่ PMN predominant (75% > 50%) + protein สูง (120 > 45) บ่งบอกว่าเป็น bacterial meningitis ไม่ใช่ viral (ซึ่งจะ lymphocyte predominant + protein ต่ำกว่า)\n\nEmpirical antibiotic สำหรับ bacterial meningitis ในทารก 6 เดือน: organisms ที่พบบ่อย ได้แก่ S. pneumoniae, N. meningitidis, H. influenzae type b ยาที่แนะนำคือ 3rd generation cephalosporin (cefotaxime หรือ ceftriaxone) สำหรับอายุ 1-3 เดือนต้องเพิ่ม ampicillin สำหรับ Listeria coverage แต่อายุ 6 เดือน ไม่ต้อง ampicillin\n\n✅ D. Cefotaxime ถูกต้อง เป็น empirical antibiotic ที่เหมาะสมสำหรับ bacterial meningitis ในทารก 6 เดือน ครอบคลุม S. pneumoniae, N. meningitidis, H. influenzae CNS penetration ดี\n\n❌ A. Acyclovir ไม่ถูกต้อง ใช้สำหรับ viral encephalitis (HSV) ซึ่ง CSF จะ lymphocyte predominant ไม่ใช่ PMN predominant\n\n❌ B. Anti-TB ไม่ถูกต้อง TB meningitis จะ lymphocyte predominant + very low glucose + very high protein + subacute onset ไม่ใช่ PMN predominant\n\n❌ C. Ampicillin ไม่ถูกต้อง Ampicillin alone ไม่ครอบคลุม S. pneumoniae ที่ penicillin-resistant ได้ดีพอ และไม่ใช่ first-line สำหรับอายุมากกว่า 3 เดือน\n\n❌ E. Amphotericin B ไม่ถูกต้อง ใช้สำหรับ fungal meningitis (Cryptococcus, Candida) ซึ่ง CSF จะ lymphocyte predominant + low glucose พบใน immunocompromised patients";

reasons['NL2-2023-Q133'] = "เด็กหญิง 4 ขวบ GTC seizure ที่ ER ขณะอยู่ใน ER เกิด recurrent GTC + LOC ถาม initial management\n\nRecurrent seizure ใน ER → ต้องให้ benzodiazepine ทันที เหมือน Q129 ตาม NRP/PALS guidelines first-line สำหรับ acute seizure management คือ benzodiazepine\n\nเมื่อเด็กชักอยู่ใน ER ทางเลือกที่เร็วที่สุด ได้แก่ IV diazepam (ถ้ามี IV), rectal diazepam (ถ้าไม่มี IV), buccal midazolam, IM midazolam ถ้ายังไม่มี IV access → rectal diazepam เป็น fastest route\n\n✅ A. Diazepam suppository ถูกต้อง เป็น initial management ที่เร็วที่สุดเมื่อ IV access ยังไม่ได้ ขนาด 0.5 mg/kg PR (max 10 mg)\n\n❌ B. ETT (Endotracheal Tube) ไม่ถูกต้อง Intubation ไม่ใช่ initial management สำหรับ seizure ต้องหยุด seizure ก่อน intubation สงวนไว้เมื่อ airway compromise\n\n❌ C. IV diazepam ไม่ถูกต้อง เป็น excellent choice แต่ต้องมี IV access ก่อน ถ้าถามถึง initial management ที่เร็วที่สุดขณะยังไม่มี IV rectal route เร็วกว่า\n\n❌ D. IV phenytoin ไม่ถูกต้อง เป็น 2nd line agent ให้หลัง benzodiazepine ล้มเหลว\n\n❌ E. Midazolam buccal ไม่ถูกต้อง Buccal midazolam เป็น alternative ที่ดีมาก (equivalent to rectal diazepam) แต่ในโจทย์นี้คำตอบ A (rectal diazepam) เป็น correct answer ตาม key";

reasons['NL2-2023-Q134'] = "เด็กชาย 13 ปี red urine 1 วัน ประวัติ acute pharyngitis 3 วันก่อน ตรวจพบ vital signs ปกติ no puffy eyelids no rash no arthritis UA: protein trace blood 3+ RBC 50-100/HPF WBC 0-1 no cast\n\nRed urine (gross hematuria) 1 วัน หลังจากมี pharyngitis เพียง 3 วันก่อน → timing เป็น key diagnostic clue\n\nIgA nephropathy (Berger's disease) มีลักษณะเฉพาะคือ synpharyngitic hematuria หมายถึง gross hematuria ที่เกิดภายใน 1-2 วันหลัง URI/pharyngitis (concurrent หรือ within 24-48 hours) เพราะ mucosal infection กระตุ้น IgA production ที่ already abnormally glycosylated ทำให้ IgA immune complexes deposit ที่ glomerular mesangium ทำให้เกิด mesangial proliferative GN\n\nต่างจาก post-streptococcal glomerulonephritis (PSGN) ที่ gross hematuria เกิดหลัง pharyngitis 1-3 สัปดาห์ (latent period) เพราะต้องใช้เวลาให้ immune complexes form ผู้ป่วยรายนี้ pharyngitis 3 วันก่อน → ไม่มี latent period → IgA nephropathy ไม่ใช่ PSGN\n\nนอกจากนี้ PSGN มักมี hypertension, edema (puffy eyelids), oliguria ผู้ป่วยรายนี้ BP ปกติ no puffy eyelids สนับสนุน IgA nephropathy มากกว่า\n\n✅ A. IgA nephropathy ถูกต้อง Synpharyngitic hematuria (gross hematuria within days of pharyngitis without latent period) + no hypertension + no edema เป็น classic presentation\n\n❌ B. IgA vasculitis ไม่ถูกต้อง IgA vasculitis (Henoch-Schonlein purpura) มี palpable purpura, arthritis/arthralgia, abdominal pain, renal involvement โจทย์ไม่มี rash หรือ arthritis\n\n❌ C. Henoch-Schonlein purpura ไม่ถูกต้อง เหมือน B ต้องมี purpuric rash + arthritis/arthralgia + abdominal pain\n\n❌ D. Membranoproliferative glomerulonephritis (MPGN) ไม่ถูกต้อง MPGN มักมา present ด้วย nephrotic + nephritic features ร่วมกัน chronic course ไม่ใช่ acute synpharyngitic hematuria แบบนี้\n\n❌ E. Acute poststreptococcal GN ไม่ถูกต้อง PSGN มี latent period 1-3 สัปดาห์หลัง pharyngitis (หรือ 3-6 สัปดาห์หลัง skin infection) ผู้ป่วยรายนี้ pharyngitis เพียง 3 วันก่อน สั้นเกินไปสำหรับ PSGN และไม่มี hypertension/edema ที่เป็น classic features ของ PSGN";

reasons['NL2-2023-Q135'] = "เด็ก 4 ขวบ edema + periorbital puffiness BP 150/100 Na 130 K 5 UA: protein 3+ RBC 50-100/HPF ถามว่านอกจาก furosemide ควรให้อะไร\n\nEdema + hypertension (150/100 ในเด็ก 4 ขวบ = severe hypertension) + proteinuria + hematuria → nephritic syndrome (likely acute GN) with severe hypertension\n\nSevere hypertension (BP 150/100) ในเด็กเป็น hypertensive urgency/emergency ที่ต้องรักษาด้วย antihypertensive drug เพื่อป้องกัน hypertensive encephalopathy, seizure, heart failure\n\n✅ A. Nicardipine ถูกต้อง เป็น IV calcium channel blocker ที่เป็น first-line สำหรับ hypertensive emergency ในเด็ก ลด BP ได้ predictable และ controllable\n\n❌ B. Albumin ไม่ถูกต้อง ใช้สำหรับ nephrotic syndrome with intravascular depletion ไม่ใช่ nephritic syndrome ที่ volume overloaded อยู่แล้ว\n\n❌ C. 10% Calcium gluconate ไม่ถูกต้อง ใช้สำหรับ cardiac protection ใน severe hyperkalemia (K>6.5 + EKG changes) K 5 ยังไม่ severe\n\n❌ D. 3% NaCl ไม่ถูกต้อง ใช้สำหรับ severe symptomatic hyponatremia (Na<120 + seizure) Na 130 = mild hyponatremia ไม่ต้อง hypertonic saline\n\n❌ E. Sodium polystyrene sulfonate (Kayexalate) ไม่ถูกต้อง ใช้สำหรับ chronic hyperkalemia K 5 ยังไม่ severe พอที่ต้อง urgent treatment";

reasons['NL2-2023-Q136'] = "เด็กหญิง 3 ขวบ สุขภาพดี abdominal distension 2 สัปดาห์ ตรวจพบ 8x8 cm firm RUQ mass BT 37 PR 100 BP 130/80 (hypertensive ในเด็ก 3 ปี) CBC Hct 33% WBC 6,500 Platelet 180,000 UA: normal\n\nLarge abdominal mass (8x8 cm) ที่ RUQ + hypertension ในเด็ก 3 ขวบ → Wilms tumor (nephroblastoma) เป็น diagnosis ที่น่าจะเป็นที่สุด\n\nWilms tumor เป็น most common primary renal malignancy ในเด็ก (peak age 3-4 ปี) มาด้วย painless abdominal mass + hypertension (จาก renin secretion โดย tumor) ± hematuria Mass มักใหญ่ smooth round firm อยู่ที่ flank/abdomen\n\nHypertension (BP 130/80) ในเด็ก 3 ปี (95th percentile ประมาณ 104/63) สูงมาก บ่งบอกว่า mass อาจมาจาก kidney ที่ produce renin\n\n✅ A. Wilms tumor ถูกต้อง Large abdominal mass + hypertension + age 3 ปี เป็น classic presentation ของ Wilms tumor\n\n❌ B. Neuroblastoma ไม่ถูกต้อง Neuroblastoma มาจาก neural crest cells (adrenal medulla/sympathetic chain) มักมี mass ที่ cross midline, irregular borders อาจมี periorbital ecchymosis (raccoon eyes), opsoclonus-myoclonus elevated urinary catecholamines (VMA, HVA) ไม่ค่อยทำให้ hypertension จาก renin\n\n❌ C. Hepatoblastoma ไม่ถูกต้อง พบในเด็กอายุน้อยกว่า 3 ปี (peak <18 เดือน) มี elevated AFP mass อยู่ที่ liver ไม่ค่อยทำให้ hypertension\n\n❌ D. Burkitt lymphoma ไม่ถูกต้อง Burkitt abdominal form มักมี rapidly growing mass ที่ ileocecal region อาจมี intussusception ไม่ทำให้ hypertension\n\n❌ E. Pheochromocytoma ไม่ถูกต้อง Pheo ทำให้ hypertension ได้จาก catecholamine excess แต่พบน้อยมากในเด็ก มี paroxysmal hypertension + headache + sweating + tachycardia ไม่ใช่ painless abdominal mass";

reasons['NL2-2023-Q137'] = "เด็ก 6 ขวบ skin infection เป็น honey crusts above mouth (impetigo) แล้วมี hematuria ตามมา ถาม proper investigation\n\nSkin infection (impetigo/honey crusts) → hematuria → post-streptococcal glomerulonephritis (PSGN) จาก skin infection\n\nPSGN หลัง skin infection (impetigo) จาก nephritogenic strains ของ Group A Streptococcus (GAS) มี latent period 3-6 สัปดาห์ (นานกว่า pharyngitis ที่ 1-3 สัปดาห์)\n\nSerological markers ของ streptococcal infection: ASO titer สูงขึ้นหลัง pharyngitis แต่ไม่ค่อยสูงหลัง skin infection เพราะ streptolysin O ถูก inactivate โดย skin lipids ส่วน Anti-DNase B จะสูงขึ้นหลังทั้ง pharyngitis และ skin infection จึงเป็น better marker สำหรับ post-impetigo PSGN\n\n✅ C. Anti-DNase B ถูกต้อง เป็น serological marker ที่ sensitive ที่สุดสำหรับ preceding streptococcal SKIN infection เพราะ Anti-DNase B สูงขึ้นได้ดีทั้งหลัง pharyngitis และ skin infection\n\n❌ A. ASO titer ไม่ถูกต้อง ASO เป็น marker ที่ดีสำหรับ streptococcal pharyngitis แต่ sensitivity ต่ำสำหรับ skin infection เพราะ streptolysin O ถูก inhibit โดย cholesterol ใน skin\n\n❌ B. Anti-dsDNA ไม่ถูกต้อง เป็น marker สำหรับ SLE nephritis ไม่ใช่ PSGN\n\n❌ D. Complement C3 level ไม่ถูกต้อง C3 จะ low ใน PSGN (จาก complement consumption) ช่วย support diagnosis แต่ไม่ specific สำหรับ streptococcal etiology C3 ต่ำได้ในหลาย glomerulonephritis\n\n❌ E. Renal biopsy ไม่ถูกต้อง ไม่จำเป็นใน typical PSGN ที่ clinical + serological diagnosis ชัดเจน Biopsy สงวนไว้เมื่อ atypical course หรือ prolonged renal impairment";

reasons['NL2-2023-Q138'] = "เด็กหญิง 12 ปี generalized thyroid enlargement 6 เดือน ทานอาหารทะเลบ่อย HR 80 BP 110/90 ตรวจพบ diffuse non-tender thyroid enlargement 30 g no nodules no exophthalmos no fever no neck pain Lab ?\n\nDiffuse goiter ในเด็กหญิง 12 ปี ที่ iodine sufficient (ทานอาหารทะเล) + HR 80 (ปกติ ไม่ใช่ tachycardia) + BP 110/90 (diastolic สูงเล็กน้อย ซึ่งพบได้ใน hypothyroidism) + no exophthalmos + no tenderness → Hashimoto thyroiditis\n\nHashimoto thyroiditis เป็น most common cause ของ acquired hypothyroidism ในเด็กและวัยรุ่นที่ iodine sufficient เป็น autoimmune thyroiditis จาก CD8+ T cell-mediated destruction ของ thyroid follicular cells ร่วมกับ anti-thyroid antibodies (anti-TPO, anti-thyroglobulin)\n\nมาด้วย diffuse painless goiter (firm, rubbery consistency) ที่ค่อยๆ โตขึ้น thyroid function อาจปกติในระยะแรก (euthyroid) แล้วค่อยๆ เป็น subclinical hypothyroid → overt hypothyroid Lab: elevated TSH, low free T4, elevated anti-TPO antibodies\n\n✅ E. Hashimoto thyroiditis ถูกต้อง Diffuse goiter + euthyroid/hypothyroid + iodine sufficient + no pain + adolescent female เป็น classic presentation\n\n❌ A. Simple goiter ไม่ถูกต้อง Simple (non-toxic) goiter เกิดจาก iodine deficiency หรือ goitrogens ผู้ป่วยรายนี้ iodine sufficient (ทานอาหารทะเล) จึงไม่น่าเป็น simple goiter\n\n❌ B. Graves' disease ไม่ถูกต้อง Graves' มี hyperthyroid symptoms: tachycardia, weight loss, tremor, sweating, exophthalmos ผู้ป่วยรายนี้ HR 80 (ปกติ) no exophthalmos ไม่เข้ากับ Graves'\n\n❌ C. Iodine deficiency ไม่ถูกต้อง ผู้ป่วยทานอาหารทะเลบ่อย iodine sufficient\n\n❌ D. Subacute thyroiditis ไม่ถูกต้อง Subacute (de Quervain) thyroiditis มาด้วย painful tender thyroid + fever + preceding viral illness ผู้ป่วยรายนี้ no tenderness no fever no pain ไม่เข้ากับ subacute thyroiditis";

reasons['NL2-2023-Q139'] = "ทารก 6 เดือน generalized edema ได้รับนม condensed milk ผสมน้ำตั้งแต่เกิด ตรวจพบ weight 6 kg length 60 cm round face apathy pitting edema 2+ thin hair dry peeling skin with hyperkeratosis\n\nKey findings: diluted condensed milk since birth (low protein, high carbohydrate diet) + generalized edema + round face + apathy + thin hair + skin changes (dry, peeling, hyperkeratosis) → protein-energy malnutrition: Kwashiorkor\n\nKwashiorkor เป็น severe acute malnutrition ที่เกิดจาก protein deficiency (adequate or excess calories but insufficient protein) นม condensed milk มี carbohydrate สูงแต่ protein ต่ำมาก เมื่อผสมน้ำ protein content จะยิ่งต่ำลง\n\nPathophysiology: protein deficiency ทำให้ albumin synthesis ลดลง → low serum albumin → low oncotic pressure → edema (bilateral, pitting, starts from feet แล้วขึ้นมา) ผมบาง/ร่วง (protein deficiency affects hair growth) ผิว dry, desquamation, hyperkeratosis (flaky paint dermatosis) round face (moon face จาก edema ที่หน้า) apathy (protein deficiency affects brain development)\n\n✅ A. Kwashiorkor disease ถูกต้อง Protein-deficient diet (diluted condensed milk) + edema + skin changes + thin hair + apathy เป็น classic presentation\n\n❌ B. Lymphedema ไม่ถูกต้อง Lymphedema เป็น non-pitting edema จาก lymphatic obstruction มักเป็นข้างเดียว ไม่มี nutritional deficiency signs\n\n❌ C. Chronic renal failure ไม่ถูกต้อง CRF มี edema จาก sodium/water retention + uremia แต่ไม่มี specific nutritional signs (thin hair, flaky skin) ที่เด่นแบบ Kwashiorkor\n\n❌ D. Nephrotic syndrome ไม่ถูกต้อง Nephrotic syndrome มี proteinuria ที่ทำให้ hypoalbuminemia + edema แต่ไม่มี dietary deficiency history หรือ skin/hair changes แบบ Kwashiorkor\n\n❌ E. Heart failure ไม่ถูกต้อง CHF มี edema + hepatomegaly + tachycardia + gallop rhythm ไม่มี nutritional signs";

reasons['NL2-2023-Q140'] = "เด็กชาย 2 ขวบ ใน daycare มี vesicles ที่มือ เท้า และ oral mucosa ไม่มีเด็กคนอื่นมีอาการเดียวกัน ถาม most effective method to prevent spreading\n\nVesicles ที่ hands, feet, oral mucosa → Hand-Foot-Mouth Disease (HFMD) สาเหตุหลักคือ Coxsackievirus A16 และ Enterovirus 71\n\nHFMD แพร่กระจายผ่าน fecal-oral route, respiratory droplets และ direct contact กับ fluid จาก vesicles ไวรัสสามารถอยู่บน surfaces ได้หลายชั่วโมง\n\nFrequent handwashing เป็น most effective infection control measure สำหรับ enteroviruses ที่ spread ผ่าน fecal-oral route + contact เพราะทำลาย virus ที่อยู่บนมือได้อย่างมีประสิทธิภาพ CDC recommends handwashing with soap and water เป็น primary prevention\n\n✅ B. Frequent Hand wash ถูกต้อง เป็น most effective และ practical measure สำหรับ prevent HFMD spread ใน daycare\n\n❌ A. Immunization ไม่ถูกต้อง ปัจจุบันมี EV71 vaccine ในบาง countries (จีน) แต่ไม่มี vaccine สำหรับ Coxsackievirus A16 และ vaccine ไม่ได้อยู่ใน EPI program\n\n❌ C. Hand sanitization alcohol ไม่ถูกต้อง Alcohol-based sanitizers มี effectiveness ต่ำต่อ non-enveloped viruses เช่น enterovirus (HFMD) เพราะ enterovirus ไม่มี lipid envelope ที่ alcohol จะ disrupt handwashing with soap + water effective กว่า\n\n❌ D. Close nursery 1 week ไม่ถูกต้อง การปิด nursery เป็น extreme measure ที่ไม่จำเป็นเมื่อมีแค่ 1 case hand hygiene + isolation ของ sick child เพียงพอ\n\n❌ E. Face mask ไม่ถูกต้อง Face mask ช่วยลด respiratory droplet spread ได้บ้าง แต่ main route ของ HFMD คือ fecal-oral + contact handwashing effective กว่ามาก";

reasons['NL2-2023-Q141'] = "เด็กชาย 4 ขวบ high-grade fever drooling dysphagia นั่ง extended neck BT 40 BP 90/60 PR 140 RR 34 stridor suprasternal retraction no wheezing no crepitation ถาม causative organism\n\nHigh fever + drooling + dysphagia + sitting with extended neck (tripod/sniffing position) + stridor + toxic appearance → acute epiglottitis\n\nAcute epiglottitis เป็น bacterial supraglottitis ที่ทำให้ epiglottis บวมอย่างรวดเร็ว อุด airway เป็น life-threatening emergency สาเหตุหลักคือ Haemophilus influenzae type b (Hib) แม้ว่า Hib vaccine จะลด incidence ลงมากแต่ยังเป็น classic cause ที่ต้องจำ\n\nClassic presentation: 4 D's — Dysphagia, Drooling, Distressed inspiratory efforts, Dysphonia ร่วมกับ sitting upright with chin extended (sniffing position) เพื่อเปิด airway ให้กว้างที่สุด Toxic appearance (high fever 40, tachycardia 140) บ่งบอก severe bacterial infection\n\n✅ E. Haemophilus influenzae ถูกต้อง เป็น classic causative organism ของ acute epiglottitis ในเด็ก\n\n❌ A. Moraxella catarrhalis ไม่ถูกต้อง ทำให้ otitis media, sinusitis ไม่ทำให้ epiglottitis\n\n❌ B. Streptococcus pneumoniae ไม่ถูกต้อง ทำให้ pneumonia, otitis media, meningitis ไม่ใช่ classic cause ของ epiglottitis\n\n❌ C. Staphylococcus aureus ไม่ถูกต้อง อาจ cause epiglottitis ได้บ้างแต่ rare ไม่ใช่ classic organism\n\n❌ D. Mycoplasma pneumoniae ไม่ถูกต้อง ทำให้ atypical pneumonia ไม่ทำให้ epiglottitis";

reasons['NL2-2023-Q142'] = "เด็กชาย 1 ขวบ dyspnea + drooling saliva นั่ง arm extended to back BT 40 RR 34 suprasternal retraction + wheezing ถาม causative agent\n\nClinical presentation เหมือนข้อ 141 — drooling + dyspnea + sitting position + high fever + stridor → acute epiglottitis จาก Haemophilus influenzae type B\n\n✅ E. Haemophilus influenzae type B ถูกต้อง Classic cause ของ acute epiglottitis\n\n❌ A. Moraxella catarrhalis ไม่ถูกต้อง ไม่ทำให้ epiglottitis ทำให้ otitis media/sinusitis\n\n❌ B. Staphylococcus aureus ไม่ถูกต้อง Rare cause ของ epiglottitis ไม่ใช่ classic\n\n❌ C. Streptococcus pyogenes ไม่ถูกต้อง ทำให้ pharyngitis/tonsillitis ไม่ใช่ epiglottitis\n\n❌ D. Mycoplasma pneumoniae ไม่ถูกต้อง ทำให้ atypical pneumonia ไม่ทำให้ epiglottitis";

reasons['NL2-2023-Q143'] = "เด็กชาย 7 ขวบ high-grade fever 1 วัน มีประวัติ wound ที่ left leg จากอุบัติเหตุจักรยาน 5 วันก่อน ตรวจพบ BT 39 PR 120 BP 100/60 looks ill dyspneic fine crepitation both lower lungs ถาม causative organism\n\nWound infection (skin break 5 วันก่อน) → bacteremia → bilateral pulmonary infiltrates (fine crepitation both lower lungs) = septic pulmonary emboli\n\nSkin wound เป็น portal of entry สำหรับ Staphylococcus aureus ซึ่งเป็น most common cause ของ skin/soft tissue infection S. aureus เข้าสู่กระแสเลือด (bacteremia) แล้ว seed ไปยังปอดเกิด septic pulmonary emboli/hematogenous pneumonia ที่มักเป็น bilateral multiple nodules/infiltrates\n\nS. aureus pneumonia มักเกิดจาก hematogenous spread (septic emboli) มากกว่า aspiration ลักษณะ bilateral, lower lobes เป็น pattern ที่พบบ่อย\n\n✅ B. Staphylococcus aureus ถูกต้อง Skin wound → staphylococcal bacteremia → septic pulmonary emboli เป็น classic pathogenesis\n\n❌ A. Moraxella catarrhalis ไม่ถูกต้อง ทำให้ otitis media/sinusitis ไม่ทำให้ wound-related bacteremia\n\n❌ C. Mycoplasma pneumoniae ไม่ถูกต้อง Atypical pneumonia ไม่สัมพันธ์กับ wound infection\n\n❌ D. Streptococcus pyogenes ไม่ถูกต้อง GAS อาจ cause wound infection (cellulitis) ได้ แต่ hematogenous pneumonia จาก GAS พบน้อยกว่า S. aureus\n\n❌ E. Haemophilus influenzae type B ไม่ถูกต้อง Hib ทำให้ meningitis, epiglottitis ไม่สัมพันธ์กับ wound-related sepsis";

reasons['NL2-2023-Q144'] = "เด็กชาย 10 ขวบ fever + nasal obstruction + otalgia 4 วัน BT 39 bilateral swollen inferior turbinate posterior nasal discharge injected pharynx tonsils 3+ erythematous bulging left TM ถาม treatment\n\nFever + nasal congestion + purulent discharge + tonsillopharyngitis + acute otitis media (erythematous bulging TM) → acute bacterial rhinosinusitis + AOM\n\nFirst-line antibiotic สำหรับทั้ง AOM และ acute sinusitis ในเด็กคือ amoxicillin (high-dose 80-90 mg/kg/day) ครอบคลุม S. pneumoniae (most common), H. influenzae, M. catarrhalis\n\n✅ A. Amoxicillin ถูกต้อง First-line antibiotic สำหรับ AOM + acute sinusitis\n\n❌ B. Azithromycin ไม่ถูกต้อง Second-line สำหรับ penicillin allergy ไม่ใช่ first-line\n\n❌ C. Dicloxacillin ไม่ถูกต้อง Anti-staphylococcal penicillin ใช้สำหรับ skin infection ไม่ครอบคลุม S. pneumoniae\n\n❌ D. Ceftriaxone ไม่ถูกต้อง IM ceftriaxone เป็น alternative สำหรับ treatment failure หรือ severe infection ไม่ใช่ initial therapy\n\n❌ E. Cefdinir ไม่ถูกต้อง 3rd gen oral cephalosporin เป็น alternative เมื่อ amoxicillin allergy (non-type 1) ไม่ใช่ first-line";

reasons['NL2-2023-Q145'] = "เด็กชาย 7 ขวบ (เหมือน Q143) wound ที่ขา → bacteremia → bilateral pneumonia ถาม most appropriate antibiotic\n\nS. aureus เป็น causative organism (เหมือน Q143) ดังนั้น antibiotic ต้องครอบคลุม S. aureus\n\nCloxacillin (dicloxacillin group) เป็น anti-staphylococcal penicillin ที่เป็น drug of choice สำหรับ methicillin-sensitive S. aureus (MSSA) infection ออกฤทธิ์โดย resist beta-lactamase ของ S. aureus จึง effective ต่อ penicillin-resistant staphylococci\n\n✅ B. Cloxacillin ถูกต้อง เป็น drug of choice สำหรับ MSSA infection ในเด็ก\n\n❌ A. Ceftazidime ไม่ถูกต้อง 3rd gen cephalosporin ที่ออกแบบมาครอบคลุม Pseudomonas ไม่ใช่ optimal สำหรับ S. aureus\n\n❌ C. Vancomycin ไม่ถูกต้อง สงวนไว้สำหรับ MRSA infection ถ้า community-acquired ในเด็กไทยส่วนใหญ่เป็น MSSA ใช้ cloxacillin ก่อน\n\n❌ D. Ciprofloxacin ไม่ถูกต้อง Fluoroquinolone ไม่แนะนำในเด็กเพราะ risk ของ cartilage damage (contraindicated <18 ปี ยกเว้น specific indications)\n\n❌ E. TMP/SMX ไม่ถูกต้อง อาจใช้ oral สำหรับ uncomplicated MRSA skin infection แต่ไม่เหมาะสำหรับ serious bacteremia + pneumonia ที่ต้อง IV antibiotic";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');
  mongoose.disconnect();
}).catch(err => console.error(err.message));
