const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q241'] = "เด็กชาย 3 ขวบ delayed speech aggressive behavior poor eye contact 1 ปี ตรวจพบ tip toe walking echolalia hyperactivity ถาม diagnosis\n\nDelayed speech + poor eye contact + echolalia + tip-toe walking ในเด็ก 3 ขวบ → Autism Spectrum Disorder (ASD)\n\nASD มี core features 2 domains ตาม DSM-5: 1) Persistent deficits in social communication/interaction (poor eye contact, reduced social reciprocity, difficulty understanding relationships) 2) Restricted/repetitive behaviors (echolalia = repetitive speech, tip-toe walking = stereotyped motor behaviors, rigid routines)\n\nEcholalia (พูดซ้ำคำที่ได้ยิน) เป็น characteristic language feature ของ ASD Tip-toe walking (เดินเขย่ง) เป็น stereotyped motor behavior ที่พบบ่อย Poor eye contact เป็น hallmark ของ social communication deficit\n\n✅ B. Autistic spectrum syndrome ถูกต้อง Poor eye contact + echolalia + tip-toe walking + delayed speech = classic ASD\n\n❌ A. Intellectual disability ไม่ถูกต้อง ID มี global developmental delay ไม่มี specific features เช่น poor eye contact + echolalia + stereotyped behaviors ที่เป็น autism-specific\n\n❌ C. ADHD ไม่ถูกต้อง ADHD มี inattention + hyperactivity + impulsivity แต่ไม่มี poor eye contact + echolalia + stereotyped behaviors\n\n❌ D. Neglected child ไม่ถูกต้อง Child neglect อาจทำให้ developmental delay ได้ แต่ echolalia + tip-toe walking เป็น autism-specific ไม่ใช่ neglect\n\n❌ E. Childhood disintegrative disorder ไม่ถูกต้อง CDD มี normal development จนถึงอายุ 2-4 ปี แล้ว regression ของ previously acquired skills โจทย์บอก delayed speech 1 ปี ไม่ใช่ regression";

reasons['NL2-2023-Q242'] = "นักเรียนชาย withdrawn avoids social interaction participates minimally average grades introverted emotionally flat ถาม diagnosis\n\nWithdrawn + avoids social interaction + emotionally flat + content being alone + minimal participation → Schizoid Personality Disorder\n\nSchizoid PD มี pattern ของ detachment จาก social relationships + restricted range of emotional expression ผู้ป่วยไม่สนใจ social relationships, ชอบอยู่คนเดียว, ดู cold/detached, emotionally flat ไม่มี paranoia (ต่างจาก schizotypal/paranoid PD) ไม่มี desire สำหรับ social interaction (ต่างจาก avoidant PD ที่ want แต่ afraid)\n\n✅ B. Schizoid personality disorder ถูกต้อง Social detachment + emotional restriction + content being alone\n\n❌ A. Avoidant PD ไม่ถูกต้อง Avoidant PD ต้องการ social interaction แต่ afraid of rejection/criticism ต่างจาก schizoid ที่ไม่สนใจ social interaction\n\n❌ C. Borderline PD ไม่ถูกต้อง BPD มี emotional instability, fear of abandonment, impulsivity, self-harm ตรงข้ามกับ emotionally flat\n\n❌ D. Dysthymia ไม่ถูกต้อง Persistent depressive disorder มี depressed mood, low self-esteem, hopelessness ผู้ป่วยรายนี้ไม่ได้ depressed แค่ socially detached\n\n❌ E. Social anxiety ไม่ถูกต้อง Social anxiety มี fear + avoidance ของ social situations จาก fear of scrutiny/embarrassment ต่างจาก schizoid ที่ไม่มี fear แค่ไม่สนใจ";

reasons['NL2-2023-Q243'] = "หญิง 25 ขวบ severe headache ขอหมอผู้ชาย flirt กับหมอ ชวนหมอไปกินข้าว ถาม diagnosis\n\nDramatic + attention-seeking + seductive/flirtatious behavior + inappropriate sexualization ของ doctor-patient relationship → Histrionic Personality Disorder\n\nHistrionic PD มี pervasive pattern ของ excessive emotionality + attention seeking behaviors ได้แก่ uncomfortable when not center of attention, inappropriate sexually seductive behavior, rapidly shifting/shallow emotions, dramatic/theatrical speech, suggestible, considers relationships more intimate than they are\n\n✅ B. Histrionic personality ถูกต้อง Attention-seeking + flirtatious + dramatic behavior\n\n❌ A. Adjustment disorder ไม่ถูกต้อง AD เป็น emotional/behavioral response ต่อ identifiable stressor ไม่ใช่ personality pattern\n\n❌ C. Borderline personality ไม่ถูกต้อง BPD มี emotional instability + fear of abandonment + self-harm + identity disturbance ต่างจาก histrionic ที่ attention-seeking + seductive\n\n❌ D. Dependent personality ไม่ถูกต้อง DPD มี excessive need to be taken care of + submissive behavior ไม่ใช่ seductive/attention-seeking\n\n❌ E. Narcissistic personality ไม่ถูกต้อง NPD มี grandiosity + need for admiration + lack of empathy ต่างจาก histrionic ที่ dramatic + seductive";

reasons['NL2-2023-Q244'] = "หญิง 50 ขวบ โสด tiredness irritability sleep disturbance uncontrolled HT/DLP poor drug compliance ลาออกจากงานดี 5 ปีก่อนเพื่อดูแลแม่ แม่ bedridden 2 ปี พี่ชายไม่ช่วย ถาม diagnosis\n\nหญิงวัยกลางคน ลาออกจากงาน ดูแลแม่ป่วย → tiredness + irritability + sleep disturbance + poor compliance → ปัญหาที่ซับซ้อนจาก life circumstances\n\nMidlife crisis เป็น concept ที่ครอบคลุม existential challenges ของวัยกลางคน ได้แก่ career loss, caregiver burden, unfulfilled goals, identity crisis ผู้ป่วยรายนี้สูญเสียอาชีพ (left successful job), รับภาระดูแลแม่, ไม่ได้รับความช่วยเหลือ, โสด → all contributing to midlife adjustment difficulties\n\n✅ A. Midlife crisis ถูกต้อง Complex life adjustment difficulties ในวัยกลางคน\n\n❌ B. Financial ไม่ถูกต้อง ไม่ได้ mention financial problems เป็น primary issue\n\n❌ C. Caregiver burnout ไม่ถูกต้อง Caregiver burnout เป็นส่วนหนึ่งของปัญหา แต่ overall picture กว้างกว่า (career loss + loneliness + health neglect) = midlife crisis\n\n❌ D. MDD ไม่ถูกต้อง ไม่ครบ DSM-5 criteria สำหรับ MDD (ต้องมี depressed mood หรือ anhedonia + 4 จาก SIGECAPS ≥ 2 สัปดาห์)\n\n❌ E. Adjustment disorder ไม่ถูกต้อง AD มี identifiable stressor + symptoms ภายใน 3 เดือน ปัญหานี้ดำเนินมา 5 ปี เกินกว่า AD";

reasons['NL2-2023-Q245'] = "หญิงไทย sleep problem muscle tension fatigue 1 ปี กังวลว่าจะเป็นแม่ที่ดีไหม + กังวลเรื่องงานสามี ถาม diagnosis\n\nExcessive worry เกี่ยวกับหลายเรื่อง (motherhood + husband's work) + muscle tension + fatigue + sleep disturbance นาน 1 ปี → Generalized Anxiety Disorder (GAD)\n\nGAD ตาม DSM-5: excessive anxiety + worry เกี่ยวกับ multiple events/activities ≥ 6 เดือน + difficulty controlling worry + ≥ 3 จาก 6 symptoms: restlessness, fatigue, concentration difficulty, irritability, muscle tension, sleep disturbance\n\nผู้ป่วยรายนี้มี: worry about multiple things + fatigue + muscle tension + sleep disturbance > 6 เดือน = GAD\n\n✅ A. GAD ถูกต้อง Excessive worry + multiple somatic symptoms > 6 เดือน\n\n❌ B. Somatic symptom disorder ไม่ถูกต้อง SSD มี excessive focus on physical symptoms ไม่ใช่ worry about life events\n\n❌ C. Panic disorder ไม่ถูกต้อง PD มี recurrent panic attacks (sudden intense fear + physical symptoms peak ใน minutes) ไม่ใช่ chronic worry\n\n❌ D. MDD ไม่ถูกต้อง MDD มี depressed mood/anhedonia เป็น core symptom ไม่ใช่ excessive worry\n\n❌ E. Adjustment disorder with anxiety ไม่ถูกต้อง AD มี identifiable stressor + onset ภายใน 3 เดือน ผู้ป่วยรายนี้ worry about normal life events (motherhood) นาน 1 ปี = GAD ไม่ใช่ AD";

reasons['NL2-2023-Q246'] = "หญิง 40 ขวบ femur fracture จาก car accident สูญเสียสามี + ลูก หมดสติหลังผ่าตัด หลังฟื้นตะโกน อยากตายตามครอบครัว ตอนกลางวัน พยายามถอด fixator กลางคืนนอนหลับไม่เป็น ถาม diagnosis\n\nPost-surgery + altered consciousness + agitation + disorientation (ตอนกลางวัน shouting ตอนกลางคืน sleep disturbance) + fluctuating course → delirium\n\nDelirium เป็น acute confusional state ที่มี fluctuating consciousness + inattention + disorganized thinking เกิดจาก underlying medical cause (post-surgery, pain, medications, metabolic derangement) มี waxing-waning course (ดีบ้างเสียบ้างตลอดวัน)\n\nKey differentiating features: acute onset หลัง surgery + fluctuating course + disorientation → delirium ไม่ใช่ psychiatric disorder\n\n✅ A. Delirium ถูกต้อง Post-surgical acute confusional state with fluctuating course\n\n❌ B. Brief psychosis ไม่ถูกต้อง Brief psychotic disorder มี delusions/hallucinations ที่ organized มากกว่า delirium ไม่มี fluctuating consciousness\n\n❌ C. MDD with psychotic feature ไม่ถูกต้อง MDD ใช้เวลา ≥ 2 สัปดาห์ ไม่ใช่ acute post-surgical onset\n\n❌ D. Adjustment disorder ไม่ถูกต้อง AD ไม่มี fluctuating consciousness/confusion\n\n❌ E. Schizophrenia ไม่ถูกต้อง Schizophrenia เป็น chronic illness ไม่ใช่ acute post-surgical presentation";

reasons['NL2-2023-Q247'] = "หญิง 20 ขวบ 3 เดือนหลังรอดจาก mass shooting หลีกเลี่ยงไปที่สาธารณะ ไม่มีความสุข nightmares รบกวนการนอน ถาม diagnosis\n\nTraumatic event (mass shooting) + > 1 เดือน + re-experiencing (nightmares) + avoidance (avoiding public) + negative mood (anhedonia) + sleep disturbance → PTSD\n\nPTSD ตาม DSM-5 ต้องมี 4 symptom clusters หลัง traumatic event > 1 เดือน: 1) Intrusion/re-experiencing (nightmares, flashbacks) 2) Avoidance (avoiding reminders) 3) Negative cognitions/mood (anhedonia, guilt) 4) Arousal/reactivity (sleep disturbance, hypervigilance)\n\n✅ D. PTSD ถูกต้อง All 4 clusters present > 1 เดือนหลัง trauma\n\n❌ A. Agoraphobia ไม่ถูกต้อง Agoraphobia มี fear ของ open/crowded spaces แต่ไม่มี nightmares + trauma history ผู้ป่วยรายนี้ avoidance เกิดจาก trauma ไม่ใช่ agoraphobia\n\n❌ B. Specific phobia ไม่ถูกต้อง Specific phobia มี fear ของ specific object/situation ไม่มี nightmares + negative mood\n\n❌ C. GAD ไม่ถูกต้อง GAD มี excessive worry about multiple things ไม่ใช่ trauma-related symptoms\n\n❌ E. Adjustment disorder with anxiety ไม่ถูกต้อง AD มี duration < 6 เดือน + symptoms ไม่ครบ PTSD criteria ผู้ป่วยรายนี้ครบ criteria สำหรับ PTSD";

reasons['NL2-2023-Q248'] = "เด็ก 14 ขวบ dyspnea ขณะเรียนหนังสือ ประวัติมาหลายครั้งด้วยอาการเดียวกัน RR 30 SpO2 90% ถาม cause\n\nRecurrent dyspnea ขณะ studying (stress trigger) + RR 30 + SpO2 90% ในเด็กวัยรุ่น → hyperventilation syndrome\n\nHyperventilation syndrome เกิดจาก anxiety/stress → rapid deep breathing → respiratory alkalosis (low CO2) → cerebral vasoconstriction + increased hemoglobin-oxygen affinity (left shift) → lightheadedness, tingling, carpopedal spasm SpO2 อาจ drop ได้บ้างจาก irregular breathing pattern\n\nRecurrent episodes ที่ triggered by stress (studying) + multiple visits → psychogenic cause\n\n✅ B. Hyperventilation syndrome ถูกต้อง Stress-triggered recurrent dyspnea ในวัยรุ่น\n\n❌ A. Panic attack ไม่ถูกต้อง Panic attack มี sudden intense fear + multiple physical symptoms ที่ peak ใน minutes hyperventilation เป็น component ของ panic attack แต่โจทย์เน้น hyperventilation pattern\n\n❌ C. Exercise-induced asthma ไม่ถูกต้อง EIA เกิดจาก exercise ไม่ใช่ studying\n\n❌ D. Vocal cord dysfunction ไม่ถูกต้อง VCD มี inspiratory stridor + throat tightness อาจเกิดจาก exercise/stress แต่ไม่ใช่ common diagnosis ในข้อสอบ\n\n❌ E. Cardiac arrhythmia ไม่ถูกต้อง Arrhythmia มี palpitations + irregular pulse ไม่ใช่ stress-triggered hyperventilation";

reasons['NL2-2023-Q249'] = "นักศึกษามีสอบพรุ่งนี้ เพื่อนร่วมห้องเตือนให้อ่านหนังสือ นักศึกษาโกรธ ถาม diagnosis\n\nIdentifiable stressor (exam tomorrow + roommate's reminder) + emotional response (anger) ที่ disproportionate → Adjustment Disorder\n\nAdjustment disorder คือ emotional/behavioral response ต่อ identifiable stressor ที่ onset ภายใน 3 เดือนหลัง stressor อาการ disproportionate ต่อ stressor + ไม่ครบ criteria ของ specific mental disorder อื่น\n\n✅ B. Adjustment disorder ถูกต้อง Disproportionate emotional response ต่อ identifiable stressor\n\n❌ A. MDD ไม่ถูกต้อง ไม่ครบ criteria (ต้องมี depressed mood/anhedonia + ≥ 4 symptoms ≥ 2 สัปดาห์)\n\n❌ C. Acute stress disorder ไม่ถูกต้อง ASD เกิดหลัง traumatic event (life-threatening) ไม่ใช่ stressor ธรรมดาอย่าง exam\n\n❌ D. Bipolar disorder ไม่ถูกต้อง ต้องมี manic/hypomanic episode ไม่ใช่แค่ anger\n\n❌ E. Intermittent explosive disorder ไม่ถูกต้อง IED มี recurrent behavioral outbursts ที่ disproportionate out of proportion โดยไม่มี specific stressor pattern";

reasons['NL2-2023-Q250'] = "นักแสดงหญิง 25 ขวบ กังวลเรื่องอ้วน easily angry mood labile กล่าวหาเพื่อนร่วมงานว่านินทา ถาม most likely cause\n\nWeight concern + irritability + mood lability + paranoid ideation (คนนินทา) → amphetamine use\n\nAmphetamine เป็น CNS stimulant ที่เพิ่ม dopamine + norepinephrine ผลต่อร่างกายและจิตใจ: 1) Anorexia/weight loss (ใช้ลดน้ำหนักผิดกฎหมาย โดยเฉพาะนักแสดง) 2) Irritability + mood lability (จาก dopamine excess) 3) Paranoid ideation (amphetamine psychosis จาก dopamine excess ใน mesolimbic pathway)\n\nTriad: weight concern + mood lability + paranoia = amphetamine\n\n✅ C. Amphetamine ถูกต้อง Weight concern + irritability + mood lability + paranoia\n\n❌ A. Kratom ไม่ถูกต้อง ไม่ทำให้ paranoia หรือ weight concern\n\n❌ B. Marijuana ไม่ถูกต้อง Cannabis ทำให้ increased appetite (munchies) ตรงข้ามกับ weight concern + relaxation ไม่ใช่ irritability\n\n❌ D. Thyroxine ไม่ถูกต้อง Iatrogenic hyperthyroidism ไม่ทำให้ paranoia\n\n❌ E. Alcohol ไม่ถูกต้อง Alcohol เป็น CNS depressant ทำให้น้ำหนักเพิ่ม ไม่ใช่ลด";

reasons['NL2-2023-Q251'] = "นักแสดงหญิง worried about weight nausea/vomiting irritable mood swings heard friends gossip ถาม drug most likely used\n\nเหมือน Q250 — weight concern + mood swings + paranoid ideation → amphetamine\n\n✅ C. Amphetamine ถูกต้อง Weight concern + irritability + paranoia = stimulant (amphetamine)\n\n❌ A. Ecstasy ไม่ถูกต้อง MDMA มี empathy + euphoria ไม่ใช่ irritability + paranoia\n\n❌ B. Cocaine ไม่ถูกต้อง Cocaine มี short duration of action (30-60 min) มี paranoia ได้ แต่ nausea/vomiting ไม่เด่น + cocaine ไม่ค่อยใช้เพื่อ weight loss แบบ amphetamine\n\n❌ D. Cannabis ไม่ถูกต้อง Cannabis ทำให้ increased appetite ไม่ช่วยลดน้ำหนัก\n\n❌ E. L-thyroxine ไม่ถูกต้อง Thyroid hormone excess ไม่ทำให้ paranoia";

reasons['NL2-2023-Q252'] = "หญิง 20 ขวบ SOB facial numbness bilateral carpopedal spasm 3 ครั้งใน 1 ชม. BT 36.5 PR 80 RR 28 BP 120/80 closes eyes good consciousness responsive ถาม management\n\nRecurrent hyperventilation + carpopedal spasm (จาก respiratory alkalosis → ionized calcium ลดลง) + normal vitals (except RR 28) + responsive → hyperventilation syndrome\n\nCarpopedal spasm เกิดจาก hyperventilation → CO2 ลดลง → respiratory alkalosis → pH สูงขึ้น → albumin bind calcium มากขึ้น → ionized calcium ลดลง → neuromuscular excitability → carpopedal spasm (Trousseau-like)\n\nRebreathing therapy (หายใจใน paper bag หรือ cupped hands) ช่วย retain CO2 → correct respiratory alkalosis → แก้ carpopedal spasm\n\n✅ B. Rebreathing therapy ถูกต้อง First-line treatment สำหรับ hyperventilation syndrome\n\n❌ A. Reassure ไม่ถูกต้อง Reassurance alone ไม่แก้ acute carpopedal spasm ต้อง rebreathing\n\n❌ C. Diazepam ไม่ถูกต้อง Benzodiazepine ใช้สำหรับ severe anxiety/panic แต่ rebreathing เป็น first-line\n\n❌ D. Haloperidol ไม่ถูกต้อง ใช้สำหรับ psychosis/agitation ไม่เหมาะสำหรับ hyperventilation\n\n❌ E. Sodium valproate ไม่ถูกต้อง Antiepileptic ไม่ใช่ treatment สำหรับ hyperventilation";

reasons['NL2-2023-Q253'] = "หญิง 30 ขวบ palpitation + chest discomfort ตอนกลางคืน นอนไม่หลับ 1 สัปดาห์ คิดว่าจะตาย no medical problems no drug abuse ถาม management\n\nRecurrent palpitation + chest discomfort + fear of dying + sleep disturbance + no medical cause → panic disorder\n\nPanic disorder ต้องมี recurrent unexpected panic attacks + ≥ 1 attack followed by ≥ 1 เดือนของ persistent concern about additional attacks หรือ maladaptive behavior change\n\nFirst-line treatment สำหรับ panic disorder: SSRI (sertraline, fluoxetine, paroxetine)\n\n✅ C. Sertraline ถูกต้อง First-line pharmacotherapy สำหรับ panic disorder\n\n❌ A. Psychotherapy ไม่ถูกต้อง CBT เป็น effective treatment แต่โจทย์ถาม pharmacological management ซึ่ง SSRI เป็น first-line\n\n❌ B. Midazolam ไม่ถูกต้อง Short-acting benzodiazepine ใช้สำหรับ acute panic attack ไม่ใช่ long-term management\n\n❌ D. Propranolol ไม่ถูกต้อง Beta-blocker ช่วยลด physical symptoms (palpitation, tremor) แต่ไม่ใช่ first-line สำหรับ panic disorder\n\n❌ E. Haloperidol ไม่ถูกต้อง Antipsychotic ไม่ใช่ treatment สำหรับ panic disorder";

reasons['NL2-2023-Q254'] = "หญิง 30 ขวบ คลอด 3 วันก่อน depressed mood กังวลว่าจะเลี้ยงลูกไม่ได้ ถาม management\n\nDepressed mood 3 วันหลังคลอด + worry about parenting → postpartum blues (baby blues)\n\nPostpartum blues เป็น transient emotional disturbance ที่พบได้ 50-80% ของ women หลังคลอด เริ่มวันที่ 2-3 หายเองภายใน 2 สัปดาห์ อาการ: mood swings, crying easily, anxiety, irritability, insomnia ต่างจาก postpartum depression ที่ persist > 2 สัปดาห์ + ครบ MDD criteria\n\nManagement สำหรับ baby blues: family support + reassurance ไม่ต้อง medication\n\n✅ A. Family consultation ถูกต้อง Family support + education เป็น appropriate management สำหรับ postpartum blues\n\n❌ B. Consult psychiatrist ไม่ถูกต้อง ยังไม่จำเป็นถ้าเป็น baby blues ที่หายเองใน 2 สัปดาห์ refer เมื่อ symptoms persist > 2 สัปดาห์\n\n❌ C. CBT ไม่ถูกต้อง CBT สำหรับ established PPD ไม่จำเป็นสำหรับ baby blues\n\n❌ D. Sertraline + stop breastfeeding ไม่ถูกต้อง Sertraline safe ใน breastfeeding แต่ไม่ต้อง medication สำหรับ baby blues\n\n❌ E. Lorazepam + stop breastfeeding ไม่ถูกต้อง Benzodiazepine + stop BF ไม่จำเป็นสำหรับ baby blues";

reasons['NL2-2023-Q255'] = "Panic attack ถาม most appropriate treatment\n\nPanic disorder (recurrent panic attacks) → first-line pharmacotherapy: SSRI\n\nSertraline เป็น SSRI ที่ FDA-approved สำหรับ panic disorder ขนาดเริ่ม 25 mg/day เพิ่มเป็น 50-200 mg/day เริ่มออกฤทธิ์ 2-4 สัปดาห์\n\n✅ A. Sertraline ถูกต้อง First-line long-term treatment สำหรับ panic disorder\n\n❌ B. Psychotherapy ไม่ถูกต้อง CBT effective แต่โจทย์ถาม pharmacological treatment\n\n❌ C. Alprazolam ไม่ถูกต้อง Benzodiazepine ใช้ acute symptom relief แต่ไม่ใช่ first-line long-term treatment เพราะ risk of dependence\n\n❌ D. Propranolol ไม่ถูกต้อง Beta-blocker ช่วย somatic symptoms แต่ไม่ first-line\n\n❌ E. Haloperidol ไม่ถูกต้อง Antipsychotic ไม่ใช่ treatment สำหรับ panic disorder";

reasons['NL2-2023-Q256'] = "หญิง 55 ขวบ เพิ่งเป็น manager insomnia irritable ทะเลาะกับเพื่อนร่วมงาน tired disappointed อยากหายไป ถาม management\n\nNew stressor (new manager position) + insomnia + irritability + fatigue + feeling of wanting to disappear → adjustment disorder with depressed mood หรือ MDD\n\n\"อยากหายไป\" เป็น passive suicidal ideation ที่ต้อง treat ด้วย antidepressant\n\nSertraline เป็น SSRI ที่เป็น first-line สำหรับ depression + adjustment disorder with depressed mood\n\n✅ C. Sertraline ถูกต้อง First-line antidepressant\n\n❌ A. Alprazolam ไม่ถูกต้อง Benzodiazepine ช่วย insomnia/anxiety แต่ไม่ treat depression + risk of dependence\n\n❌ B. Diazepam ไม่ถูกต้อง เหมือน alprazolam ไม่ treat depression\n\n❌ D. Quetiapine ไม่ถูกต้อง Atypical antipsychotic ใช้ adjunctive สำหรับ treatment-resistant depression ไม่ใช่ first-line\n\n❌ E. Haloperidol ไม่ถูกต้อง Typical antipsychotic ไม่ใช่ treatment สำหรับ depression";

reasons['NL2-2023-Q257'] = "ชาย insomnia 1 เดือน หลังทรัพย์สินถูกยึดตามคำสั่งศาล ดื่มแอลกอฮอล์ทุกวัน ไม่ยอมกิน ระบายอารมณ์กับภรรยาและลูก ถาม treatment\n\nIdentifiable stressor (asset seizure) + insomnia + alcohol use + anger displacement + appetite loss → depression/adjustment disorder with depressed mood ที่ต้อง antidepressant\n\n✅ A. Sertraline ถูกต้อง First-line antidepressant\n\n❌ B. Lorazepam ไม่ถูกต้อง Benzodiazepine ไม่เหมาะในผู้ป่วยที่ดื่มแอลกอฮอล์ทุกวัน (risk of cross-dependence + respiratory depression)\n\n❌ C. Haloperidol ไม่ถูกต้อง ไม่ใช่ treatment สำหรับ depression\n\n❌ D. Risperidone ไม่ถูกต้อง Atypical antipsychotic ไม่ใช่ first-line สำหรับ depression\n\n❌ E. Sodium valproate ไม่ถูกต้อง Mood stabilizer ใช้สำหรับ bipolar disorder ไม่ใช่ unipolar depression";

reasons['NL2-2023-Q258'] = "ชาย 25 ขวบ สุขภาพดี dyspnea + palpitation ขณะขับรถ รู้สึกเหมือนจะตาย ต้องจอดรถ 30 นาที ไม่มี underlying disease ไม่ดื่มเหล้า/ใช้ยา BT 37 BP 130/70 PR 95 ถาม treatment\n\nRecurrent episodes ของ sudden dyspnea + palpitation + fear of dying + duration 30 min + no medical cause → panic disorder\n\nFirst-line pharmacotherapy: SSRI (fluoxetine, sertraline, paroxetine)\n\n✅ A. Fluoxetine ถูกต้อง SSRI เป็น first-line สำหรับ panic disorder\n\n❌ B. Diazepam ไม่ถูกต้อง ช่วย acute symptoms แต่ไม่ใช่ long-term treatment\n\n❌ C. Alprazolam ไม่ถูกต้อง เหมือน diazepam\n\n❌ D. Risperidone ไม่ถูกต้อง Antipsychotic ไม่ใช่ treatment สำหรับ panic disorder\n\n❌ E. Valproate ไม่ถูกต้อง Mood stabilizer ไม่ใช่ treatment สำหรับ panic disorder";

reasons['NL2-2023-Q259'] = "ชาย 40 ขวบ confusion 1 วันหลัง appendectomy ดื่มเหล้าทุกวัน 10 ปี มือสั่น ถาม medication\n\nPost-surgical confusion + chronic alcohol use + tremor → alcohol withdrawal delirium (delirium tremens)\n\nAlcohol withdrawal เกิดเมื่อหยุดดื่มกะทันหัน (เช่น admission สำหรับ surgery) เริ่ม 6-24 ชม.หลังหยุดดื่ม: tremor, anxiety, insomnia, tachycardia → 24-72 ชม.: seizures, hallucinations → 48-96 ชม.: delirium tremens (confusion, agitation, autonomic instability, fever)\n\nDiazepam เป็น first-line treatment สำหรับ alcohol withdrawal ตาม CIWA protocol (benzodiazepine-based) ออกฤทธิ์ผ่าน GABA-A receptor (cross-tolerance กับ alcohol ที่ออกฤทธิ์ผ่าน GABA)\n\n✅ A. Diazepam ถูกต้อง First-line สำหรับ alcohol withdrawal\n\n❌ B. Haloperidol ไม่ถูกต้อง ลด seizure threshold อาจ worsen alcohol withdrawal seizure\n\n❌ C. Amitriptyline ไม่ถูกต้อง TCA ไม่ใช่ treatment สำหรับ alcohol withdrawal\n\n❌ D. Phenytoin ไม่ถูกต้อง Phenytoin ไม่ effective สำหรับ alcohol withdrawal seizure (ต่างจาก epileptic seizure)\n\n❌ E. Naltrexone ไม่ถูกต้อง ใช้สำหรับ long-term alcohol dependence treatment ไม่ใช่ acute withdrawal";

reasons['NL2-2023-Q260'] = "ผู้ป่วย palpitations dizziness sense of impending death (panic attack) ถาม treatment\n\nPanic disorder → SSRI เป็น first-line pharmacotherapy\n\n✅ A. Sertraline ถูกต้อง First-line SSRI สำหรับ panic disorder\n\n❌ B. Diazepam ไม่ถูกต้อง Acute relief ไม่ใช่ long-term treatment\n\n❌ C. Methylphenidate ไม่ถูกต้อง Stimulant สำหรับ ADHD อาจทำให้ panic worse\n\n❌ D. Midazolam ไม่ถูกต้อง Short-acting benzodiazepine ไม่ใช่ long-term treatment\n\n❌ E. Buspirone ไม่ถูกต้อง ใช้สำหรับ GAD ไม่ proven effective สำหรับ panic disorder";

reasons['NL2-2023-Q261'] = "ผู้ป่วย OCD ถาม treatment\n\nOCD → first-line pharmacotherapy: SSRI (sertraline, fluoxetine, fluvoxamine) ที่ higher doses กว่า depression (sertraline 150-200 mg/day)\n\n✅ A. Sertraline ถูกต้อง First-line SSRI สำหรับ OCD ตาม APA guidelines\n\n❌ B. Haloperidol ไม่ถูกต้อง Antipsychotic ไม่ใช่ first-line อาจใช้ augment SSRI ใน refractory OCD\n\n❌ C. Diazepam ไม่ถูกต้อง Benzodiazepine ไม่ treat OCD\n\n❌ D. Sodium valproate ไม่ถูกต้อง Mood stabilizer ไม่ treat OCD\n\n❌ E. Clomipramine ไม่ถูกต้อง Clomipramine (TCA) เป็น effective สำหรับ OCD แต่ SSRI เป็น first-line เพราะ better side effect profile clomipramine เป็น second-line";

reasons['NL2-2023-Q262'] = "Interview เรื่อง sexual activity ในนักเรียน ม.ปลาย 2 วิธี: face-to-face = 10% vs questionnaire = 25% ถาม bias\n\nFace-to-face interview ได้ lower rate กว่า anonymous questionnaire สำหรับ sensitive topic (sexual activity) → social desirability bias\n\nSocial desirability bias เกิดเมื่อ respondents ตอบในสิ่งที่ socially acceptable มากกว่าความจริง เมื่อถูกถามต่อหน้า (face-to-face) นักเรียนไม่กล้าบอกว่ามี sexual activity เพราะกลัว judgment → underreport ขณะที่ anonymous questionnaire ไม่มี social pressure → report ตามจริง → higher rate\n\n✅ C. Social desirability ถูกต้อง Face-to-face underreport sensitive behavior\n\n❌ A. Selection ไม่ถูกต้อง Selection bias เกิดจากการเลือก participants ไม่เกี่ยวกับ method ของ interview\n\n❌ B. Exclusion ไม่ถูกต้อง ไม่มีการ exclude participants\n\n❌ D. Attrition ไม่ถูกต้อง Attrition bias เกิดจาก loss to follow-up ไม่เกี่ยว\n\n❌ E. Recall bias ไม่ถูกต้อง Recall bias เกิดจากการจำผิด ไม่ใช่การตอบไม่ตรง";

reasons['NL2-2023-Q263'] = "Meta-analysis ของ corticosteroid vs placebo ใน pneumonia ถาม most beneficial outcome (ดูจากตาราง ARD, RR, NNT)\n\nMeta-analysis outcomes ดู beneficial outcome จาก NNT (Number Needed to Treat) ยิ่ง NNT น้อย ยิ่ง beneficial (ต้อง treat คนน้อยเพื่อ prevent 1 event) ร่วมกับ 95% CI ที่ statistically significant\n\nจากตาราง prevention of shock ใน adults มี NNT ที่น้อยที่สุดและ statistically significant → most beneficial outcome\n\n✅ D. Prevention of shock in adults ถูกต้อง มี NNT ดีที่สุดที่ statistically significant\n\n❌ A. 30-day mortality severe ไม่ถูกต้อง NNT อาจไม่ significant หรือ larger\n\n❌ B. 30-day mortality non-severe ไม่ถูกต้อง ไม่ significant\n\n❌ C. Prevention of mechanical ventilation ไม่ถูกต้อง NNT อาจ larger กว่า prevention of shock\n\n❌ E. Hyperglycemia ไม่ถูกต้อง Hyperglycemia เป็น harm ไม่ใช่ benefit (NNH ไม่ใช่ NNT)";

reasons['NL2-2023-Q264'] = "Health surveillance: prevalence HT ใน adults 30% โรงพยาบาลทำ low-salt diet promotion campaign ถาม type of prevention\n\nLow-salt diet promotion สำหรับ population ที่มี HT prevalence 30% → primary prevention\n\nPrimary prevention = ป้องกันการเกิดโรคก่อนที่จะเกิด โดย modify risk factors (low-salt diet ลด risk ของ HT ในคนที่ยังไม่เป็น)\n\nแม้ว่า 30% ของ population เป็น HT อยู่แล้ว แต่ campaign ที่ promote low-salt diet ให้ population ทั้งหมด (รวมคนที่ยังไม่เป็น HT) จัดเป็น primary prevention เพราะ target คือ prevent new cases\n\n✅ B. Primary Prevention ถูกต้อง Diet modification เพื่อ prevent disease occurrence\n\n❌ A. Primordial Prevention ไม่ถูกต้อง Primordial = prevent risk factors from developing (เช่น สร้าง environment ที่ healthy ตั้งแต่เด็ก) ไม่ใช่ dietary campaign ใน adults\n\n❌ C. Secondary Prevention ไม่ถูกต้อง Secondary = early detection + treatment (screening + treatment ของ HT)\n\n❌ D. Tertiary Prevention ไม่ถูกต้อง Tertiary = ลด complications ของ established disease\n\n❌ E. Quaternary Prevention ไม่ถูกต้อง Quaternary = ป้องกัน overdiagnosis/overtreatment";

reasons['NL2-2023-Q265'] = "หญิงทำงานในโรงงานตัดเย็บเสื้อผ้า 25 ปี dyspnea อาการเด่นวันจันทร์ ดีขึ้นวันหยุด CXR: perihilar interstitial infiltration ถาม diagnosis\n\nGarment factory worker 25 ปี + dyspnea ที่ worse on Monday + better on weekends + perihilar infiltration → byssinosis\n\nByssinosis (Monday fever/brown lung disease) เกิดจากสูดฝุ่น cotton/textile fibers ที่มี endotoxin ทำให้ bronchial inflammation + bronchoconstriction อาการเด่นในวันจันทร์ (หลังหยุดพัก 2 วัน กลับมาสัมผัส cotton dust ใหม่) เรียกว่า \"Monday morning symptoms\" ดีขึ้นเมื่อ adapt ระหว่างสัปดาห์ (tachyphylaxis)\n\n✅ A. Byssinosis ถูกต้อง Textile worker + Monday symptoms + occupational exposure 25 ปี\n\n❌ B. Silicosis ไม่ถูกต้อง จาก silica dust (mining, sandblasting) ไม่ใช่ textile factory CXR: upper lobe fibrosis + eggshell calcification\n\n❌ C. Asbestosis ไม่ถูกต้อง จาก asbestos exposure (construction, shipyard) CXR: lower lobe fibrosis + pleural plaques\n\n❌ D. Melioidosis ไม่ถูกต้อง เป็น infection จาก Burkholderia pseudomallei ไม่ใช่ occupational lung disease\n\n❌ E. Hypersensitivity pneumonitis ไม่ถูกต้อง HP เกิดจาก organic antigens (bird droppings, moldy hay) มี Monday symptoms ได้แต่ textile factory ชี้ไปที่ byssinosis มากกว่า";

reasons['NL2-2023-Q266'] = "Survey พบ goiter prevalence 15% ถาม population group ที่ควร target screening\n\nGoiter prevalence 15% ใน population → endemic goiter จาก iodine deficiency WHO กำหนดว่า goiter prevalence > 5% ใน school-age children ถือเป็น public health problem\n\nSchool-age children (6-12 ปี) เป็น target group สำหรับ iodine deficiency screening ตาม WHO guidelines เพราะ 1) easy to access (โรงเรียน) 2) sensitive indicator ของ iodine status 3) goiter rate ใน school-age children reflect recent iodine status ของ community\n\n✅ B. School age ถูกต้อง WHO-recommended target group สำหรับ iodine deficiency screening\n\n❌ A. Pre-school ไม่ถูกต้อง ยากที่จะ access + goiter ยังไม่เด่นชัด\n\n❌ C. Teenage ไม่ถูกต้อง ไม่ใช่ WHO-recommended primary target\n\n❌ D. Pregnant women ไม่ถูกต้อง Pregnant women ต้อง iodine supplementation แต่ไม่ใช่ target สำหรับ goiter screening ใน population\n\n❌ E. Elderly ไม่ถูกต้อง ไม่ใช่ target group สำหรับ iodine deficiency screening";

reasons['NL2-2023-Q267'] = "หญิง 35 ขวบ sexually inactive no family history ASCVD healthy diet exercise no smoking ถาม strongly recommended health periodic examination\n\nHealthy 35-year-old woman sexually inactive → ดูว่า screening อะไรที่ recommended ตาม age + risk factors\n\nBlood pressure measurement เป็น screening ที่ strongly recommended สำหรับ adults ทุกคนตั้งแต่อายุ 18 ปีขึ้นไป (USPSTF Grade A recommendation) ไม่ว่าจะมี risk factors หรือไม่\n\n✅ A. Blood pressure ถูกต้อง USPSTF Grade A recommendation สำหรับ adults ≥ 18 ปี\n\n❌ B. Mammogram ไม่ถูกต้อง เริ่มอายุ 40-50 ปี (ขึ้นกับ guidelines) ยังไม่ถึงอายุ\n\n❌ C. Pap smear ไม่ถูกต้อง Pap smear แนะนำสำหรับ sexually active women ผู้ป่วยรายนี้ sexually inactive\n\n❌ D. Fasting blood sugar + lipid profile ไม่ถูกต้อง DM screening เริ่มอายุ 35-45 ปี (ขึ้นกับ risk factors) Lipid screening เริ่มอายุ 40+ ในหญิง ผู้ป่วยรายนี้ no risk factors อายุ 35 ยังไม่ strongly recommended\n\n❌ E. Stool occult blood ไม่ถูกต้อง CRC screening เริ่มอายุ 45-50 ปี ยังไม่ถึง";

reasons['NL2-2023-Q268'] = "ชาย 20 ขวบ ถูกเพื่อนตีศีรษะด้วย baseball bat พบ 5 cm laceration ที่ left parietal skull 2 ปีต่อมาเป็นพยานศาล ทนายถามเกี่ยวกับ type of object ถาม most appropriate answer\n\nForensic testimony เกี่ยวกับ type ของ object ที่ใช้ทำร้าย — แพทย์ไม่ควรระบุว่า specific object คืออะไร (baseball bat) แต่ควรระบุ type of force/mechanism ที่สอดคล้องกับ wound pattern\n\n5 cm laceration = wound จาก blunt force trauma (ขอบไม่เรียบ, bridging vessels, surrounding bruising) ต่างจาก sharp force (incised wound ที่ขอบเรียบ clean)\n\nแพทย์ควรตอบว่า \"wound consistent with blunt object impact\" ไม่ควรระบุว่าเป็น baseball bat เพราะ blunt objects หลายชนิดทำให้ wound pattern เหมือนกันได้\n\n✅ C. The patient had head impaction by a blunt object ถูกต้อง ระบุ type of force (blunt) โดยไม่ระบุ specific object\n\n❌ A. The patient was hit by a baseball bat ไม่ถูกต้อง แพทย์ไม่ควรระบุ specific object เพราะ wound pattern ไม่สามารถ differentiate ระหว่าง blunt objects ได้\n\n❌ B. Could be blunt or sharp ไม่ถูกต้อง Laceration = blunt force ชัดเจน ไม่ใช่ sharp\n\n❌ D. Sharp force injury ไม่ถูกต้อง Laceration = blunt ไม่ใช่ sharp (incised wound)\n\n❌ E. Cannot determine ไม่ถูกต้อง สามารถ determine type of force (blunt) ได้จาก wound characteristics";

reasons['NL2-2023-Q269'] = "Postmortem exam ที่อาคารไฟไหม้ พบศพชายไม่มี burn wounds autopsy: dark red livor mortis swelling pink oral/respiratory mucosa/larynx no soot in airway serum CO undetected ถาม what to tell\n\nBody ในอาคารไฟไหม้ แต่ 1) ไม่มี burn wounds 2) ไม่มี soot ใน airway (ไม่ได้หายใจเอาควันเข้าไป) 3) CO level undetected (ไม่ได้สูดดม CO) → ศพถูกนำมาวางก่อนเกิดไฟไหม้ (dead before fire)\n\nถ้าตายจากไฟไหม้ จะพบ 1) Burns 2) Soot ใน airway (สูดควัน) 3) Elevated CO level (สูดดม CO) การที่ไม่มีสิ่งเหล่านี้แสดงว่าเสียชีวิตก่อนไฟไหม้\n\nDark red livor mortis + pink mucosa อาจเกิดจาก CO exposure ใน low concentration หลังตาย (passive exposure) หรือจาก postmortem changes อื่น\n\n✅ E. The dead body was brought before the building burned ถูกต้อง No vital reaction to fire (no burns, no soot, no CO) = dead before fire\n\n❌ A. Smoke inhalation ไม่ถูกต้อง No soot in airway + no CO → ไม่ได้สูดควัน\n\n❌ B. Laryngeal spasm ไม่ถูกต้อง ไม่มี evidence ของ acute airway obstruction\n\n❌ C. Natural death ไม่ถูกต้อง ไม่สามารถ conclude natural death ได้เมื่อพบศพใน crime scene (fire)\n\n❌ D. Homicide ไม่ถูกต้อง ยังไม่สามารถ determine manner of death ได้จาก autopsy findings เพียงอย่างเดียว ต้อง further investigation";

reasons['NL2-2023-Q270'] = "ชายนอนคว่ำ มีปืนในมือ gunshot wound ที่ศีรษะ ถาม finding ที่ indicate contact-range gunshot wound\n\nContact gunshot wound เกิดเมื่อ muzzle ของปืนแนบชิดผิวหนัง characteristics ได้แก่ 1) Star-shaped/stellate wound (ผิวหนังฉีกเป็นรูปดาวจาก gas expansion ใต้ผิวหนัง) 2) Muzzle imprint (รอยพิมพ์ของปากกระบอกปืน) 3) Soot/powder deposition ภายใน wound (ไม่ใช่รอบ wound) 4) Cherry-red discoloration จาก CO ใน propellant gas\n\nStar-shaped wound เป็น most characteristic finding ของ contact-range gunshot เกิดจาก gas + flame ที่เข้าไปใต้ผิวหนัง expand ทำให้ skin burst outward เป็นรูปดาว\n\n✅ B. Star-shaped wound ถูกต้อง Pathognomonic finding ของ contact gunshot wound\n\n❌ A. Marginal abrasion ไม่ถูกต้อง Abrasion collar/marginal abrasion พบได้ในทุก range ของ gunshot wound ไม่ specific สำหรับ contact\n\n❌ C. Gunpowder in the wound ไม่ถูกต้อง Gunpowder ใน wound พบได้ใน close range ไม่เฉพาะ contact\n\n❌ D. Contusion ไม่ถูกต้อง ไม่ specific สำหรับ contact gunshot\n\n❌ E. Gun found in hand ไม่ถูกต้อง ไม่ใช่ wound characteristic ไม่ indicate contact range (gun อาจถูกวางหลัง shooting)";

reasons['NL2-2023-Q271'] = "หญิง 20 ขวบ ไปไนท์คลับ หมดสติ ตื่นมาอยู่ในห้องโรงแรม PE: elliptical marks + petechiae ที่คอ new hymen tear ที่ 5 o'clock ถาม most appropriate action\n\nLoss of consciousness ที่ nightclub + woke up ใน hotel room + neck marks + hymen tear → suspected drug-facilitated sexual assault (DFSA)\n\nElliptical marks ที่คอ = finger marks จาก strangulation/choking Hymen tear = evidence ของ vaginal penetration Pattern ชี้ว่าถูก drugged แล้ว assault\n\nMost appropriate action: test for sedative drug level เพื่อ 1) Confirm DFSA 2) Identify specific drug used (GHB, benzodiazepines, ketamine) 3) Evidence สำหรับ legal proceedings เนื่องจาก drugs เหล่านี้มี short half-life ต้อง test เร็ว\n\n✅ D. Test for sedative drug level ถูกต้อง Most important forensic investigation สำหรับ suspected DFSA\n\n❌ A. Notify police ไม่ถูกต้อง ต้องได้ consent จากผู้ป่วยก่อน notify police (ในหลายประเทศ) แพทย์ไม่ควร notify police โดยไม่ได้รับอนุญาต\n\n❌ B. Document penetration ไม่ถูกต้อง Document ว่ามี hymen tear ได้ แต่ไม่ควรระบุว่า \"there was penetration\" เพราะ hymen tear อาจเกิดจากสาเหตุอื่นได้ ควรบรรยาย findings เท่านั้น\n\n❌ C. Document sexual intercourse occurred ไม่ถูกต้อง แพทย์ไม่ควร conclude ว่า sexual intercourse occurred ควรบรรยาย physical findings เท่านั้น\n\n❌ E. Send DNA from vaginal swab ไม่ถูกต้อง DNA swab สำคัญแต่ sedative drug testing เป็น more urgent เพราะ drugs metabolize เร็ว";

reasons['NL2-2023-Q272'] = "ชาย 25 ขวบ car accident fracture femur + spleen rupture admitted + surgery 1 วันหลัง surgery expired left calf swollen + painful ถาม cause of death ใน death certificate\n\nCar accident → femur fracture + spleen rupture → surgery → 1 วันหลัง expired + left calf swollen (DVT) → pulmonary embolism\n\nChain of events: trauma → immobilization + surgery → DVT → PE → death\n\nCause of death ใน death certificate: Ia = immediate cause = Pulmonary embolism (ทำให้ตาย) Ib = due to: DVT Ic = due to: Femur fracture + immobilization II = contributing: Spleen rupture + surgery\n\nSwollen painful left calf = deep vein thrombosis ที่ embolize ไป pulmonary artery → fatal PE\n\n✅ C. Pulmonary embolism ถูกต้อง เป็น immediate cause of death\n\n❌ A. Traffic accident ไม่ถูกต้อง เป็น circumstances/manner of death ไม่ใช่ medical cause\n\n❌ B. Splenic rupture ไม่ถูกต้อง ผ่าตัดแก้ไขแล้ว ไม่ใช่ immediate cause of death\n\n❌ D. Fracture of femur ไม่ถูกต้อง เป็น underlying cause ไม่ใช่ immediate cause\n\n❌ E. Complication of surgery ไม่ถูกต้อง ไม่ specific PE เป็น specific cause ที่ควรระบุ";

reasons['NL2-2023-Q273'] = "เด็กหญิงวัยเรียนไข้ + ไอ 3 ม.ค. ไปคลินิกเอกชน 5 ม.ค. ได้ diagnosis acute tonsillitis + antibiotics ดีขึ้น 7 ม.ค. มาโรงพยาบาลรัฐขอใบรับรองแพทย์ แพทย์ควรทำอย่างไร\n\nผู้ป่วยมา 7 ม.ค. ขอใบรับรองแพทย์ แพทย์ที่โรงพยาบาลรัฐสามารถออกใบรับรองแพทย์ได้เฉพาะสิ่งที่ตรวจพบในวันที่มาตรวจ (7 ม.ค.) เท่านั้น ไม่สามารถรับรองผลการตรวจของคลินิกเอกชน (5 ม.ค.) ได้\n\n✅ A. Grant medical certificate for examination on that day ถูกต้อง ออกใบรับรองแพทย์ได้เฉพาะผลการตรวจวันที่มา (7 ม.ค.)\n\n❌ B-E ไม่ถูกต้อง ไม่สามารถออกใบรับรองย้อนหลังสำหรับวันที่ไม่ได้ตรวจ";

reasons['NL2-2023-Q274'] = "ชาย 20 ขวบ drunk มา ER หลังอุบัติเหตุ มีกลิ่นแอลกอฮอล์ conscious cooperative ตำรวจขอตรวจ blood alcohol level ผู้ป่วยปฏิเสธ ถาม management\n\nผู้ป่วย conscious + cooperative (competent) ปฏิเสธการตรวจ blood alcohol level ที่ตำรวจขอ → ต้องเคารพสิทธิ์ผู้ป่วย\n\nผู้ป่วยที่มี competence (conscious, cooperative) มีสิทธิ์ปฏิเสธการตรวจใดๆ ตามหลัก patient autonomy แพทย์ไม่สามารถส่งตรวจ blood alcohol level โดยไม่ได้รับ consent จากผู้ป่วย แม้ตำรวจจะร้องขอ\n\n✅ D. Don't send blood alcohol level test ถูกต้อง เคารพสิทธิ์ผู้ป่วยที่ปฏิเสธ\n\n❌ A. Request for treatment ไม่ถูกต้อง ไม่สามารถ disguise legal test เป็น medical test\n\n❌ B. Comply with Criminal Procedure Code ไม่ถูกต้อง แพทย์ไม่ใช่เจ้าหน้าที่บังคับใช้กฎหมาย ต้อง prioritize patient rights\n\n❌ C. Ask police for breathalyzer ไม่ถูกต้อง ไม่ใช่หน้าที่ของแพทย์\n\n❌ E. State refusal ไม่ถูกต้อง แพทย์ไม่ควรบันทึก refusal ในเอกสารให้ตำรวจ โดยไม่ได้รับ consent จากผู้ป่วย";

reasons['NL2-2023-Q275'] = "เด็กชาย 14 ขวบ ถูกพ่อพามาตรวจยาเสพติดโดยที่เด็กไม่ทราบ มี warning จากครูเรื่องโดดเรียน สูบบุหรี่ ใช้ยา ถาม management\n\nเด็ก 14 ขวบ (minor แต่มี right to know) ถูกนำมาตรวจยาโดยไม่ทราบ → ต้อง inform เด็กก่อนทำการตรวจ\n\nตามหลัก medical ethics + children's rights เด็กวัยรุ่นมีสิทธิ์ที่จะทราบว่าจะถูกตรวจอะไร (informed assent) แม้พ่อจะเป็นผู้ปกครองที่มี authority to consent แต่เด็กต้องได้รับ information เกี่ยวกับ test ก่อน\n\n✅ B. Inform the boy about the test before performing ถูกต้อง เด็กมีสิทธิ์ทราบว่าจะถูกตรวจอะไร (informed assent)\n\n❌ A. Perform urinalysis ไม่ถูกต้อง ทำโดยไม่ inform เด็กก่อนเป็นการละเมิดสิทธิ์\n\n❌ C. Getting to know the boy ไม่ถูกต้อง สร้างสัมพันธ์ดีแต่ต้อง inform about test ก่อน\n\n❌ D. Informed consent from father ไม่ถูกต้อง Parental consent อย่างเดียวไม่เพียงพอ เด็กต้อง assent\n\n❌ E. Refer to psychiatrist ไม่ถูกต้อง ยังไม่ถึงขั้น refer ต้อง evaluate ก่อน";

reasons['NL2-2023-Q276'] = "เด็กหญิง 15 ขวบ severe abdominal pain + hypovolemic shock ผ่าตัดพบ ruptured ectopic pregnancy หลังรักษา เด็กขอให้ไม่เขียน ectopic pregnancy ใน medical record แพทย์เขียน diagnosis เป็นอย่างอื่น ถาม principle ที่ถูกละเมิด\n\nแพทย์เขียน diagnosis ผิดจากความจริงตามคำขอผู้ป่วย → ละเมิด truth telling (honesty/veracity)\n\nMedical record ต้อง accurate + truthful การเขียน false diagnosis เป็นการ violate professional duty + truth telling principle แม้จะทำเพื่อ accommodate patient's request\n\n✅ C. Truth telling ถูกต้อง แพทย์ต้องเขียน medical record ตามความจริง\n\n❌ A. Beneficence ไม่ถูกต้อง Beneficence = ทำในสิ่งที่ดีที่สุดสำหรับผู้ป่วย ไม่ใช่ issue หลักในกรณีนี้\n\n❌ B. Non-maleficence ไม่ถูกต้อง Non-maleficence = do no harm ไม่ใช่ issue หลัก\n\n❌ D. Confidentiality ไม่ถูกต้อง Confidentiality = ไม่เปิดเผยข้อมูลผู้ป่วย ซึ่งแพทย์ต้อง maintain แต่ไม่ได้ถูกละเมิดในกรณีนี้\n\n❌ E. Autonomy ไม่ถูกต้อง Autonomy = สิทธิ์ผู้ป่วยในการตัดสินใจ แต่ autonomy ไม่ extend ไปถึงการขอให้แพทย์เขียน false record";

reasons['NL2-2023-Q277'] = "ผู้ป่วยชาย HIV infection ขอไม่ให้เปิดเผยผลตรวจกับภรรยา ถาม what should physician do\n\nHIV-positive patient ขอไม่บอกภรรยา → ethical dilemma ระหว่าง patient confidentiality vs duty to warn/protect third party\n\nตาม medical ethics guidelines: แพทย์ควร advise/counsel ผู้ป่วยให้บอกภรรยาเอง (patient disclosure) ก่อน เพราะ 1) รักษา doctor-patient trust 2) Patient มี autonomy ที่จะเลือก disclose เอง 3) Partner notification โดยผู้ป่วยเองเป็น most effective approach\n\nถ้าผู้ป่วยปฏิเสธอย่างถาวรหลัง counseling แล้ว แพทย์อาจ consider disclosure ตามกฎหมาย (Tarasoff duty to warn) แต่ initial approach ควรเป็น counseling ก่อนเสมอ\n\n✅ C. Advise the patient to inform his wife himself ถูกต้อง Initial approach: counsel ให้ผู้ป่วย disclose เอง\n\n❌ A. Comply with patient's request ไม่ถูกต้อง Complete compliance อาจ harm ภรรยาที่ไม่ทราบ risk แพทย์มี duty to try counseling\n\n❌ B. Tell the wife immediately ไม่ถูกต้อง Breach confidentiality ทันทีไม่เหมาะสม ต้อง counsel ผู้ป่วยก่อน\n\n❌ D. Consult ethics committee ไม่ถูกต้อง อาจทำได้แต่ initial step ควร counsel ผู้ป่วยก่อน\n\n❌ E. Refer to social worker ไม่ถูกต้อง Social worker ช่วยได้แต่แพทย์ต้อง counsel เองก่อน";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');

  // Final count
  const total = await col.countDocuments({examId: 'NL2-2023'});
  console.log('Total NL2-2023 questions:', total);

  mongoose.disconnect();
}).catch(err => console.error(err.message));
