const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q091'] = "ชายอายุ 47 ปี สุขภาพดี มา screening CA sigmoid บิดาเป็น CA Colon อายุ 55 ปี คำถามเดียวกับข้อ 90 — ผู้ที่มี first-degree relative เป็น CRC ก่อนอายุ 60 ปี จัดเป็น increased risk group ตาม ACS/ACG guidelines ต้อง screening ด้วย colonoscopy เริ่มที่อายุ 40 ปี หรือ 10 ปีก่อนอายุที่ relative ได้รับ diagnosis (55-10=45 ปี) ทุก 5 ปี\n\nColonoscopy เป็น gold standard สำหรับ CRC screening ใน high-risk group เพราะ 1) ดูได้ทั้ง colon ตั้งแต่ cecum ถึง rectum 2) สามารถ detect + remove premalignant polyps พร้อมกัน (diagnostic + therapeutic) 3) sensitivity สูงสุด (95% สำหรับ polyps มากกว่า 1 cm) 4) สามารถ biopsy suspicious lesion ได้ทันที\n\n✅ E. Colonoscopy ถูกต้อง เป็น screening modality ที่แนะนำสำหรับ increased risk group ที่มี family history ของ CRC\n\n❌ A. Stool occult blood test ไม่ถูกต้อง FOBT/FIT เป็น screening สำหรับ average risk population ที่ไม่มี family history ทำทุกปี sensitivity ต่ำ ไม่เพียงพอสำหรับ increased risk group\n\n❌ B. Serum CEA ไม่ถูกต้อง CEA ไม่ใช่ screening tool สำหรับ CRC เพราะ sensitivity และ specificity ต่ำ ใช้สำหรับ monitor treatment response และ detect recurrence เท่านั้น\n\n❌ C. Barium enema ไม่ถูกต้อง ไม่แนะนำเป็น primary screening tool แล้วในปัจจุบัน sensitivity ต่ำกว่า colonoscopy ไม่สามารถ biopsy หรือ remove polyp ได้\n\n❌ D. Sigmoidoscopy ไม่ถูกต้อง ดูได้เฉพาะ left colon (60 cm) ไม่ครอบคลุมทั้ง colon ผู้ป่วย increased risk ต้อง full colonoscopy";

reasons['NL2-2023-Q092'] = "หญิงอายุ 25 ปี มาด้วย painful defecation ร่วมกับ low-grade fever นั่งลำบาก ปวดรอบทวารหนัก สอดนิ้วเข้า anal sphincter ไม่ได้เพราะเจ็บ\n\nKey findings: perianal pain รุนแรงจนสอดนิ้วไม่ได้ + low-grade fever + ปวดนั่ง ทั้งหมดบ่งบอกถึง perianal/anorectal abscess\n\nAnorectal abscess เกิดจาก infection ของ anal glands ที่อยู่ใน intersphincteric space (cryptoglandular theory) เมื่อ anal gland ถูก block ทำให้เกิด stasis + bacterial overgrowth → abscess formation ตำแหน่งของ abscess แบ่งตาม anatomical space ที่ pus สะสม ได้แก่ perianal (พบบ่อยที่สุด 60%), intersphincteric (internal sphincter abscess), ischiorectal, supralevator\n\nInternal sphincter abscess (intersphincteric abscess) มีลักษณะเฉพาะคือ pain ที่รุนแรงมาก อยู่ลึกภายใน anal canal ระหว่าง internal และ external sphincter ทำให้สอดนิ้วตรวจไม่ได้เพราะเจ็บมาก (intense spasm ของ sphincter) มักคลำไม่พบ mass จากภายนอก ต้อง examine under anesthesia (EUA) หรือ imaging (endoanal ultrasound/MRI) low-grade fever บ่งบอก infection\n\n✅ B. Internal sphincter abscess ถูกต้อง อาการ severe perianal pain ที่สอดนิ้วไม่ได้ + low-grade fever เข้ากับ intersphincteric abscess ที่อยู่ลึกใน anal canal ระหว่าง internal และ external sphincter การรักษาคือ incision and drainage ภายใต้ anesthesia\n\n❌ A. Proctalgia fugax ไม่ถูกต้อง เป็น functional anorectal pain ที่เกิดเป็น episode สั้นๆ (วินาทีถึงนาที) มักเกิดตอนกลางคืน ปวดรุนแรงที่ rectum แล้วหายเองอย่างกะทันหัน ไม่มี fever ไม่มี physical findings ตรวจร่างกายปกติ ไม่ใช่ continuous pain with fever แบบนี้\n\n❌ C. Thrombosed external hemorrhoid ไม่ถูกต้อง จะเห็น/คลำ painful, bluish, tense mass ที่ anal margin ได้ชัดเจนจากภายนอก ผู้ป่วยสามารถชี้ตำแหน่งได้ ไม่ได้อยู่ลึกจนสอดนิ้วไม่ได้ และมักไม่มี fever\n\n❌ D. Internal hemorrhoid ไม่ถูกต้อง Internal hemorrhoid มักมาด้วย painless bright red rectal bleeding ไม่ค่อยเจ็บ (เพราะอยู่เหนือ dentate line ซึ่ง innervated by visceral nerves) ยกเว้นมี strangulation/thrombosis แต่ก็ไม่ทำให้ fever\n\n❌ E. Solitary anal ulcer disease (Solitary rectal ulcer syndrome) ไม่ถูกต้อง เป็น chronic condition ที่เกิดจาก mucosal ischemia จาก straining มาด้วย bloody mucoid stool, feeling of incomplete evacuation, perineal pain ไม่มี fever ไม่ทำให้สอดนิ้วไม่ได้";

reasons['NL2-2023-Q093'] = "หญิงอายุ 34 ปี มาด้วย frequent painful defecation with bright red blood staining stool อาการไม่ดีขึ้นหลังใช้ยา 6 เดือน ตรวจพบ longitudinal ulcer ที่ posterior midline of anus ร่วมกับ hypertrophic anal papilla (sentinel pile)\n\nChronic anal fissure — longitudinal ulcer ที่ posterior midline + sentinel pile/hypertrophic anal papilla + ไม่ตอบสนองต่อ conservative treatment 6 เดือน เป็น hallmark ของ chronic anal fissure ที่ต้องการ surgical intervention\n\nAnal fissure แบ่งเป็น acute (น้อยกว่า 6-8 สัปดาห์ ขอบ sharp ไม่มี secondary features) และ chronic (มากกว่า 6-8 สัปดาห์ มี secondary features ได้แก่ sentinel pile, hypertrophied anal papilla, exposed internal sphincter fibers ที่ ulcer base) สาเหตุหลักคือ internal anal sphincter hypertonia ที่ทำให้ blood supply ไปยัง posterior midline ลดลง (watershed area) ทำให้ ulcer ไม่หาย\n\nLateral internal sphincterotomy (LIS) เป็น gold standard surgical treatment สำหรับ chronic anal fissure ที่ failed conservative treatment โดยตัด internal anal sphincter บางส่วน ลด resting anal pressure ทำให้ blood flow ไปยัง fissure ดีขึ้น หายได้ 95% success rate\n\n✅ E. Sphincterotomy ถูกต้อง Lateral internal sphincterotomy เป็น definitive treatment สำหรับ chronic anal fissure ที่ failed 6 เดือนของ conservative treatment มี evidence-based success rate 95%\n\n❌ A. Warm sitz bath ไม่ถูกต้อง เป็น conservative treatment ที่ช่วยลด sphincter spasm ชั่วคราว ใช้สำหรับ acute fissure หรือ initial management ผู้ป่วยรายนี้ไม่ตอบสนองต่อ conservative treatment 6 เดือนแล้ว จึงไม่เพียงพอ\n\n❌ B. Biopsy ไม่ถูกต้อง Biopsy จำเป็นเมื่อ fissure อยู่ในตำแหน่งที่ผิดปกติ (lateral position) หรือสงสัย underlying disease เช่น Crohn's disease, TB, squamous cell carcinoma ผู้ป่วยรายนี้ fissure อยู่ที่ posterior midline ซึ่งเป็น typical location ไม่จำเป็นต้อง biopsy\n\n❌ C. Botulinum A injection ไม่ถูกต้อง Botox injection เข้า internal sphincter เป็น alternative treatment ที่ลด sphincter spasm ได้ชั่วคราว (3-6 เดือน) success rate ต่ำกว่า sphincterotomy (60-80% vs 95%) และมี recurrence rate สูงกว่า จึงไม่ใช่ best answer เมื่อเทียบกับ sphincterotomy\n\n❌ D. Anal dilation ไม่ถูกต้อง Manual anal dilation (Lord's procedure) เคยใช้รักษา chronic fissure แต่ปัจจุบันไม่แนะนำแล้ว เพราะ uncontrolled stretching ของ sphincter ทำให้ risk ของ incontinence สูง (10-20%)";

reasons['NL2-2023-Q094'] = "หญิงอายุ 30 ปี มาด้วย bleeding per anus 5 วัน ประวัติ fresh blood หลังถ่ายเป็นๆ หายๆ 1 ปี Vital signs stable Proctoscope พบ venous dilatation lump with active bleeding above dentate line\n\nKey finding: venous dilatation above dentate line = internal hemorrhoids ที่มี active bleeding\n\nInternal hemorrhoids เกิดจาก engorgement ของ hemorrhoidal venous plexus ที่อยู่เหนือ dentate line (superior hemorrhoidal plexus) แบ่งเป็น 4 degree: Grade I (bleeding only ไม่ prolapse), Grade II (prolapse with straining แล้ว reduce เอง), Grade III (prolapse ต้อง manual reduction), Grade IV (prolapse ไม่สามารถ reduce ได้)\n\nผู้ป่วยรายนี้มี active bleeding + venous dilatation lump above dentate line น่าจะเป็น Grade II-III internal hemorrhoids ที่มี significant bleeding (มาด้วย bleeding 5 วัน)\n\nRubber band ligation (RBL) เป็น standard office-based procedure สำหรับ Grade I-III internal hemorrhoids ที่มี significant bleeding หรือ prolapse โดยใส่ rubber band รัดที่ base ของ hemorrhoid ทำให้ tissue ischemia + necrosis + slough off ภายใน 5-7 วัน มี success rate 70-80% สำหรับ Grade II-III\n\n✅ B. Rubber band ligation ถูกต้อง เป็น first-line procedure สำหรับ symptomatic Grade II-III internal hemorrhoids ที่ conservative treatment ไม่เพียงพอ ทำได้ง่ายใน outpatient setting ไม่ต้อง anesthesia complication rate ต่ำ\n\n❌ A. Steroid suppository ไม่ถูกต้อง Topical steroid/hydrocortisone suppository เป็น conservative treatment ที่ช่วยลด inflammation และ pruritus ไม่หยุดเลือดได้จาก active bleeding hemorrhoid ไม่เป็น definitive treatment\n\n❌ C. Hemorrhoidectomy ไม่ถูกต้อง Surgical hemorrhoidectomy เป็น most effective treatment (95% cure) แต่สงวนไว้สำหรับ Grade III-IV ที่ failed RBL หรือ external hemorrhoids ที่ต้องผ่าตัด เป็น more invasive มี significant postoperative pain และ recovery time นานกว่า RBL ในผู้ป่วยรายนี้ RBL ควรเป็น first-line ก่อน\n\n❌ D. Bulk-forming laxatives ไม่ถูกต้อง Fiber supplements/bulk laxatives เป็น lifestyle modification ที่ช่วย soften stool ลด straining เป็น adjunctive treatment สำหรับ hemorrhoids ทุก grade แต่ไม่เพียงพอเป็น sole treatment เมื่อมี active bleeding ที่ต้อง intervention\n\n❌ E. Gel foam embolism ไม่ถูกต้อง Gel foam embolization ใช้สำหรับ hemorrhage จาก arterial source ผ่าน interventional radiology ไม่ใช่ standard treatment สำหรับ hemorrhoidal bleeding ซึ่งเป็น venous in origin";

reasons['NL2-2023-Q095'] = "ทารกอายุ 1 เดือน ถ่าย meconium ที่ 48 ชั่วโมงหลังคลอด (delayed) มาด้วย abdominal distension 1 สัปดาห์ ตรวจพบ hyperactive bowel sound ไม่มี guarding ไม่มี rebound tenderness\n\nDelayed passage of meconium (มากกว่า 24-48 ชั่วโมง) เป็น key clinical feature ของ Hirschsprung disease ซึ่ง 90% ของ normal term neonates จะถ่าย meconium ภายใน 24 ชั่วโมง ร่วมกับ abdominal distension ในสัปดาห์แรกของชีวิต เป็น classic presentation\n\nHirschsprung disease (congenital aganglionic megacolon) เกิดจาก failure of neural crest cell migration ไปยัง distal bowel ทำให้ myenteric (Auerbach) และ submucosal (Meissner) plexus ไม่มี ganglion cells บริเวณที่ขาด ganglion cells (aganglionic segment) จะอยู่ในสภาพ tonic contraction ตลอดเวลา เพราะไม่มี inhibitory neurons ที่ปล่อย nitric oxide และ VIP เพื่อ relax smooth muscle ทำให้เกิด functional obstruction\n\nSegment ที่ aganglionic มักเริ่มจาก rectum ขึ้นไป (rectosigmoid 80%) ทำให้ stool ไม่สามารถผ่าน aganglionic segment ได้ เกิด proximal bowel dilatation (megacolon) + abdominal distension การวินิจฉัยเบื้องต้นด้วย barium enema (transition zone) + anorectal manometry (absent relaxation of internal sphincter) และ confirmatory diagnosis ด้วย full-thickness rectal biopsy ที่แสดง absent ganglion cells + hypertrophied nerve fibers\n\n✅ A. Hirschsprung disease ถูกต้อง Delayed meconium passage (48 ชม.) + abdominal distension ในทารก 1 เดือน เป็น classic presentation ของ Hirschsprung disease Hyperactive bowel sound เกิดจาก proximal normal bowel ที่พยายาม push stool ผ่าน functional obstruction\n\n❌ B. Neurogenic bowel syndrome ไม่ถูกต้อง Neurogenic bowel เกิดจาก spinal cord injury หรือ congenital spinal anomaly (เช่น spina bifida) ที่ทำให้ bowel motility ผิดปกติ มักมี neurological signs อื่นร่วมด้วย ในทารกที่ไม่มี spinal anomaly จะไม่นึกถึง\n\n❌ C. Anal stenosis ไม่ถูกต้อง Anal stenosis ทำให้ถ่ายลำบาก stool อาจเป็น ribbon-like แต่มักสามารถถ่ายได้บ้าง (ไม่ delayed มากเท่า Hirschsprung) ตรวจทวารหนักจะพบ anus ที่แคบ สอดนิ้วยาก\n\n❌ D. Meconium ileus ไม่ถูกต้อง Meconium ileus เกิดจาก meconium ที่ข้นหนืดผิดปกติอุดตัน terminal ileum พบได้ใน cystic fibrosis มักมาตั้งแต่วันแรกๆ หลังคลอด (ไม่ถ่าย meconium เลย) ร่วมกับ abdominal distension + bilious vomiting ในทารกรายนี้ถ่าย meconium ได้ที่ 48 ชม. แสดงว่า ileum ไม่ได้อุดตัน ปัญหาอยู่ที่ distal colon/rectum\n\n❌ E. Intestinal atresia ไม่ถูกต้อง Intestinal atresia เป็น complete obstruction ตั้งแต่แรกเกิด ทารกจะไม่ถ่าย meconium เลย มี bilious vomiting ตั้งแต่วันแรก X-ray จะเห็น air-fluid levels with no distal gas ทารกรายนี้ถ่าย meconium ได้ที่ 48 ชม. แสดงว่า bowel ไม่ได้ atresia";

reasons['NL2-2023-Q096'] = "ทารกคลอดมาพบ imperforate anus (anorectal malformation) ถามว่าควรตรวจอะไรเพื่อหา associated anomaly\n\nAnorectal malformations (ARM) มักพบร่วมกับ anomalies อื่นในกลุ่ม VACTERL association ซึ่งย่อมาจาก V = Vertebral anomalies, A = Anorectal malformations, C = Cardiac defects, T = Tracheoesophageal fistula, E = Esophageal atresia, R = Renal/urinary anomalies, L = Limb defects\n\nRenal anomalies เป็น associated anomaly ที่พบบ่อยที่สุดใน ARM (พบ 20-50%) ได้แก่ renal agenesis, multicystic dysplastic kidney, vesicoureteral reflux, hydronephrosis ดังนั้น renal ultrasound จึงเป็น mandatory investigation ที่ต้องทำทุกรายที่มี imperforate anus เพื่อ screen renal anomalies เพราะ renal anomalies อาจไม่มีอาการแต่ส่งผลต่อ renal function ในระยะยาว\n\n✅ A. Renal ultrasound ถูกต้อง เป็น mandatory investigation สำหรับทุก ARM เพื่อ screen renal anomalies ที่พบได้ 20-50% ทำง่าย non-invasive ไม่มี radiation\n\n❌ B. Upper GI study ไม่ถูกต้อง ใช้ diagnose esophageal atresia/TEF แต่ esophageal atresia มักมี symptoms ชัดเจน (excessive salivation, choking with feeds) ที่จะ diagnose ได้จาก clinical + NG tube ที่ coil ใน upper pouch ไม่ต้อง upper GI study เป็น routine screening\n\n❌ C. CT brain ไม่ถูกต้อง CNS anomalies ไม่ใช่ส่วนหนึ่งของ VACTERL association และไม่ได้พบร่วมกับ ARM บ่อย ไม่จำเป็นต้องทำ routine\n\n❌ D. Echocardiography ไม่ถูกต้อง แม้ cardiac defects เป็นส่วนหนึ่งของ VACTERL (พบ 10-30%) แต่ renal anomalies พบบ่อยกว่า (20-50%) renal ultrasound จึงเป็น priority แรก Echocardiography อาจทำเพิ่มเติมได้แต่ไม่ใช่ first priority\n\n❌ E. Spinal X-ray ไม่ถูกต้อง Vertebral anomalies พบได้ใน VACTERL แต่ renal ultrasound มี clinical significance มากกว่าเพราะ renal anomalies พบบ่อยกว่าและมีผลต่อ management";

reasons['NL2-2023-Q097'] = "เด็กชาย 3 ขวบ เอาเหรียญ 1 บาทใส่ปาก ไม่มีอาการ ตรวจร่างกายปกติ\n\nForeign body ingestion ในเด็กเป็น common emergency พบบ่อยในเด็กอายุ 6 เดือน - 3 ปี เหรียญเป็น foreign body ที่พบบ่อยที่สุด (60-80% ของ ingested foreign bodies)\n\nเมื่อเด็กกลืน foreign body ขั้นตอนแรกที่สำคัญที่สุดคือ X-ray chest and abdomen (AP + lateral) เพื่อ 1) ยืนยันว่ามี foreign body จริง 2) ระบุตำแหน่ง (esophagus vs stomach vs beyond pylorus) 3) ประเมินว่ามี complication หรือไม่ (free air = perforation)\n\nตำแหน่งของ foreign body determine management: ถ้าอยู่ใน esophagus ต้อง remove ด้วย endoscopy ภายใน 24 ชั่วโมง (risk of pressure necrosis + perforation) ถ้าผ่าน pylorus ไปแล้ว มักจะ pass ออกเองทาง stool ภายใน 4-6 วัน สามารถ observe ได้\n\n✅ C. X-ray plain film chest and abdomen ถูกต้อง เป็น initial investigation ที่จำเป็นเพื่อ localize foreign body และ guide management เหรียญเป็น radiopaque จะเห็นชัดใน X-ray\n\n❌ A. Reassure ไม่ถูกต้อง ไม่สามารถ reassure ได้โดยไม่ทราบตำแหน่งของ foreign body เพราะถ้าเหรียญติดอยู่ใน esophagus จะ erode ผ่าน wall ได้ ต้อง X-ray ก่อนเสมอ\n\n❌ B. Laxative ไม่ถูกต้อง ไม่แนะนำให้ laxative เพราะไม่ช่วยเร่ง passage ของ foreign body และอาจทำให้เกิด complication ถ้า foreign body ติดที่ใดที่หนึ่ง\n\n❌ D. NPO, admit, observing for 24 hours ไม่ถูกต้อง การ NPO + admit โดยไม่ทำ X-ray ก่อนไม่เหมาะสม ต้อง localize foreign body ก่อนเพื่อ determine ว่าต้อง admit หรือไม่ ถ้าเหรียญอยู่ใน stomach แล้วสามารถ observe outpatient ได้\n\n❌ E. EGD (Esophagogastroduodenoscopy) ไม่ถูกต้อง EGD ทำเมื่อ X-ray ยืนยันว่า foreign body อยู่ใน esophagus หรือ stomach ที่ต้อง remove (เช่น sharp object, battery, magnet) ไม่ใช่ initial management ต้อง X-ray localize ก่อน";

reasons['NL2-2023-Q098'] = "ทารกชายอายุ 3 เดือน มาด้วย scrotal sac mass ตั้งแต่เกิด ตรวจพบ scrotal enlargement 2.5 cm transillumination positive silk sign negative คลำ right testis ไม่พบ Left testis + penis ปกติ\n\nTransillumination positive = fluid-filled (hydrocele) silk sign negative = ไม่มี patent processus vaginalis ที่ communicate กับ peritoneal cavity (non-communicating hydrocele) ถ้า silk sign positive หมายถึง communicating hydrocele/inguinal hernia\n\nHydrocele ในทารกเกิดจาก processus vaginalis ที่ปกติจะ obliterate ก่อนคลอด ไม่ปิดสนิท ทำให้ peritoneal fluid ลงมาสะสมรอบ testis ใน tunica vaginalis ทำให้ scrotum โต\n\nHydrocele ในทารกอายุน้อยกว่า 12-24 เดือน ส่วนใหญ่ resolve เอง เมื่อ processus vaginalis obliterate สมบูรณ์ ดังนั้น standard management คือ observation/reassurance จนถึงอายุ 12-24 เดือน ถ้ายังไม่หายจึงค่อยพิจารณา surgical repair\n\n✅ A. Observe ถูกต้อง เป็น standard management สำหรับ hydrocele ในทารกอายุ 3 เดือน เพราะ majority resolve spontaneously ภายใน 12-24 เดือน\n\n❌ B. Incision & drainage ไม่ถูกต้อง Hydrocele ไม่ใช่ abscess ไม่ต้อง I&D fluid จะกลับมาสะสมอีก\n\n❌ C. Hydrocelectomy ไม่ถูกต้อง Surgery สงวนไว้เมื่อ hydrocele ไม่ resolve หลังอายุ 12-24 เดือน หรือเป็น communicating hydrocele ที่ size เปลี่ยนแปลง\n\n❌ D. Aspiration ไม่ถูกต้อง การ aspirate fluid จะกลับมาใหม่ มี risk of infection ไม่แนะนำ\n\n❌ E. Orchiopexy ไม่ถูกต้อง Orchiopexy ใช้สำหรับ undescended testis (cryptorchidism) โจทย์บอกว่า right testis unpalpable ซึ่งอาจเป็น retractile testis หรือถูก obscure ด้วย hydrocele แต่ primary problem ตอนนี้คือ hydrocele ที่ควร observe ก่อน";

reasons['NL2-2023-Q099'] = "เด็กไทยชายอายุ 6 เดือน มาด้วย hydrocele ถามว่าการรักษาคืออะไร\n\nHydrocele ในทารกอายุ 6 เดือน — เช่นเดียวกับ Q98 standard management คือ observation เพราะ processus vaginalis มักจะ obliterate เองภายในขวบปีแรก ทำให้ hydrocele resolve โดยไม่ต้องผ่าตัด ถ้าหลังอายุ 12-24 เดือนยังไม่หาย หรือ hydrocele ใหญ่ขึ้นเรื่อยๆ (อาจเป็น communicating type) จึงค่อยพิจารณา surgical repair\n\n✅ A. Observe ถูกต้อง เป็น standard management สำหรับ infant hydrocele เพราะ spontaneous resolution rate สูงมาก\n\n❌ B. Hydrocelectomy ไม่ถูกต้อง ไม่จำเป็นในทารกที่อายุน้อยกว่า 1-2 ปี ควร observe ก่อน\n\n❌ C. Aspiration ไม่ถูกต้อง ไม่แนะนำเพราะ fluid recurs และมี infection risk\n\n❌ D. Scrotal support and NSAIDs ไม่ถูกต้อง ใช้สำหรับ epididymitis ไม่ใช่ hydrocele\n\n❌ E. Inguinal hernia repair ไม่ถูกต้อง Hydrocele ไม่ใช่ hernia แม้ทั้งสองจะเกิดจาก patent processus vaginalis แต่ hernia มี bowel content ใน sac ส่วน hydrocele มีแค่ fluid";

reasons['NL2-2023-Q100'] = "เด็กชายอายุ 13 ปี มาด้วย right testicular pain หลังเล่นเทนนิส 4 ชม. ก่อน ตรวจพบ vital signs stable, erythematous + generalized swelling ของ right scrotum, testis อยู่ในตำแหน่ง transverse (horizontal lie), pain aggravated (คาดว่า cremasteric reflex absent)\n\nKey findings: วัยรุ่น + acute testicular pain + transverse lie ของ testis เป็น classic presentation ของ testicular torsion ซึ่งเป็น surgical emergency\n\nTesticular torsion เกิดจาก spermatic cord บิดตัว ทำให้ blood supply ไปยัง testis ถูกตัด (venous obstruction ก่อน ตามด้วย arterial obstruction) ถ้าไม่แก้ไขภายใน 6 ชั่วโมง testis จะ infarct และ non-salvageable (salvage rate: ภายใน 6 ชม. = 90-100%, 6-12 ชม. = 50%, มากกว่า 12 ชม. = น้อยกว่า 10%)\n\nTransverse lie (horizontal testis) เป็น classic sign ของ torsion เกิดจาก spermatic cord ที่บิดทำให้ testis หมุนจาก vertical เป็น transverse position เรียกว่า bell clapper deformity ที่ predispose ให้เกิด torsion\n\nผู้ป่วยรายนี้มาหลัง onset 4 ชั่วโมง ยังอยู่ใน window period ที่ salvageable ต้อง surgical exploration ทันทีเพื่อ detorse testis + assess viability + orchiopexy (ทั้งสองข้าง) ไม่ควร delay ด้วย imaging\n\n✅ D. Surgical exploration of right scrotum ถูกต้อง เป็น emergency surgery ที่ต้องทำทันทีเมื่อ clinical diagnosis ชัดเจน (acute testicular pain + transverse lie) โดยไม่ต้องรอ imaging ระหว่าง surgery จะ detorse spermatic cord, assess testis viability, ทำ orchiopexy ทั้งสองข้าง\n\n❌ A. NSAIDs ไม่ถูกต้อง NSAIDs เป็น pain management เท่านั้น ไม่แก้ cause ของ torsion ถ้า delay surgery ด้วยการให้แค่ pain relief testis จะ infarct\n\n❌ B. Manual reduction ไม่ถูกต้อง Manual detorsion (open the book technique) อาจ attempt ได้เป็น temporizing measure ในขณะเตรียม OR แต่ไม่ใช่ definitive treatment เพราะ 1) ไม่แน่ใจว่า detorse สำเร็จหรือไม่ 2) ยังต้อง orchiopexy เพื่อป้องกัน recurrence 3) อาจ detorse ผิดทิศทาง\n\n❌ C. Doppler ultrasound of testis ไม่ถูกต้อง Doppler US สามารถ confirm ว่า blood flow ลดลง/absent ใน torsion ได้ แต่เมื่อ clinical presentation ชัดเจน (acute pain + transverse lie + adolescent) ไม่ควร delay surgery เพื่อรอทำ imaging เพราะทุกนาทีที่ delay คือ testis ที่ขาดเลือดเพิ่มขึ้น Imaging สงวนไว้เมื่อ diagnosis ไม่แน่ใจ\n\n❌ E. IV antibiotics for epididymitis ไม่ถูกต้อง Epididymitis มาด้วย gradual onset pain, fever, urinary symptoms, positive Prehn sign (pain relieved by elevation) ผู้ป่วยรายนี้เป็น acute onset หลัง physical activity, transverse lie ซึ่งเข้ากับ torsion มากกว่า epididymitis ในเด็กวัยรุ่นต้อง rule out torsion ก่อนเสมอ";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');

  // Count progress
  const total = await col.countDocuments({examId: 'NL2-2023', isAudited: {'$ne': true}});
  console.log('Total unaudited remaining:', total);

  mongoose.disconnect();
}).catch(err => console.error(err.message));
