const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q146'] = "เด็กชาย 15 ขวบ HIV infection มี left otorrhea otalgia eardrum perforation right hemiparesis right facial weakness motor power grade III ถาม diagnosis\n\nHIV + chronic otitis media (otorrhea + TM perforation) + focal neurological deficits (hemiparesis + facial weakness) → intracranial extension ของ infection จาก ear → brain abscess\n\nBrain abscess เกิดจาก direct extension ของ chronic suppurative otitis media (CSOM) ผ่าน temporal bone ไปสู่ temporal lobe หรือ cerebellum ของสมอง เชื้อที่พบบ่อย ได้แก่ mixed flora (aerobes + anaerobes) ใน HIV patient อาจพบ opportunistic organisms ได้ด้วย\n\nContralateral hemiparesis (right) + ipsilateral facial weakness (right = อาจเป็น upper motor neuron type) บ่งบอกว่ามี space-occupying lesion ใน brain ที่กดทับ motor cortex/corticospinal tract\n\n✅ A. Brain abscess ถูกต้อง CSOM + HIV + focal neurological deficits = otogenic brain abscess จาก direct extension\n\n❌ B. Toxoplasmosis ไม่ถูกต้อง Toxoplasma ใน HIV มี ring-enhancing lesion ใน brain แต่มักเกิดเมื่อ CD4 < 100 มักเป็น multiple lesions ที่ basal ganglia ไม่สัมพันธ์กับ CSOM\n\n❌ C. Cysticercosis ไม่ถูกต้อง Neurocysticercosis มี calcified granulomas/cysts ใน brain มักมา seizure เป็นหลัก ไม่สัมพันธ์กับ ear infection\n\n❌ D. TB ไม่ถูกต้อง TB meningitis มี chronic meningitis pattern (headache, fever, cranial nerve palsies) ไม่ใช่ focal mass lesion ที่สัมพันธ์กับ CSOM\n\n❌ E. CNS lymphoma ไม่ถูกต้อง Primary CNS lymphoma ใน HIV มักเกิดเมื่อ CD4 < 50 เป็น single periventricular enhancing lesion ไม่สัมพันธ์กับ ear infection";

reasons['NL2-2023-Q147'] = "เด็กไทยชาย 5 ขวบ altered consciousness 1 วัน high-grade fever + sore throat 3 วัน BT 38.2 PR 100 RR 24 BP 90/60 ตรวจพบ shallow ulcer ที่ anterior pillar vesicles ที่ soles of feet ถาม causative organism\n\nFever + sore throat + oral ulcer at anterior pillar + vesicles on soles → Hand-Foot-Mouth Disease (HFMD) ร่วมกับ altered consciousness (encephalitis/CNS involvement)\n\nHFMD ที่มี CNS complications (encephalitis, brainstem encephalitis, pulmonary edema) มักเกิดจาก Enterovirus 71 (EV71) ซึ่งเป็น serotype ที่มี neurotropism สูง ต่างจาก Coxsackievirus A16 ที่มักทำให้ HFMD แบบ uncomplicated\n\nEV71 encephalitis มี predilection สำหรับ brainstem ทำให้เกิด brainstem encephalitis ที่อาจมี myoclonus, ataxia, cranial nerve palsies และอาจ progress เป็น neurogenic pulmonary edema ซึ่งเป็น life-threatening complication\n\n✅ A. Enterovirus 71 ถูกต้อง เป็น cause ของ HFMD with CNS complications (encephalitis) ใน Southeast Asia\n\n❌ B. Coxsackie B ไม่ถูกต้อง Coxsackie B ทำให้ myocarditis, pleurodynia (Bornholm disease) ไม่ใช่ classic cause ของ HFMD with encephalitis\n\n❌ C. Parvovirus B19 ไม่ถูกต้อง ทำให้ erythema infectiosum (fifth disease) ด้วย slapped cheek rash ไม่ใช่ HFMD pattern\n\n❌ D. HSV ไม่ถูกต้อง HSV gingivostomatitis มี vesicles/ulcers ทั่ว oral mucosa + gingiva ไม่ใช่เฉพาะ anterior pillar และไม่มี hand/foot vesicles\n\n❌ E. VZV ไม่ถูกต้อง Varicella มี generalized vesicular rash ใน different stages (crop lesions) ไม่ใช่ HFMD pattern ที่จำกัดเฉพาะ hands, feet, mouth";

reasons['NL2-2023-Q148'] = "เด็ก 5 ขวบ abdominal pain 2 วัน ประวัติ rash + joint pain 1 สัปดาห์ก่อน no fever vital signs stable rash ที่ legs and feet ถาม most serious complication\n\nPalpable purpura ที่ legs/feet + joint pain + abdominal pain + no fever → IgA vasculitis (Henoch-Schonlein purpura/HSP)\n\nHSP เป็น small vessel vasculitis จาก IgA immune complex deposition มี classic tetrad: 1) Palpable purpura (ที่ legs, buttocks) 2) Arthritis/arthralgia 3) Abdominal pain (GI involvement) 4) Renal involvement (glomerulonephritis)\n\nMost serious complication ของ HSP คือ renal involvement (IgA nephropathy/nephritis) เพราะอาจ progress เป็น chronic kidney disease ในบาง cases (5-10%) IgA deposits ที่ glomerular mesangium ทำให้ mesangial proliferative GN เช่นเดียวกับ IgA nephropathy ที่เป็น primary disease\n\nSkin, joint, GI involvement ของ HSP มักเป็น self-limited หายเองภายในสัปดาห์ แต่ renal damage อาจ persistent ดังนั้น long-term follow-up ต้อง monitor urine (proteinuria, hematuria) + renal function\n\n✅ C. Kidney damage ถูกต้อง เป็น most serious long-term complication ของ HSP ที่อาจ progress เป็น CKD\n\n❌ A. Anemia ไม่ถูกต้อง Anemia ไม่ใช่ major complication ของ HSP\n\n❌ B. Carditis ไม่ถูกต้อง Carditis ไม่ใช่ feature ของ HSP (เป็น feature ของ acute rheumatic fever)\n\n❌ D. GI hemorrhage ไม่ถูกต้อง GI bleeding อาจเกิดได้ใน HSP แต่มักเป็น self-limited ไม่ใช่ most serious long-term complication\n\n❌ E. Intracerebral hemorrhage ไม่ถูกต้อง CNS involvement ใน HSP พบน้อยมาก (< 1%) ไม่ใช่ most serious complication";

reasons['NL2-2023-Q149'] = "เด็กมี fever + petechiae ที่ both legs (likely meningococcemia) ถาม complication ที่ต้อง closely monitor\n\nFever + petechiae → meningococcemia (Neisseria meningitidis bacteremia) ซึ่งเป็น medical emergency\n\nMeningococcemia สามารถทำให้เกิด fulminant course ภายในชั่วโมง สาเหตุ mortality หลักคือ Waterhouse-Friderichsen syndrome ซึ่งเป็น bilateral adrenal hemorrhage/necrosis จาก DIC ที่เกิดจาก meningococcal endotoxin ทำให้ massive adrenal insufficiency → refractory shock\n\nAdrenal insufficiency ใน meningococcemia ต้อง monitor closely เพราะ 1) เกิดเร็วมาก 2) ทำให้ refractory hypotension ที่ไม่ตอบสนองต่อ fluid + vasopressor 3) ต้อง stress-dose hydrocortisone ทันที\n\n✅ B. Adrenal insufficiency ถูกต้อง Waterhouse-Friderichsen syndrome (bilateral adrenal hemorrhage) เป็น classic life-threatening complication ของ meningococcemia ที่ต้อง monitor\n\n❌ A. Anemia ไม่ถูกต้อง ไม่ใช่ primary complication ที่ต้อง closely monitor\n\n❌ C. GI bleeding ไม่ถูกต้อง ไม่ใช่ characteristic complication ของ meningococcemia\n\n❌ D. Intracranial hemorrhage ไม่ถูกต้อง อาจเกิดได้จาก DIC แต่ไม่ใช่ most important complication เมื่อเทียบกับ adrenal insufficiency\n\n❌ E. DIC ไม่ถูกต้อง DIC เป็น mechanism ที่ทำให้เกิด adrenal hemorrhage/insufficiency แต่โจทย์ถามเฉพาะ complication ที่ต้อง monitor โดย adrenal insufficiency เป็น specific complication ที่ treatable ด้วย hydrocortisone";

reasons['NL2-2023-Q150'] = "ผู้ป่วย meningococcemia ถาม prophylaxis สำหรับ close family contacts\n\nNeisseria meningitidis แพร่กระจายผ่าน respiratory droplets จาก nasopharyngeal carriage Close contacts (household, คนอยู่ร่วมบ้าน) มี risk 500-800 เท่าของ general population ต้องให้ chemoprophylaxis ภายใน 24 ชม.\n\nRifampicin เป็น first-line chemoprophylaxis สำหรับ meningococcal disease ขนาด 600 mg PO ทุก 12 ชม. นาน 2 วัน (4 doses) สำหรับผู้ใหญ่ 10 mg/kg/dose สำหรับเด็ก > 1 เดือน Rifampicin สะสมใน nasopharyngeal secretions ได้ดี eradicate carriage ได้ > 90% Alternatives: ciprofloxacin 500 mg single dose PO หรือ ceftriaxone 250 mg IM single dose\n\n✅ D. Rifampicin ถูกต้อง First-line chemoprophylaxis สำหรับ meningococcal disease\n\n❌ A. Throat swab ไม่ถูกต้อง Screening culture ไม่แนะนำ ให้ prophylaxis ทุก contact โดยไม่ต้องรอผล culture\n\n❌ B. Nasopharyngeal swab ไม่ถูกต้อง เหมือน A ไม่ต้อง screen ให้ prophylaxis เลย\n\n❌ C. Azithromycin ไม่ถูกต้อง ไม่ใช่ standard prophylaxis สำหรับ meningococcal disease\n\n❌ E. Ofloxacin ไม่ถูกต้อง Fluoroquinolone ที่ approved คือ ciprofloxacin ไม่ใช่ ofloxacin";

reasons['NL2-2023-Q151'] = "เด็กหญิง 9 เดือน fever + rash ไม่ได้ทานยาก่อนมี rash BT 38.5 Skin: erythroderma scaly erythematous patches with desquamation around eyes nose mouth genital ถาม diagnosis\n\nInfant + fever + erythroderma + desquamation around eyes, nose, mouth, genital (perioral, periorbital = periorificial) → Staphylococcal Scalded Skin Syndrome (SSSS)\n\nSSSS เกิดจาก exfoliative toxins (ET-A, ET-B) ของ Staphylococcus aureus phage group II toxins จะ target desmoglein-1 ซึ่งเป็น desmosomal cadherin ที่อยู่ใน granular layer ของ epidermis ทำให้ intraepidermal cleavage ที่ granular layer → superficial skin separation/desquamation\n\nSSSS พบบ่อยในเด็กอายุน้อยกว่า 5 ปี (โดยเฉพาะ neonates + infants) เพราะ immature renal function ไม่สามารถ clear toxins ได้เร็วพอ + ขาด anti-toxin antibodies\n\nNikolsky sign positive (skin slippage เมื่อกดถู) Perioral/periorificial distribution (รอบตา จมูก ปาก genital) เป็น characteristic pattern\n\n✅ E. SSSS ถูกต้อง Infant + erythroderma + periorificial desquamation + fever = classic SSSS\n\n❌ A. Impetigo ไม่ถูกต้อง Impetigo เป็น localized S. aureus skin infection (honey-crusted lesions) ไม่ใช่ generalized erythroderma\n\n❌ B. Scarlet fever ไม่ถูกต้อง Scarlet fever มี sandpaper-like rash + strawberry tongue + pharyngitis + Pastia lines จาก GAS toxin ไม่มี desquamation pattern แบบ SSSS\n\n❌ C. Kawasaki disease ไม่ถูกต้อง Kawasaki มี fever >5 วัน + conjunctival injection + lip/oral changes + cervical LAD + extremity changes + polymorphous rash ผู้ป่วยรายนี้ไม่ครบ criteria\n\n❌ D. TEN (Toxic Epidermal Necrolysis) ไม่ถูกต้อง TEN เป็น drug reaction ที่มี full-thickness epidermal necrosis (ต่างจาก SSSS ที่ superficial) ผู้ป่วยรายนี้ไม่ได้ทานยาก่อนมี rash histology จะแตกต่าง: TEN = subepidermal split, SSSS = intraepidermal split";

reasons['NL2-2023-Q152'] = "ทารก 1 เดือน small clean dew-deep flaccid vesicles ที่ forehead neck upper trunk occluded area BT 37 ถาม management\n\nSmall superficial clear vesicles (dew-drop appearance) ที่ occluded areas + no fever ในทารก 1 เดือน → miliaria crystallina\n\nMiliaria crystallina เกิดจาก eccrine sweat duct obstruction ที่ระดับ stratum corneum (most superficial level) ทำให้ sweat retention vesicles เป็น tiny (1-2 mm) clear non-inflammatory vesicles ที่ rupture ง่าย พบที่บริเวณที่ occluded/sweating มาก เป็น benign self-limited condition ที่หายเองเมื่อลด heat + humidity\n\n✅ A. Reassure ถูกต้อง Miliaria crystallina เป็น benign condition หายเองโดยไม่ต้องรักษา แค่ลด excessive clothing + heat\n\n❌ B. Emollient ไม่ถูกต้อง ไม่จำเป็นและอาจทำให้ occlusion แย่ลง\n\n❌ C. Topical mupirocin ไม่ถูกต้อง ไม่ใช่ infection ไม่ต้อง antibiotic\n\n❌ D. Topical steroid ไม่ถูกต้อง ไม่มี inflammation ที่ต้อง steroid\n\n❌ E. Topical antifungal ไม่ถูกต้อง ไม่ใช่ fungal infection";

reasons['NL2-2023-Q153'] = "เด็กมี itching ที่ interdigital spaces พ่อมีอาการเดียวกัน ถาม management\n\nItching ที่ interdigital spaces (web spaces between fingers) + family member มีอาการเหมือนกัน → scabies (หิด)\n\nScabies เกิดจาก Sarcoptes scabiei var. hominis ที่ burrow เข้าไปใน stratum corneum ทำให้เกิด intense itching (type IV hypersensitivity) ตำแหน่งที่พบบ่อย: interdigital web spaces, wrists, axillae, waistline, genitalia ลักษณะเฉพาะคือ itching ที่แย่ลงตอนกลางคืน + family/close contact involvement\n\nBenzoyl benzoate เป็น scabicidal agent ที่ใช้ได้ในเด็ก (10-25% lotion) ทาทั้งตัวจาก neck ลงไป ทิ้งไว้ 24 ชม. ล้างออก ทำซ้ำวันที่ 3 ต้องรักษาทุกคนในบ้านพร้อมกัน\n\n✅ B. Benzoyl benzoate ถูกต้อง เป็น scabicidal agent ที่ effective สำหรับ scabies\n\n❌ A. Mupirocin ointment ไม่ถูกต้อง Mupirocin เป็น topical antibiotic สำหรับ bacterial skin infection (impetigo) ไม่ฆ่า scabies mite\n\n❌ C. Topical steroid ไม่ถูกต้อง Steroid ลด itching ได้บ้างแต่ไม่ฆ่า mite ปัญหา persist + spread\n\n❌ D. Topical antibiotic ไม่ถูกต้อง ไม่ใช่ bacterial infection\n\n❌ E. Topical antifungal ไม่ถูกต้อง ไม่ใช่ fungal infection";

reasons['NL2-2023-Q154'] = "เด็กชาย 10 ขวบ skin lesion ที่หน้า 3 วัน BT 37 honey crusted surrounded by erythema ที่ nose + upper lip ถาม management\n\nHoney-colored crusted lesion ที่ face (nose, upper lip) → impetigo (non-bullous type)\n\nImpetigo เป็น superficial bacterial skin infection พบบ่อยที่สุดในเด็ก สาเหตุหลักคือ Staphylococcus aureus และ Group A Streptococcus non-bullous type (70% of cases) มี golden/honey-colored crusts ที่ form over vesicles/pustules ที่ rupture\n\nLocalized impetigo (few lesions) รักษาด้วย topical antibiotic ยาที่แนะนำคือ mupirocin ointment 2% ทา 3 ครั้ง/วัน นาน 5-7 วัน Mupirocin ออกฤทธิ์ยับยั้ง isoleucyl-tRNA synthetase ทำให้ bacteria ไม่สามารถ synthesize protein ได้ effective ต่อ S. aureus + GAS\n\n✅ C. Mupirocin ointment ถูกต้อง First-line topical treatment สำหรับ localized impetigo\n\n❌ A. Wet dressing with NSS ไม่ถูกต้อง NSS dressing ช่วย remove crusts ได้แต่ไม่ treat infection\n\n❌ B. Acyclovir cream ไม่ถูกต้อง ใช้สำหรับ herpes simplex ไม่ใช่ bacterial impetigo\n\n❌ D. Clotrimazole cream ไม่ถูกต้อง เป็น antifungal ไม่ใช่ bacterial infection\n\n❌ E. Mometasone cream ไม่ถูกต้อง เป็น topical steroid ที่อาจทำให้ infection แย่ลง ไม่เหมาะสำหรับ infectious condition";

reasons['NL2-2023-Q155'] = "ทารกชาย 1 เดือน slowly progressive scalp mass ตั้งแต่เกิด ตรวจพบ solitary mass ที่ scalp อื่นๆ ปกติ ถาม management\n\nScalp mass ตั้งแต่เกิดที่ค่อยๆ โตขึ้น (slowly progressive) ในทารก 1 เดือน → infantile hemangioma\n\nInfantile hemangioma เป็น most common benign vascular tumor ในทารก (4-10% ของ infants) เกิดจาก abnormal proliferation ของ endothelial cells มักปรากฏใน 1-2 สัปดาห์แรกหลังคลอดแล้วโตขึ้นอย่างรวดเร็วในช่วง proliferative phase (0-12 เดือน) ก่อนจะค่อยๆ involution ใน 1-5 ปี\n\nPropranolol เป็น first-line treatment สำหรับ problematic infantile hemangioma ตั้งแต่ปี 2008 ออกฤทธิ์ผ่านหลายกลไก: vasoconstriction (ลดสีแดง/ขนาดได้เร็วภายใน 24-48 ชม.), inhibit VEGF expression (ลด angiogenesis), induce apoptosis ของ endothelial cells ขนาด 2-3 mg/kg/day PO\n\nIndications สำหรับ treatment ได้แก่ functional impairment (eyelid → amblyopia, airway obstruction), ulceration, disfigurement (facial location), rapidly growing\n\n✅ B. Propranolol ถูกต้อง First-line treatment สำหรับ infantile hemangioma ที่ต้องการ treatment\n\n❌ A. Reassure ไม่ถูกต้อง Observation alone เหมาะสำหรับ small non-problematic hemangiomas ที่ไม่อยู่ในตำแหน่งเสี่ยง scalp hemangioma ที่ actively growing ควร treat เพื่อป้องกัน complications\n\n❌ C. Intralesional steroid ไม่ถูกต้อง เคยเป็น first-line ก่อนปี 2008 แต่ propranolol มี efficacy สูงกว่าและ side effects น้อยกว่า\n\n❌ D. Laser therapy ไม่ถูกต้อง Pulsed dye laser ใช้สำหรับ superficial/residual telangiectasia ไม่ effective สำหรับ deep/proliferating hemangioma\n\n❌ E. Surgical removal ไม่ถูกต้อง Surgery สงวนไว้สำหรับ hemangioma ที่ไม่ตอบสนองต่อ medical therapy หรือ residual tissue หลัง involution";

reasons['NL2-2023-Q156'] = "เด็กชาย 15 ขวบ neck + groin masses 3 เดือน night fever + weight loss (B symptoms) ตรวจพบ multiple 2-4 cm painless cervical + groin lymph nodes CBC Hb 11.5 WBC 12,000 (N60% L35%) platelet 180,000 ถาม investigation\n\nMultiple painless lymphadenopathy ที่ non-contiguous sites (cervical + groin) + B symptoms (night fever, weight loss) 3 เดือน → suspect lymphoma\n\nLymphoma เป็น malignant lymphoproliferative disorder ที่พบบ่อยในวัยรุ่น Hodgkin lymphoma (HL) มักมา present ด้วย painless cervical lymphadenopathy + B symptoms (fever, night sweats, weight loss >10%) Non-Hodgkin lymphoma (NHL) ก็เป็นไปได้\n\nDefinitive diagnosis ของ lymphoma ต้องทำ lymph node biopsy (excisional biopsy preferred) เพื่อดู histology ได้แก่ Reed-Sternberg cells ใน Hodgkin lymphoma หรือ specific subtypes ของ NHL ร่วมกับ immunohistochemistry\n\n✅ E. Lymph node biopsy ถูกต้อง เป็น definitive diagnostic procedure สำหรับ suspected lymphoma\n\n❌ A. Chest x-ray ไม่ถูกต้อง CXR อาจเห็น mediastinal mass ใน HL แต่ไม่ให้ tissue diagnosis\n\n❌ B. CT head & neck ไม่ถูกต้อง CT ช่วย staging แต่ไม่ให้ histological diagnosis\n\n❌ C. Gastric wash for AFB stain ไม่ถูกต้อง ใช้สำหรับ suspected TB ไม่ใช่ lymphoma\n\n❌ D. Bone marrow study ไม่ถูกต้อง BM biopsy ใช้สำหรับ staging ของ lymphoma หรือ diagnosis ของ leukemia ไม่ใช่ initial diagnostic procedure สำหรับ lymphadenopathy";

reasons['NL2-2023-Q157'] = "เด็ก 2 ขวบ fever + fatigue ประวัติ neonatal jaundice ได้ phototherapy ตรวจพบ BT 38 PR 120 RR 24 BP 90/60 Liver 1 cm BRCM (span 7 cm) Spleen 2 cm BLCM moderate pallor mild jaundice ถาม investigation\n\nChronic hemolytic anemia (pallor + jaundice + hepatosplenomegaly) + neonatal jaundice history ในเด็กไทย 2 ขวบ → thalassemia disease เป็น most likely diagnosis\n\nThalassemia เป็น inherited hemoglobinopathy ที่พบบ่อยที่สุดใน Southeast Asia ผู้ป่วยมี chronic hemolysis ตั้งแต่เด็ก มาด้วย pallor (anemia) + jaundice (hemolysis) + hepatosplenomegaly (extramedullary hematopoiesis + RES hyperplasia) มักมี history ของ neonatal jaundice ที่ต้อง phototherapy\n\nHemoglobin typing (Hb electrophoresis/HPLC) เป็น definitive diagnostic test ที่บอก type ของ thalassemia ได้แก่ Hb Bart's (alpha-thal), Hb H (Hb H disease), elevated Hb F (beta-thal major), Hb E (Hb E/beta-thal)\n\n✅ C. Hb typing ถูกต้อง เป็น definitive diagnostic test สำหรับ thalassemia\n\n❌ A. Mycoplasma titer ไม่ถูกต้อง ไม่เกี่ยวกับ chronic hemolytic anemia\n\n❌ B. LFT ไม่ถูกต้อง LFT อาจ elevated จาก hemolysis (indirect bilirubin สูง) แต่ไม่ให้ specific diagnosis\n\n❌ D. Red cell flow cytometry ไม่ถูกต้อง ใช้สำหรับ PNH (detect CD55/CD59 deficiency) ไม่ใช่ thalassemia\n\n❌ E. Direct antiglobulin test (DAT) ไม่ถูกต้อง DAT ใช้ diagnose autoimmune hemolytic anemia ซึ่ง uncommon ในเด็ก 2 ขวบ thalassemia เป็น likely diagnosis มากกว่า";

reasons['NL2-2023-Q158'] = "เด็กชาย 2 ขวบ abdominal pain + watery diarrhea → วันนี้ bloody diarrhea BT 38 PR 90/60 RR 30 CBC: Hct 7% (น่าจะเป็น Hb 7) WBC 13,500 Platelet 50,000 PBS: MAHA (schistocyte) BUN 35 Cr 3 ถาม diagnosis\n\nDiarrhea (initially watery → bloody) + microangiopathic hemolytic anemia (MAHA with schistocytes) + thrombocytopenia + acute renal failure (BUN 35, Cr 3) → classic triad ของ Hemolytic Uremic Syndrome (HUS)\n\nHUS เป็น thrombotic microangiopathy ที่พบบ่อยที่สุดในเด็ก สาเหตุ 90% คือ Shiga toxin-producing E. coli (STEC) O157:H7 หรือ O104:H4 Shiga toxin ทำลาย endothelial cells ของ glomerular capillaries → platelet activation/consumption → microthrombi formation → RBCs ถูก fragmentation ขณะผ่าน narrowed vessels (schistocytes) → renal failure จาก thrombotic microangiopathy\n\nClassic triad ของ HUS: 1) MAHA (hemolytic anemia + schistocytes + negative Coombs) 2) Thrombocytopenia 3) Acute renal failure ทั้ง 3 มีครบในผู้ป่วยรายนี้\n\n✅ C. HUS ถูกต้อง Bloody diarrhea prodrome + MAHA + thrombocytopenia + renal failure เป็น classic typical (diarrhea+) HUS\n\n❌ A. ITP ไม่ถูกต้อง ITP มีแค่ isolated thrombocytopenia ไม่มี MAHA หรือ renal failure\n\n❌ B. TTP ไม่ถูกต้อง TTP มี pentad (MAHA + thrombocytopenia + renal failure + neurological symptoms + fever) คล้าย HUS แต่ TTP พบในผู้ใหญ่ ไม่ค่อยมี preceding diarrhea ในเด็กที่มี diarrhea prodrome → HUS ไม่ใช่ TTP\n\n❌ D. DIC ไม่ถูกต้อง DIC มี consumption coagulopathy (prolonged PT/PTT, low fibrinogen, elevated D-dimer) + schistocytes ได้ แต่ DIC มักเกิดจาก sepsis/trauma/malignancy มี multi-organ failure ไม่มี preceding diarrhea pattern แบบ HUS\n\n❌ E. Evans syndrome ไม่ถูกต้อง Evans syndrome = AIHA + ITP (autoimmune) Coombs test จะ positive ต่างจาก HUS ที่ Coombs negative";

reasons['NL2-2023-Q159'] = "เด็กมี fever แล้ว pallor Urinalysis: numerous RBCs PBS: Heinz body-like cells ถาม diagnosis\n\nFever (infection) → acute hemolysis (pallor) + hematuria (RBCs in urine = hemoglobinuria/hematuria) + PBS: Heinz bodies → G6PD deficiency\n\nG6PD deficiency เป็น X-linked recessive enzyme deficiency ที่ทำให้ RBCs ไม่สามารถ protect against oxidative stress ได้ เมื่อมี oxidative trigger (infection, drugs เช่น sulfa/primaquine/dapsone, fava beans) จะเกิด oxidation ของ hemoglobin → denatured hemoglobin precipitate เป็น Heinz bodies ที่เห็นด้วย supravital stain (crystal violet/methylene blue) RBCs ที่มี Heinz bodies จะถูก spleen กัดกินบางส่วนเป็น bite cells\n\n✅ B. G6PD deficiency ถูกต้อง Infection trigger + acute hemolysis + Heinz bodies เป็น classic presentation\n\n❌ A. Thalassemia disease ไม่ถูกต้อง Thalassemia มี chronic hemolysis + microcytic anemia + target cells ไม่ใช่ acute hemolysis กับ Heinz bodies\n\n❌ C. AIHA ไม่ถูกต้อง AIHA มี spherocytes + positive Coombs test ไม่มี Heinz bodies\n\n❌ D. DIC ไม่ถูกต้อง DIC มี schistocytes + coagulopathy ไม่มี Heinz bodies\n\n❌ E. PNH ไม่ถูกต้อง PNH มี complement-mediated hemolysis ไม่มี Heinz bodies วินิจฉัยด้วย flow cytometry";

reasons['NL2-2023-Q160'] = "เด็กชาย 3 ขวบ สุขภาพดี มาด้วย pallor + dark urine วันนี้ fever + sore throat 3 วัน ไม่มี family history of anemia BT 38.5 PR 102 BP 90/60 ตรวจพบ moderate pallor mild jaundice hepatomegaly spleen just palpable ถาม investigation\n\nAcute hemolysis (pallor + dark urine + jaundice) triggered by infection (fever + sore throat) ในเด็กที่ไม่มี family history of anemia → need to determine cause of hemolysis\n\nDifferential diagnosis: G6PD deficiency (X-linked, acute hemolysis จาก infection trigger, no family history ได้เพราะ de novo mutation หรือ carrier mother), AIHA, hereditary spherocytosis\n\nSupravital stain (เช่น brilliant cresyl blue หรือ crystal violet) เป็น investigation ที่เหมาะสมที่สุดเพราะสามารถ detect Heinz bodies (denatured hemoglobin จาก G6PD deficiency) + reticulocytes (compensatory response) ช่วย differentiate G6PD deficiency จาก other causes\n\n✅ B. Supravital stain ถูกต้อง ช่วย detect Heinz bodies (G6PD) + Hb H inclusions (Hb H disease) + reticulocytes ในเด็กที่มี acute hemolysis จาก infection trigger\n\n❌ A. Urinalysis ไม่ถูกต้อง UA อาจเห็น hemoglobinuria/urobilinogen สูง แต่ไม่ช่วย differentiate สาเหตุของ hemolysis\n\n❌ C. OF test ไม่ถูกต้อง Osmotic fragility test ใช้ diagnose hereditary spherocytosis ซึ่ง less likely เมื่อไม่มี family history\n\n❌ D. Direct antiglobulin test (DAT) ไม่ถูกต้อง DAT ใช้ diagnose AIHA ซึ่ง uncommon ในเด็ก 3 ขวบ เมื่อมี infection trigger → G6PD more likely\n\n❌ E. Bone marrow aspiration ไม่ถูกต้อง BM aspiration เป็น invasive procedure ที่ไม่จำเป็นเมื่อ peripheral blood tests สามารถ diagnose ได้ สงวนไว้เมื่อสงสัย leukemia/aplastic anemia";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');
  mongoose.disconnect();
}).catch(err => console.error(err.message));
