const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q121'] = "ทารก 4 เดือน noisy breathing 1 เดือน อาการดีขึ้นเมื่อนอนหงาย (supine) แย่ลงเมื่อนอนคว่ำ (prone) ตรวจพบ weight 6 kg BT 36.5 PR 120 RR 35 suprasternal retraction inspiratory stridor อื่นๆ ปกติ\n\nInspiratory stridor ในทารก 4 เดือน ที่ดำเนินมา 1 เดือน โดยไม่มี fever และเจริญเติบโตปกติ สาเหตุที่พบบ่อยที่สุดของ chronic inspiratory stridor ในทารกคือ laryngomalacia ซึ่งเป็น most common congenital laryngeal anomaly (60-70% ของ all congenital laryngeal disorders)\n\nLaryngomalacia เกิดจาก immature/floppy supraglottic structures (epiglottis, aryepiglottic folds, arytenoid cartilages) ที่ collapse เข้าหา airway ขณะหายใจเข้า ทำให้เกิด inspiratory stridor มักเริ่มสังเกตได้ที่อายุ 2-4 สัปดาห์ แย่ลงที่อายุ 4-8 เดือน แล้วค่อยๆ ดีขึ้นเองภายใน 12-18 เดือนเมื่อ cartilage แข็งแรงขึ้น อาการมักแย่ลงขณะ feeding, crying, agitation และสัมพันธ์กับ position\n\nการวินิจฉัยด้วย flexible nasopharyngolaryngoscopy จะเห็น omega-shaped epiglottis + prolapse ของ supraglottic structures ขณะหายใจเข้า ส่วนใหญ่ไม่ต้องรักษา (self-limited) ยกเว้นมี severe symptoms (failure to thrive, cyanosis, obstructive sleep apnea) จึงค่อยทำ supraglottoplasty\n\n✅ C. Laryngomalacia ถูกต้อง เป็น most common cause ของ chronic inspiratory stridor ในทารก onset ที่อายุน้อย ดำเนินมานาน ไม่มี fever เจริญเติบโตปกติ\n\n❌ A. Viral croup ไม่ถูกต้อง Croup (laryngotracheobronchitis) เป็น acute condition มาด้วย barking cough, stridor, hoarseness ร่วมกับ URI prodrome (runny nose, fever) อาการเป็น acute onset (2-3 วัน) ไม่ใช่ chronic 1 เดือนแบบนี้\n\n❌ B. Vascular ring ไม่ถูกต้อง Vascular ring เกิดจาก anomalous aortic arch vessels ที่รัด trachea/esophagus ทำให้ biphasic stridor (ทั้ง inspiratory + expiratory) + dysphagia อาการมักคงที่ไม่เปลี่ยนตาม position อย่างชัดเจน วินิจฉัยด้วย CT angiography/MRI\n\n❌ D. Vocal cord paralysis ไม่ถูกต้อง เป็น 2nd most common cause ของ congenital stridor unilateral VCP มี weak/breathy cry + mild stridor, bilateral VCP มี severe stridor + normal cry แต่มักมี associated conditions (Arnold-Chiari malformation, birth trauma, cardiac surgery) ไม่สัมพันธ์กับ position แบบ laryngomalacia\n\n❌ E. Subglottic hemangioma ไม่ถูกต้อง พบน้อยกว่า laryngomalacia มาก มักมี biphasic stridor ที่แย่ลงเรื่อยๆ ตามการเติบโตของ hemangioma (enlarge ใน 6-12 เดือนแรก) มักมี cutaneous hemangioma ร่วมด้วย 50%";

reasons['NL2-2023-Q122'] = "เด็กชาย 7 ขวบ severe productive cough 3 วัน ประวัติ running nose 1 สัปดาห์ ตรวจพบ BT 37 (ไม่มีไข้) RR 24 normal nasal turbinate no postnasal drip pharynx/tonsil not injected no wheezing coarse crepitation both lungs\n\nProductive cough หลัง URI (runny nose 1 week) + no fever + coarse crepitation both lungs + no wheezing → acute bronchitis\n\nAcute bronchitis เป็น inflammation ของ tracheobronchial tree มักเป็น sequel ของ viral URI เชื้อ virus ที่ทำให้เกิด URI ลุกลามลงมาที่ bronchi ทำให้ bronchial mucosa อักเสบ สร้าง mucus มากขึ้น เกิด productive cough และ coarse crepitation (จาก mucus ใน large airways) ไม่มี wheezing (ไม่ใช่ asthma) ไม่มี consolidation (ไม่ใช่ pneumonia) ไม่มี fever (viral bronchitis มักไม่มีไข้สูง)\n\n✅ D. Acute bronchitis ถูกต้อง Post-URI productive cough + bilateral coarse crepitation + no fever + no wheezing เข้ากับ acute bronchitis มากที่สุด\n\n❌ A. Asthma ไม่ถูกต้อง Asthma มี wheezing เป็น hallmark ผู้ป่วยรายนี้ไม่มี wheezing ไม่มีประวัติ recurrent episodes\n\n❌ B. Pneumonia ไม่ถูกต้อง Pneumonia มักมี fever + focal crepitation/consolidation + tachypnea ผู้ป่วยไม่มี fever ไม่มี focal findings\n\n❌ C. Acute sinusitis ไม่ถูกต้อง Sinusitis มาด้วย nasal congestion, purulent nasal discharge, facial pain/pressure, postnasal drip ผู้ป่วยมี normal nasal turbinate no postnasal drip ไม่เข้ากับ sinusitis\n\n❌ E. Acute bronchiolitis ไม่ถูกต้อง Bronchiolitis พบในเด็กอายุน้อยกว่า 2 ปี จาก RSV มี wheezing + fine crepitation เด็ก 7 ขวบไม่อยู่ในกลุ่มอายุของ bronchiolitis";

reasons['NL2-2023-Q123'] = "เด็กชาย 5 ขวบ watery rhinorrhea ตรวจพบ bilateral inferior turbinate swelling ถาม proper management\n\nWatery rhinorrhea + bilateral turbinate swelling ในเด็ก → allergic rhinitis\n\nAllergic rhinitis เกิดจาก IgE-mediated type I hypersensitivity ต่อ aeroallergens (dust mites, pollen, pet dander, mold) ทำให้ nasal mucosa อักเสบ เกิด nasal congestion, rhinorrhea (watery), sneezing, nasal itching Bilateral inferior turbinate swelling (boggy, pale turbinates) เป็น classic finding\n\nIntranasal corticosteroid (เช่น fluticasone, mometasone, budesonide) เป็น most effective treatment สำหรับ allergic rhinitis ทุกระดับความรุนแรง ออกฤทธิ์ลด inflammation ที่ nasal mucosa โดยตรง มีประสิทธิภาพต่อทุกอาการ (congestion, rhinorrhea, sneezing, itching)\n\n✅ B. Intranasal corticosteroid ถูกต้อง เป็น first-line treatment สำหรับ allergic rhinitis ตาม ARIA guidelines\n\n❌ A. Inhaled corticosteroid ไม่ถูกต้อง Inhaled (ผ่าน MDI/DPI) ใช้สำหรับ lower airway (asthma) ไม่ใช่ nasal symptoms ต้องใช้ intranasal spray\n\n❌ C. Oral prednisolone ไม่ถูกต้อง Systemic steroid สงวนไว้สำหรับ severe allergic rhinitis ที่ไม่ตอบสนองต่อ topical treatment ไม่ใช่ first-line เพราะ side effects\n\n❌ D. Salbutamol nebulizer ไม่ถูกต้อง Salbutamol ใช้สำหรับ bronchospasm/asthma ไม่มี effect ต่อ nasal symptoms\n\n❌ E. Oral antihistamine ไม่ถูกต้อง Antihistamine ช่วยลด sneezing, rhinorrhea, itching ได้ แต่ไม่ effective สำหรับ nasal congestion/turbinate swelling เท่า intranasal corticosteroid ซึ่ง effective กว่าสำหรับทุกอาการ";

reasons['NL2-2023-Q124'] = "เด็กชาย 15 เดือน noisy breathing วันนี้ ประวัติ runny nose cough low-grade fever 2 วัน ตรวจพบ BT 38 RR 50 PR 100 SpO2 95% suprasternal notch retraction brassy cough inspiratory stridor rhonchi both lungs\n\nURI prodrome (runny nose, cough, low-grade fever 2 วัน) → barking/brassy cough + inspiratory stridor + suprasternal retraction = croup (acute laryngotracheobronchitis)\n\nCroup เป็น viral infection ที่พบบ่อยที่สุดในเด็กอายุ 6 เดือน - 6 ปี (peak 1-2 ปี) สาเหตุหลักคือ parainfluenza virus (type 1 พบบ่อยที่สุด) ทำให้ subglottic area อักเสบบวม ทำให้ airway แคบลง เกิด inspiratory stridor + barking cough X-ray neck AP จะเห็น steeple sign (subglottic narrowing)\n\nผู้ป่วยรายนี้มี moderate croup (stridor at rest + retractions + SpO2 95%) ต้องการ immediate treatment\n\nNebulized epinephrine เป็น treatment สำหรับ moderate-severe croup ออกฤทธิ์ vasoconstriction ที่ subglottic mucosa ลด edema ได้รวดเร็วภายใน 10-30 นาที ร่วมกับ systemic dexamethasone (oral/IM) เป็น standard treatment\n\n✅ D. Nebulized epinephrine ถูกต้อง เป็น appropriate treatment สำหรับ moderate-severe croup ที่มี stridor at rest + retractions ให้ผลเร็วภายในนาที\n\n❌ A. Ceftriaxone ไม่ถูกต้อง Croup เป็น viral infection ไม่ต้องใช้ antibiotics\n\n❌ B. Oral prednisone ไม่ถูกต้อง Systemic steroid (dexamethasone preferred > prednisone) เป็น standard treatment แต่ออกฤทธิ์ช้ากว่า (6-12 ชม.) สำหรับ moderate-severe croup ที่มี stridor at rest ต้อง nebulized epinephrine ก่อนเพื่อ rapid relief\n\n❌ C. Nebulized salbutamol ไม่ถูกต้อง Salbutamol ออกฤทธิ์ที่ lower airway (bronchodilation) ไม่ช่วย subglottic edema ซึ่งเป็น upper airway obstruction\n\n❌ E. Nebulized hypertonic saline ไม่ถูกต้อง Hypertonic saline ใช้ใน bronchiolitis ไม่ใช่ croup ไม่มี evidence สนับสนุนการใช้ใน croup";

reasons['NL2-2023-Q125'] = "เด็กที่มี URI ได้ amoxicillin 4 วัน ไม่ดีขึ้น CXR พบ LUL interstitial infiltration + mild pharyngeal injection ถาม most appropriate antibiotic\n\nURI + interstitial infiltration + failed amoxicillin → atypical pneumonia\n\nInterstitial infiltration pattern (ไม่ใช่ consolidation/lobar) บ่งบอกว่าเป็น atypical pneumonia ซึ่งสาเหตุที่พบบ่อยที่สุดในเด็กวัยเรียน (5 ปีขึ้นไป) คือ Mycoplasma pneumoniae ตามด้วย Chlamydophila pneumoniae อาการมักเป็น subacute: dry/productive cough ค่อยเป็นค่อยไป ไข้ต่ำ pharyngitis อาจมี extrapulmonary manifestations (rash, myalgia)\n\nAmoxicillin ไม่ cover atypical organisms เพราะ Mycoplasma ไม่มี cell wall (amoxicillin target = cell wall synthesis) จึงไม่ดีขึ้นหลัง 4 วัน\n\nAzithromycin เป็น drug of choice สำหรับ atypical pneumonia ในเด็ก เป็น macrolide ที่ inhibit bacterial protein synthesis ที่ 50S ribosome subunit effective ต่อ Mycoplasma, Chlamydia ขนาด 10 mg/kg วันแรก ตามด้วย 5 mg/kg วันที่ 2-5\n\n✅ C. Azithromycin ถูกต้อง เป็น drug of choice สำหรับ atypical pneumonia (Mycoplasma/Chlamydia) ในเด็ก\n\n❌ A. Augmentin ไม่ถูกต้อง Amoxicillin-clavulanate ครอบคลุม beta-lactamase producing bacteria แต่ยังไม่ cover atypical organisms ที่ไม่มี cell wall\n\n❌ B. Ceftriaxone ไม่ถูกต้อง 3rd gen cephalosporin ไม่ cover Mycoplasma/Chlamydia\n\n❌ D. Clindamycin ไม่ถูกต้อง ครอบคลุม gram-positive + anaerobes ไม่ใช่ atypical organisms\n\n❌ E. Doxycycline ไม่ถูกต้อง Doxycycline effective ต่อ Mycoplasma แต่ contraindicated ในเด็กอายุน้อยกว่า 8 ปี เพราะ staining ของ developing teeth (ยกเว้น short course สำหรับ Rocky Mountain spotted fever)";

reasons['NL2-2023-Q126'] = "เด็กไทยชาย 3 ขวบ สุขภาพดี abdominal distension 3 วัน ถ่าย meconium ภายใน 24 ชม.หลังคลอด feeding ดี ถ่ายอุจจาระ 1-2 ครั้ง/สัปดาห์ ตรวจพบ vital signs stable irritability abdominal distension impacted stool\n\nเด็ก 3 ขวบ ถ่าย meconium ปกติ (ภายใน 24 ชม.) กินนมได้ดี แต่ถ่าย 1-2 ครั้ง/สัปดาห์ (infrequent) ร่วมกับ abdominal distension + impacted stool → functional constipation with fecal impaction\n\nอย่างไรก็ตาม ในเด็กที่มี abdominal distension + infrequent stooling ต้อง rule out Hirschsprung disease (HD) ก่อน แม้ว่าจะถ่าย meconium ปกติ (90% ของ HD ถ่าย meconium ช้า แต่ 10% อาจถ่ายปกติ โดยเฉพาะ short-segment HD)\n\nRectal examination เป็น most appropriate initial step เพราะ 1) ช่วยประเมิน anal tone, rectal ampulla (empty = สงสัย HD, full of stool = functional constipation) 2) ช่วย disimpact stool (therapeutic) 3) blast sign ใน HD (explosive stool + gas หลังถอดนิ้ว)\n\n✅ A. Rectal examination ถูกต้อง เป็น essential initial step ในเด็กที่มี chronic constipation เพื่อ assess + differentiate functional constipation จาก Hirschsprung disease\n\n❌ B. Stool examination ไม่ถูกต้อง ไม่ช่วย diagnose สาเหตุของ constipation\n\n❌ C. X-ray plain film acute abdomen series ไม่ถูกต้อง อาจช่วยดู fecal loading แต่ไม่จำเป็นเป็น initial step เมื่อ clinical diagnosis ชัดอยู่แล้ว rectal exam ให้ข้อมูลมากกว่า\n\n❌ D. Ultrasound abdomen ไม่ถูกต้อง ไม่ใช่ investigation หลักสำหรับ constipation rectal exam เป็น initial step ที่เหมาะสมกว่า\n\n❌ E. Oral simethicone ไม่ถูกต้อง Simethicone ใช้สำหรับ gas/bloating ไม่ช่วยเรื่อง fecal impaction ต้อง disimpact ก่อน";

reasons['NL2-2023-Q127'] = "เด็กชาย 2 ขวบ hard defecation 4 เดือน ถ่ายไม่ค่อยบ่อย ร้องเวลาถ่าย แม่จำ meconium history ไม่ได้ ตรวจพบ ill-defined mass 3 cm ที่ LLQ anal fissure อื่นๆ ปกติ\n\nHard stool 4 เดือน + infrequent defecation + crying during defecation + palpable mass ที่ LLQ (fecal mass) + anal fissure (จาก hard stool) → fecal impaction\n\nFecal impaction เกิดจาก hard stool สะสมใน rectum และ sigmoid colon จนเป็นก้อน (fecal mass) ทำให้ rectum ขยาย (megarectum) สูญเสีย sensation ถ่ายไม่ค่อยออก เกิดเป็น vicious cycle: hard stool → painful defecation → withholding → more impaction → harder stool\n\nAnal fissure เป็น complication ที่พบบ่อยของ chronic constipation จาก hard stool ที่ traumatize anal mucosa ทำให้เจ็บขณะถ่ายมากขึ้น เด็กจึง withhold มากขึ้น\n\n✅ B. Fecal impact ถูกต้อง Chronic hard stool + palpable fecal mass + anal fissure เป็น classic presentation ของ fecal impaction\n\n❌ A. Physiologic dyschezia ไม่ถูกต้อง เป็นภาวะในทารกอายุน้อยกว่า 6 เดือนที่ร้องก่อนถ่าย stool ปกติ ไม่แข็ง เกิดจาก inability to coordinate relaxation of pelvic floor with abdominal straining ไม่ใช่เด็ก 2 ขวบที่มี hard stool + fecal mass\n\n❌ C. Hirschsprung's disease ไม่ถูกต้อง HD มักมา present ตั้งแต่ neonatal period ด้วย delayed meconium passage, abdominal distension, failure to thrive rectal exam จะพบ empty rectum + blast sign ผู้ป่วยรายนี้คลำ fecal mass ที่ LLQ ได้ แสดงว่า stool ผ่าน colon มาถึง sigmoid ได้ ไม่เข้ากับ HD ที่ distal colon aganglionic\n\n❌ D. Functional constipation ไม่ถูกต้อง Functional constipation กับ fecal impaction มี overlap แต่เมื่อมี palpable fecal mass แล้ว ถือว่าเป็น fecal impaction ซึ่งเป็น complication ของ functional constipation ที่ต้อง specific management (disimpaction ก่อน แล้วจึง maintenance)\n\n❌ E. Anal stenosis ไม่ถูกต้อง Anal stenosis ทำให้ stool เป็น ribbon-like ตรวจพบ anal opening ที่แคบผิดปกติ ผู้ป่วยรายนี้มี anal fissure ซึ่งเป็นผลจาก hard stool ไม่ใช่ stenosis";

reasons['NL2-2023-Q128'] = "เด็กที่มี RUQ pain, jaundice, hepatomegaly เพื่อนร่วมชั้นมีอาการเดียวกัน ถาม proper investigation\n\nRUQ pain + jaundice + hepatomegaly + cluster outbreak ในเพื่อนร่วมชั้น → acute viral hepatitis A\n\nHepatitis A virus (HAV) เป็น RNA picornavirus ติดต่อทาง fecal-oral route พบบ่อยในเด็กวัยเรียน มี incubation period 15-50 วัน (เฉลี่ย 28 วัน) ระบาดเป็นกลุ่มในโรงเรียน/สถานรับเลี้ยงเด็กจากอาหาร/น้ำที่ปนเปื้อน\n\nการวินิจฉัย acute hepatitis A ต้องใช้ IgM anti-HAV ซึ่งเป็น marker ของ acute infection ขึ้นพร้อมกับอาการ คงอยู่ 3-6 เดือน ส่วน IgG anti-HAV เป็น marker ของ past infection/immunity คงอยู่ตลอดชีวิต\n\n✅ E. Hepatitis A IgM ถูกต้อง เป็น diagnostic marker ที่ specific สำหรับ acute hepatitis A infection\n\n❌ A. Stool culture for parasites ไม่ถูกต้อง Parasitic infection ไม่ระบาดเป็น cluster ในเด็กนักเรียนแบบนี้\n\n❌ B. Entamoeba Histolytica antibody titer ไม่ถูกต้อง Amoebiasis ไม่เข้ากับ acute hepatitis + cluster outbreak\n\n❌ C. Hepatitis A IgG ไม่ถูกต้อง IgG เป็น marker ของ past infection/immunity ไม่สามารถวินิจฉัย acute infection ได้ คนที่เคยติดเชื้อหรือฉีดวัคซีนจะ IgG positive ตลอดชีวิต\n\n❌ D. Anti-HBs ไม่ถูกต้อง เป็น marker ของ immunity ต่อ Hepatitis B ไม่เกี่ยวกับ Hepatitis A Hepatitis B ติดต่อทาง blood/body fluid ไม่ระบาดเป็น cluster ในเด็กแบบนี้";

reasons['NL2-2023-Q129'] = "เด็ก 4 ขวบ GTC seizure 5 นาที มาถึง ER 30 นาทีหลัง onset ที่ ER เกิด seizure อีกครั้ง ถาม initial management\n\nRecurrent seizure ใน ER → ต้องให้ benzodiazepine เพื่อหยุด seizure ทันที\n\nตาม status epilepticus management guidelines ลำดับการให้ยาคือ 1st line: benzodiazepine (lorazepam IV หรือ diazepam IV/rectal หรือ midazolam IM/buccal/intranasal) 2nd line: phenytoin/fosphenytoin IV หรือ levetiracetam IV 3rd line: phenobarbital IV\n\nเมื่อเด็กชักอีกครั้งใน ER ถ้ายังไม่มี IV access ให้ diazepam rectal (suppository) เป็น fastest route ขนาด 0.5 mg/kg PR onset ภายใน 2-5 นาที ถ้ามี IV access ให้ IV diazepam (0.2-0.3 mg/kg) หรือ IV lorazepam (0.1 mg/kg)\n\nโจทย์ถาม initial management เมื่อเด็กชักใน ER — ในสถานการณ์จริง IV access อาจยังไม่ได้ ดังนั้น rectal diazepam เป็น fastest route ที่ทำได้ทันที\n\n✅ A. Diazepam suppository ถูกต้อง เป็น initial management ที่รวดเร็วที่สุดเมื่อ IV access ยังไม่ได้\n\n❌ B. IV phenytoin ไม่ถูกต้อง Phenytoin เป็น 2nd line agent ให้หลังจาก benzodiazepine ไม่สามารถหยุด seizure ได้\n\n❌ C. IV phenobarbital ไม่ถูกต้อง เป็น 3rd line agent\n\n❌ D. IM phenobarbital ไม่ถูกต้อง IM absorption ช้าและไม่สม่ำเสมอ ไม่เหมาะสำหรับ acute seizure management\n\n❌ E. IV lorazepam ไม่ถูกต้อง Lorazepam IV เป็น excellent choice สำหรับ seizure (preferred over diazepam IV ใน USA) แต่ต้องมี IV access ก่อน ถ้าถามถึง initial management ที่ไม่ต้องรอ IV rectal diazepam จะเร็วกว่า";

reasons['NL2-2023-Q130'] = "เด็ก 13 ขวบ GTC 30 นาที ปวดศีรษะ + บวม 3 วัน ตรวจพบ BT 37 RR 30 PR 110 BP 160/100 drowsy fine crepitation both lungs non-pitting edema both legs puffy eyelids BUN 25 Cr 1.5 Na 130 K ?\n\nGTC seizure 30 นาที + hypertensive emergency (BP 160/100) + edema (puffy eyelids, legs) + pulmonary edema (crepitation) + renal impairment (BUN 25, Cr 1.5) → acute glomerulonephritis (AGN) with hypertensive encephalopathy\n\nAGN (most likely post-streptococcal GN ในเด็ก 13 ปี) ทำให้ sodium and water retention → volume overload → hypertension → pulmonary edema → hypertensive encephalopathy (seizure, drowsiness)\n\nSeizure ในกรณีนี้เกิดจาก hypertensive encephalopathy (BP 160/100 ในเด็ก = severe hypertension) ไม่ใช่จาก primary CNS pathology ดังนั้น management ที่สำคัญที่สุดคือ lower blood pressure ลงอย่างรวดเร็วเพื่อหยุด seizure + ป้องกัน further cerebral damage\n\nNicardipine IV เป็น drug of choice สำหรับ hypertensive emergency ในเด็ก เป็น dihydropyridine calcium channel blocker ที่ให้ IV continuous infusion ปรับ dose ได้ง่าย onset รวดเร็ว (1-5 นาที) predictable ลด BP ได้ controlled\n\n✅ B. Nicardipine IV ถูกต้อง เป็น first-line antihypertensive สำหรับ hypertensive emergency ในเด็ก ที่ทำให้ seizure จาก hypertensive encephalopathy\n\n❌ A. 3% NaCl IV ไม่ถูกต้อง 3% NaCl ใช้สำหรับ symptomatic severe hyponatremia (Na<120 with seizure) ผู้ป่วยรายนี้ Na 130 (mild hyponatremia) ไม่ใช่สาเหตุของ seizure สาเหตุคือ hypertensive encephalopathy\n\n❌ C. Phenytoin IV ไม่ถูกต้อง Phenytoin เป็น antiepileptic ที่ใช้หยุด seizure แต่ seizure ในกรณีนี้เกิดจาก hypertension การรักษาที่ root cause คือลด BP seizure จะหยุดเมื่อ BP ลดลง\n\n❌ D. 7.5% NaHCO3 IV ไม่ถูกต้อง NaHCO3 ใช้สำหรับ severe metabolic acidosis หรือ hyperkalemia ไม่ได้ระบุว่ามี acidosis หรือ K สูงที่ต้อง urgent treatment\n\n❌ E. 10% Calcium gluconate IV ไม่ถูกต้อง Calcium gluconate ใช้เป็น cardioprotective agent ใน severe hyperkalemia (K>6.5 with EKG changes) โจทย์ไม่ได้ระบุ hyperkalemia";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');
  mongoose.disconnect();
}).catch(err => console.error(err.message));
