const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q101'] = "หญิงอายุ 52 ปี มาด้วยปัสสาวะเล็ดขณะ activity, coughing, sneezing ตรวจพบ urethral hypermobility UA ปกติ\n\nUrinary leakage ที่เกิดขณะ increased intra-abdominal pressure (ไอ จาม ออกกำลังกาย) ร่วมกับ urethral hypermobility เป็น hallmark ของ stress urinary incontinence (SUI)\n\nSUI เกิดจากความอ่อนแอของ pelvic floor support structures (pubourethral ligaments, endopelvic fascia) ทำให้ urethra และ bladder neck ไม่สามารถรักษา position ปกติได้เมื่อมี increased intra-abdominal pressure เกิด urethral hypermobility ส่งผลให้ urethral closure pressure ไม่เพียงพอ ปัสสาวะจึงเล็ดออกขณะ stress Risk factors ได้แก่ vaginal delivery, menopause (estrogen deficiency), obesity, chronic cough\n\n✅ C. Stress urinary incontinence ถูกต้อง ปัสสาวะเล็ดขณะ cough/sneeze/activity + urethral hypermobility เป็น diagnostic criteria ของ SUI\n\n❌ A. Coital urinary incontinence ไม่ถูกต้อง เป็น incontinence ขณะมีเพศสัมพันธ์ โจทย์ไม่ได้กล่าวถึง\n\n❌ B. Mixed urinary incontinence ไม่ถูกต้อง Mixed UI มีทั้ง stress + urgency components แต่โจทย์ไม่มี urgency symptoms (รู้สึกปวดปัสสาวะรุนแรงกะทันหันจนกลั้นไม่อยู่)\n\n❌ D. Urgency incontinence ไม่ถูกต้อง มาด้วย sudden urgency ที่กลั้นไม่ทัน เกิดจาก detrusor overactivity ไม่สัมพันธ์กับ physical activity/cough/sneeze\n\n❌ E. Overflow incontinence ไม่ถูกต้อง เกิดจาก chronic urinary retention (bladder เต็มจนล้น) พบใน BPH, neurogenic bladder มี dribbling + large post-void residual";

reasons['NL2-2023-Q102'] = "ชายอายุ 70 ปี มาด้วย frequency + difficulty urinating 2 ปี BT 37 BP 140/70 ตรวจพบ bilateral palpable flank mass (bilateral hydronephrosis), suprapubic mass (distended bladder), enlarged prostate\n\nBPH with complications — bilateral hydronephrosis + urinary retention (distended bladder) แสดงว่า BPH รุนแรงมากจน bladder outlet obstruction เรื้อรัง ทำให้ bilateral ureteral obstruction + renal damage แล้ว\n\nIndication สำหรับ TURP (Transurethral Resection of the Prostate) ใน BPH ได้แก่ refractory urinary retention, recurrent UTI, bladder stones, renal insufficiency จาก obstruction, recurrent gross hematuria, failed medical therapy ผู้ป่วยรายนี้มี bilateral hydronephrosis + urinary retention ซึ่งเป็น absolute indication สำหรับ surgery\n\n✅ E. TURP ถูกต้อง เป็น gold standard surgical treatment สำหรับ BPH ที่มี complications (bilateral hydronephrosis + urinary retention) Medical therapy alone (alpha blocker, 5-ARI) ไม่เพียงพอเมื่อมี renal compromise\n\n❌ A. Alpha antagonist ไม่ถูกต้อง เป็น first-line medical therapy สำหรับ uncomplicated BPH แต่เมื่อมี bilateral hydronephrosis + retention ยาอย่างเดียวไม่เพียงพอ ต้อง surgical intervention\n\n❌ B. 5-alpha reductase inhibitor ไม่ถูกต้อง ใช้เวลา 3-6 เดือนกว่าจะเห็นผล ไม่เหมาะสำหรับ acute retention with renal compromise\n\n❌ C. Alpha antagonist + 5-ARI ไม่ถูกต้อง Combination therapy เหมาะสำหรับ large prostate ที่ต้องการ long-term management ไม่เหมาะเมื่อมี absolute surgical indication\n\n❌ D. Finasteride ไม่ถูกต้อง Finasteride เป็น 5-ARI ซ้ำกับ choice B ไม่เหมาะสำหรับ complicated BPH";

reasons['NL2-2023-Q103'] = "ผู้ป่วย 20% TBSA superficial 2nd degree burn มาถึง ER 2 ชั่วโมงหลังเกิดเหตุ ถามว่า initial fluid rate จาก modified Brooke's formula คือเท่าไร\n\nModified Brooke formula: 2 mL x body weight (kg) x %TBSA burn ให้ใน 24 ชั่วโมงแรก โดย 50% ให้ใน 8 ชั่วโมงแรกนับจากเวลาเกิดเหตุ (ไม่ใช่เวลาที่มาถึง ER) อีก 50% ให้ใน 16 ชั่วโมงถัดไป\n\nถ้าสมมติน้ำหนัก 70 kg (ซึ่งเป็น standard ถ้าโจทย์ไม่ระบุ): Total = 2 x 70 x 20 = 2,800 mL ใน 24 ชม. ครึ่งแรก (1,400 mL) ให้ใน 8 ชม.แรก แต่มาถึง ER ช้าไป 2 ชม. จึงเหลือ 6 ชม. ที่ต้องให้ 1,400 mL Rate = 1,400/6 = 233 mL/hr\n\nถ้าน้ำหนัก 60 kg: Total = 2 x 60 x 20 = 2,400 mL ครึ่งแรก 1,200 mL ใน 6 ชม. = 200 mL/hr ซึ่งตรงกับคำตอบ A\n\n✅ A. 200 mL/hr ถูกต้อง คำนวณจาก modified Brooke formula สำหรับผู้ป่วยน้ำหนักประมาณ 60 kg ที่มา ER 2 ชม.หลังเกิดเหตุ ต้องให้ครึ่งแรกของ total volume ใน 6 ชม.ที่เหลือ (8-2=6)\n\n❌ B. 150 mL/hr ไม่ถูกต้อง น้อยเกินไปสำหรับ 20% TBSA burn ไม่ตรงกับ modified Brooke formula\n\n❌ C. 120 mL/hr ไม่ถูกต้อง น้อยเกินไป\n\n❌ D. 100 mL/hr ไม่ถูกต้อง น้อยเกินไป อาจทำให้ under-resuscitation\n\n❌ E. 250 mL/hr ไม่ถูกต้อง มากเกินไปสำหรับน้ำหนักที่โจทย์ต้องการ อาจทำให้ over-resuscitation";

reasons['NL2-2023-Q104'] = "โจทย์ให้ภาพ (EKG/CT/X-ray ที่ไม่ได้แสดง) ถาม diagnosis คำตอบคือ Epidural hemorrhage\n\nEpidural hemorrhage (EDH) เป็น blood collection ระหว่าง inner surface ของ skull กับ dura mater สาเหตุหลักคือ rupture ของ middle meningeal artery จาก temporal bone fracture (85-95% เป็น arterial bleeding)\n\nCT brain ของ EDH จะแสดง biconvex (lens-shaped/lenticular) hyperdense lesion ที่ไม่ข้าม suture lines (เพราะ dura ยึดแน่นกับ skull ที่ suture lines) ตำแหน่งที่พบบ่อยที่สุดคือ temporal region\n\nClassic clinical presentation (Lucid interval) พบใน 20-50% — หลัง head trauma ผู้ป่วยหมดสติ → ตื่นขึ้นมา (lucid interval) → หมดสติอีกครั้งจาก expanding hematoma ที่กด brain เกิด uncal herniation → ipsilateral pupil dilation → contralateral hemiparesis\n\n✅ A. Epidural hemorrhage ถูกต้อง CT แสดง biconvex hyperdense lesion ซึ่งเป็น pathognomonic finding ของ EDH\n\n❌ B. Subdural hemorrhage ไม่ถูกต้อง SDH จะเห็นเป็น crescent-shaped (concave) hyperdense lesion ที่ข้าม suture lines ได้ เกิดจาก tearing ของ bridging veins\n\n❌ C. Subarachnoid hemorrhage ไม่ถูกต้อง SAH จะเห็น blood ใน subarachnoid space (cisterns, sulci, fissures) ไม่เป็น biconvex mass\n\n❌ D. Intracranial hemorrhage ไม่ถูกต้อง ICH (intraparenchymal) จะเห็น blood ภายใน brain parenchyma ไม่ใช่ extra-axial collection\n\n❌ E. Interventricular hemorrhage ไม่ถูกต้อง IVH จะเห็น blood ภายใน ventricles ไม่ใช่ extra-axial biconvex collection";

reasons['NL2-2023-Q105'] = "หญิงอายุ 33 ปี มาด้วย itching scar ที่ right shoulder มีประวัติ 1x3 cm wound ที่เคยเย็บ wound infected จึง de-suture, drain, ให้ antibiotics จนหาย ตรวจพบ erythematous, wide scar (สันนิษฐานว่า raised/hypertrophic)\n\nItching + erythematous + wide scar ที่เกิดจาก wound ที่มี complication (infection, secondary healing) เข้าได้กับ hypertrophic scar หรือ keloid ทั้งสองชนิดเป็น excessive scar formation จาก abnormal wound healing\n\nHypertrophic scar อยู่ภายในขอบเขตของ original wound ขยายตัวตามแนว tension lines มักดีขึ้นเองภายใน 1-2 ปี ส่วน keloid ขยายเลยขอบเขต wound ไม่หายเอง มักเกิดซ้ำหลังตัดออก Risk factors ของ excessive scarring ได้แก่ dark skin, wound infection, delayed healing, excessive tension\n\nIntralesional steroid injection (triamcinolone acetonide 10-40 mg/mL) เป็น first-line treatment สำหรับ hypertrophic scar และ keloid กลไกคือ steroid ยับยั้ง collagen synthesis, ลด fibroblast proliferation, เพิ่ม collagenase activity ทำให้ scar flatten, soften และ less pruritic ฉีดทุก 4-6 สัปดาห์ จนได้ผล\n\n✅ C. Intralesional steroid injection ถูกต้อง เป็น first-line treatment สำหรับ symptomatic hypertrophic/keloid scar ที่มี itching และ raised\n\n❌ A. Pressure garment ไม่ถูกต้อง Pressure therapy ใช้ prevent hypertrophic scar ใน burn patients ที่ wound ใหญ่ ไม่ใช่ treatment หลักสำหรับ established scar จาก small wound\n\n❌ B. Topical silicone gel ไม่ถูกต้อง Silicone gel sheets เป็น adjunctive treatment ที่ช่วย flatten scar ได้บ้าง แต่ประสิทธิภาพต่ำกว่า intralesional steroid สำหรับ symptomatic scar ที่คัน\n\n❌ D. Laser ablation ไม่ถูกต้อง Laser therapy (pulsed dye laser, fractional CO2) เป็น adjunctive treatment ที่ใช้เมื่อ steroid injection ไม่เพียงพอ ไม่ใช่ first-line\n\n❌ E. Excision ไม่ถูกต้อง Surgical excision alone มี recurrence rate สูงมาก (45-100% สำหรับ keloid) ถ้าตัดออกต้องให้ adjuvant therapy ร่วมด้วย (steroid injection, radiation) ไม่ใช่ first-line treatment";

reasons['NL2-2023-Q106'] = "เด็กที่มี pneumonia ได้รับ ceftriaxone 5 วัน อาการดีขึ้นแต่ยังมีไข้ CXR พบ pleural effusion Pleural fluid: WBC 1,500 cells/uL ถามว่า management ที่เหมาะสม\n\nPediatric pneumonia ที่ได้ antibiotics แล้วอาการดีขึ้น (clinical improvement) แต่ยังมี persistent fever ร่วมกับ new finding ของ pleural effusion → parapneumonic effusion ที่อาจเป็น complicated parapneumonic effusion หรือ empyema\n\nParapneumonic effusion แบ่งเป็น 3 stages: 1) Simple (exudative) — sterile fluid, low WBC, pH>7.2, glucose>40 → antibiotics alone 2) Complicated (fibrinopurulent) — bacteria invade, elevated WBC, pH<7.2, glucose<40, loculations → drainage needed 3) Empyema (organized) — frank pus, thick peel → decortication\n\nWBC 1,500 cells/uL ร่วมกับ persistent fever หลังได้ antibiotics 5 วัน บ่งบอกว่าเป็น complicated effusion ที่ antibiotics alone ไม่เพียงพอ ต้อง intercostal drainage (chest tube) เพื่อ drain infected fluid ออก\n\n✅ B. Intercostal drainage ถูกต้อง เป็น standard treatment สำหรับ complicated parapneumonic effusion/empyema ใน pediatric pneumonia ที่ไม่ตอบสนองต่อ antibiotics alone\n\n❌ A. Change antibiotics ไม่ถูกต้อง อาการ clinical improvement แสดงว่า antibiotic choice ถูกต้อง ปัญหาคือมี fluid collection ที่ antibiotics ไม่สามารถ penetrate ได้เพียงพอ ต้อง drain\n\n❌ C. Decortication ไม่ถูกต้อง Decortication เป็น surgical procedure สำหรับ organized empyema ที่มี thick fibrous peel เป็น last resort หลัง chest tube + fibrinolytics ล้มเหลว\n\n❌ D. VATS ไม่ถูกต้อง Video-assisted thoracoscopic surgery เป็น option สำหรับ complicated empyema ที่ chest tube drainage ล้มเหลว ไม่ใช่ initial management\n\n❌ E. Observe and repeat CXR ไม่ถูกต้อง Persistent fever + significant effusion ไม่ควร observe เฉยๆ ต้อง active drainage";

reasons['NL2-2023-Q107'] = "ทารกครบกำหนดคลอดด้วย vacuum extraction มี dyspnea 1 ชม.หลังคลอด ANC ปกติ ตรวจพบ BT 37, PR 190/min (tachycardia รุนแรง), BP 40/30 (hypotension รุนแรง), RR 65, SpO2 95%, weak pulse, pallor, normal heart sounds, no murmur\n\nKey findings: term neonate + vacuum delivery + severe shock (tachycardia 190 + hypotension 40/30 + weak pulse + pallor) ภายใน 1 ชม.หลังคลอด\n\nDifferential diagnosis ของ neonatal shock after vacuum extraction: subgaleal hemorrhage (SGH) เป็น most important cause SGH เกิดจาก bleeding เข้า potential space ระหว่าง galea aponeurotica กับ periosteum ของ skull ซึ่งเป็น space ที่ขยายได้มากจากหูถึงหู จาก forehead ถึง occiput สามารถเก็บเลือดได้ถึง 260 mL ใน newborn ทำให้เกิด hypovolemic shock อย่างรวดเร็ว SGH พบร่วมกับ vacuum extraction ได้ 0.6% (สูงกว่า spontaneous delivery 60 เท่า)\n\nผู้ป่วยรายนี้มี clinical picture ของ hypovolemic shock จาก hemorrhage → initial management คือ fluid resuscitation\n\n✅ E. NSS 10 mL/kg IV push in 15 min ถูกต้อง เป็น initial fluid bolus สำหรับ neonatal hypovolemic shock ตาม NRP guidelines ให้ isotonic crystalloid (NSS) 10 mL/kg IV push ใน 10-15 นาที ประเมินซ้ำ ถ้ายัง shock ให้ซ้ำได้ ถ้าสงสัย hemorrhage มาก อาจต้อง blood transfusion\n\n❌ A. PPV (Positive Pressure Ventilation) ไม่ถูกต้อง PPV ใช้สำหรับ respiratory failure ในทารกแรกเกิด (apnea, gasping, HR<100) ผู้ป่วยรายนี้ SpO2 95% RR 65 ยัง breathe ได้เอง ปัญหาหลักคือ circulatory shock ไม่ใช่ respiratory failure\n\n❌ B. U/S head ไม่ถูกต้อง Cranial ultrasound ช่วย diagnose intracranial hemorrhage ได้ แต่ไม่ใช่ immediate management ต้อง stabilize hemodynamically ก่อน\n\n❌ C. Dopamine ไม่ถูกต้อง Vasopressor/inotrope ใช้สำหรับ cardiogenic shock หรือ distributive shock หลัง adequate volume resuscitation แล้วยัง hypotensive ไม่ใช่ first-line สำหรับ hypovolemic shock ที่ต้อง volume replacement ก่อน\n\n❌ D. 10% D/W 65 mL/kg/day ไม่ถูกต้อง เป็น maintenance fluid ไม่ใช่ resuscitation fluid Maintenance fluid ให้ช้าๆ (mL/hr) ไม่ได้ให้เป็น bolus สำหรับ shock";

reasons['NL2-2023-Q108'] = "ทารกครบกำหนดคลอดด้วย C/S เนื่องจาก respiratory distress ร่วมกับ meconium-stained amniotic fluid ตรวจพบ central cyanosis, HR 80/min, poor tone\n\nKey findings: term newborn + meconium-stained fluid + central cyanosis + HR<100 + poor tone = non-vigorous newborn ที่ต้องการ resuscitation ทันที\n\nตาม NRP (Neonatal Resuscitation Program) guidelines ฉบับปรับปรุงปี 2015+ เมื่อทารกคลอดร่วมกับ meconium-stained fluid:\n- ถ้า vigorous (ร้อง, tone ดี, HR>100): routine care\n- ถ้า non-vigorous (ไม่ร้อง, poor tone, HR<100): เริ่ม initial steps (warmth, clear airway, dry, stimulate) แล้ว PPV ทันที ไม่ต้อง routine intubation เพื่อ suction tracheal meconium อีกต่อไป (เปลี่ยนจาก guidelines เดิมที่แนะนำ intubation + meconium aspiration)\n\nเหตุผลที่เปลี่ยน: evidence แสดงว่า routine tracheal suction ไม่ลด incidence ของ MAS (meconium aspiration syndrome) และ delay เวลาที่จะเริ่ม ventilation ซึ่งเป็นสิ่งสำคัญที่สุดสำหรับ non-vigorous newborn\n\n✅ B. PPV (Positive Pressure Ventilation) ถูกต้อง เป็น most appropriate initial management สำหรับ non-vigorous newborn ที่มี meconium-stained fluid ตาม NRP guidelines ปัจจุบัน เริ่ม PPV ทันทีเมื่อ initial steps ไม่ทำให้ดีขึ้น\n\n❌ A. 100% oxygen ไม่ถูกต้อง Free-flow oxygen alone ไม่เพียงพอสำหรับ newborn ที่ HR<100 + poor tone + cyanosis ต้อง PPV เพื่อ inflate lungs\n\n❌ C. Intubation with suction by meconium aspirator ไม่ถูกต้อง ตาม NRP guidelines ปัจจุบัน (2015+) ไม่แนะนำ routine tracheal suction สำหรับ meconium-stained fluid อีกต่อไป แม้ทารก non-vigorous ควรเริ่ม PPV ก่อน\n\n❌ D. Provide warmth and tactile stimulation ไม่ถูกต้อง เป็น initial steps ที่ทำก่อน PPV แต่เมื่อทารกมี HR<100 + cyanosis + poor tone หลัง initial steps ต้อง escalate ไป PPV ทันที warmth + stimulation alone ไม่เพียงพอ\n\n❌ E. Chest compression ไม่ถูกต้อง Chest compression ใช้เมื่อ HR<60 หลังจากให้ PPV ด้วย 100% oxygen อย่างมีประสิทธิภาพแล้ว 30 วินาที ผู้ป่วยรายนี้ HR 80 ยังไม่ถึงเกณฑ์ที่ต้อง chest compression";

reasons['NL2-2023-Q109'] = "ทารกแรกเกิดจากแม่ GA 32 สัปดาห์ ไม่มี ANC PROM 24 ชม. ได้ antibiotics ไม่ครบ ตรวจพบ BT 36.5, ดูสบายดี ถามว่านอกจาก CBC ควรส่งตรวจอะไรเพิ่ม\n\nRisk factors สำหรับ early-onset neonatal sepsis (EONS) ในรายนี้ ได้แก่ 1) Prematurity (32 weeks) 2) No ANC 3) Prolonged PROM >18 ชม. 4) Inadequate intrapartum antibiotics ทั้งหมดเป็น risk factors ที่สำคัญสำหรับ Group B Streptococcus (GBS) sepsis\n\nแม้ทารกดูสบายดี (asymptomatic) แต่ multiple risk factors ทำให้ต้อง evaluate สำหรับ sepsis ตาม AAP guidelines สำหรับ risk factor-based approach ควรส่ง blood culture + inflammatory markers (CRP) เพื่อ monitor ร่วมกับ serial clinical observation\n\nBlood culture เป็น gold standard สำหรับ diagnose bacteremia/sepsis ส่วน CRP เป็น inflammatory marker ที่ช่วย monitor ถ้า CRP สูงขึ้น serial จะช่วย support diagnosis ของ infection แม้ culture ยังไม่ขึ้น\n\n✅ D. Blood culture, CRP ถูกต้อง เป็น appropriate workup สำหรับ preterm neonate ที่ asymptomatic แต่มี multiple risk factors สำหรับ EONS Blood culture เพื่อ identify organism, CRP เพื่อ monitor inflammatory response\n\n❌ A. CRP ไม่ถูกต้อง CRP alone ไม่เพียงพอ ต้อง blood culture ร่วมด้วยเสมอเพื่อ identify organism และ guide antibiotic therapy\n\n❌ B. Blood culture ไม่ถูกต้อง Blood culture alone ก็ไม่เพียงพอ ต้อง CRP ร่วมด้วยเพื่อ monitor ถ้า culture negative แต่ clinical สงสัย CRP serial จะช่วย decide ว่าต้องให้ antibiotics ต่อหรือไม่\n\n❌ C. Blood culture, urine culture ไม่ถูกต้อง Urine culture ไม่จำเป็นสำหรับ evaluation ของ EONS (early-onset ภายใน 72 ชม.) เพราะ UTI ไม่ใช่ common source ใน early-onset sepsis Urine culture มีประโยชน์มากกว่าใน late-onset sepsis (หลัง 72 ชม.)\n\n❌ E. Blood culture, urine culture, lumbar puncture ไม่ถูกต้อง Full sepsis workup รวม LP เหมาะสำหรับ symptomatic neonates ที่สงสัย meningitis ทารกรายนี้ asymptomatic + comfortable จึงไม่จำเป็นต้อง LP เป็น initial evaluation";

reasons['NL2-2023-Q110'] = "ทารกแรกเกิด GA 37 สัปดาห์ มี jaundice ที่ 18 ชั่วโมงหลังคลอด Microbilirubin 17 mg/dL, Hct 37%\n\nJaundice ที่เกิดภายใน 24 ชั่วโมงแรกหลังคลอด ถือเป็น pathological jaundice เสมอ (ไม่ใช่ physiological) สาเหตุที่พบบ่อย ได้แก่ ABO incompatibility, Rh incompatibility, G6PD deficiency, spherocytosis\n\nTotal serum bilirubin 17 mg/dL ที่อายุ 18 ชั่วโมง — ตาม AAP nomogram/Bhutani nomogram จะอยู่ในระดับ high-risk zone ที่สูงมาก ที่อายุ 18 ชม. ค่า bilirubin ที่ถึงระดับ exchange transfusion จะอยู่ประมาณ 15-20 mg/dL (ขึ้นกับ gestational age และ risk factors) สำหรับ GA 37 weeks ค่า 17 mg/dL ที่อายุ 18 ชม. ถือว่าสูงมากจนอาจถึงระดับที่ต้อง exchange transfusion\n\nExchange transfusion ทำเมื่อ bilirubin สูงจนเสี่ยงต่อ acute bilirubin encephalopathy/kernicterus โดยเฉพาะเมื่อ bilirubin สูงเร็วมาก (rising rate มากกว่า 0.5 mg/dL/hr) หรือระดับ bilirubin ถึง exchange transfusion threshold ตาม nomogram\n\n✅ C. Total blood exchange transfusion ถูกต้อง เมื่อ bilirubin 17 mg/dL ที่อายุ 18 ชม. สูงถึง exchange threshold ตาม AAP nomogram ต้องทำ exchange transfusion เพื่อลด bilirubin อย่างรวดเร็วป้องกัน kernicterus\n\n❌ A. Phototherapy ไม่ถูกต้อง Phototherapy เป็น first-line treatment สำหรับ hyperbilirubinemia ที่ระดับต่ำกว่า exchange threshold แต่ bilirubin 17 mg/dL ที่ 18 ชม. สูงเกินกว่าจะรอ phototherapy alone ซึ่งลด bilirubin ได้ช้ากว่า exchange transfusion\n\n❌ B. Partial blood exchange transfusion ไม่ถูกต้อง Partial exchange ใช้สำหรับ polycythemia (Hct สูงมาก) ไม่ใช่สำหรับ hyperbilirubinemia Hct 37% ในรายนี้ปกติ\n\n❌ D. Reassure ไม่ถูกต้อง Jaundice ใน 24 ชม.แรก เป็น pathological เสมอ ต้อง investigate และ treat ไม่สามารถ reassure ได้\n\n❌ E. IVIG ไม่ถูกต้อง IVIG ใช้สำหรับ isoimmune hemolytic disease (เช่น ABO/Rh incompatibility) ที่ bilirubin สูงขึ้นเร็วแม้ได้ intensive phototherapy เป็น adjunctive therapy เพื่อลด rate of hemolysis ไม่ใช่ initial management เมื่อ bilirubin ถึง exchange threshold แล้ว";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');
  mongoose.disconnect();
}).catch(err => console.error(err.message));
