const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q201'] = "ทารก 9 เดือน leukocoria ถาม most likely diagnosis\n\nLeukocoria (white pupillary reflex/cat's eye reflex) ในทารก 9 เดือน → retinoblastoma จนกว่าจะ prove otherwise\n\nRetinoblastoma เป็น most common primary intraocular malignancy ในเด็ก (1:15,000-20,000) มักพบก่อนอายุ 3 ปี (median 18 เดือน) 40% bilateral (germline RB1 mutation) 60% unilateral มาด้วย leukocoria (60% presenting sign) หรือ strabismus (20%)\n\n✅ B. Retinoblastoma ถูกต้อง Leukocoria ในทารก = retinoblastoma จนกว่าจะ rule out\n\n❌ A. Neuroblastoma ไม่ถูกต้อง Neuroblastoma ไม่ทำให้ leukocoria ทำให้ periorbital ecchymosis (raccoon eyes) จาก orbital metastasis\n\n❌ C. Congenital cataract ไม่ถูกต้อง Congenital cataract ทำให้ leukocoria ได้ แต่มักพบตั้งแต่แรกเกิด ที่อายุ 9 เดือน retinoblastoma เป็น most likely cause\n\n❌ D. Lens dislocation ไม่ถูกต้อง Lens subluxation ทำให้ เห็น lens edge ผ่าน pupil ไม่ใช่ white reflex\n\n❌ E. Persistent fetal vasculature (PFV) ไม่ถูกต้อง PFV ทำให้ leukocoria ได้แต่มักพบตั้งแต่แรกเกิด unilateral microphthalmos ร่วมด้วย";

reasons['NL2-2023-Q202'] = "หญิง 25 ขวบ left eye pain + excessive tearing VA 6/6 both eyes left conjunctivitis with follicular reaction mildly tender preauricular LAD ถาม management\n\nFollicular conjunctivitis + preauricular lymphadenopathy + normal VA → viral (adenoviral) conjunctivitis\n\nAdenoviral conjunctivitis (epidemic keratoconjunctivitis = EKC) เป็น highly contagious eye infection แพร่ผ่าน direct contact กับ ocular secretions + fomites (towels, pillows, medical instruments) follicular reaction + preauricular LAD เป็น hallmark\n\nManagement: self-limited (1-3 สัปดาห์) + supportive (cold compress, artificial tears) + strict hygiene + CONTACT PRECAUTION เพื่อป้องกัน spread (handwashing, ไม่แชร์ towels, แยกของใช้)\n\n✅ E. Contact precaution ถูกต้อง Most important management เพื่อ prevent spread ของ highly contagious viral conjunctivitis\n\n❌ A. Topical steroid ไม่ถูกต้อง ไม่แนะนำในระยะแรกของ viral conjunctivitis อาจทำให้ worse + prolong viral shedding ใช้เมื่อมี subepithelial infiltrates ที่ affect vision\n\n❌ B. Topical antiviral/antifungal ไม่ถูกต้อง ไม่มี effective topical antiviral สำหรับ adenovirus (ต่างจาก HSV keratitis ที่ใช้ ganciclovir/trifluridine)\n\n❌ C. Topical antibiotic ไม่ถูกต้อง ไม่ effective ต่อ virus อาจให้เป็น prophylaxis ต่อ secondary bacterial infection แต่ไม่ใช่ primary management\n\n❌ D. Oral antibiotics ไม่ถูกต้อง ไม่เกี่ยวกับ viral conjunctivitis";

reasons['NL2-2023-Q203'] = "ผู้ป่วย left eye pain หลังสัมผัส hot glue 3 ชม.ก่อน left eye: ciliary injection + abnormal corneal light reflex ถาม initial management\n\nChemical/thermal burn to eye (hot glue) → corneal injury (abnormal corneal reflex = corneal damage)\n\nHot glue เป็น thermal + chemical burn ที่ cornea เมื่อมาถึง 3 ชม.หลังเกิดเหตุ immediate copious irrigation (ซึ่งเป็น most important first aid) ผ่านไปแล้ว management ต่อไปคือ promote corneal healing + prevent infection\n\nFrequent artificial tears (lubricant) ช่วย keep corneal surface moist + promote epithelial healing + wash out debris + pain relief ร่วมกับ topical antibiotic prophylaxis เพื่อป้องกัน secondary bacterial keratitis ที่ damaged corneal epithelium\n\n✅ D. Frequent artificial tear and topical ATB prophylaxis ถูกต้อง Promote healing + prevent infection ที่ damaged cornea\n\n❌ A. Cold compression ไม่ถูกต้อง ไม่ใช่ standard treatment สำหรับ corneal burn\n\n❌ B. Topical antihistamine ไม่ถูกต้อง ใช้สำหรับ allergic conjunctivitis ไม่ใช่ burn\n\n❌ C. Topical anesthesia with steroid eyedrops ไม่ถูกต้อง Topical anesthesia ใช้ชั่วคราวสำหรับ examination ไม่ควรให้ต่อเนื่องเพราะ inhibit corneal healing steroid อาจให้ในระยะหลังเพื่อลด inflammation แต่ไม่ใช่ initial management\n\n❌ E. Pressure patch ไม่ถูกต้อง Pressure patch ไม่แนะนำอีกต่อไปสำหรับ corneal abrasion/burn เพราะ studies แสดงว่า ไม่ improve healing + อาจ increase risk ของ infection";

reasons['NL2-2023-Q204'] = "หญิง 25 ขวบ left eyelid mass 3 เดือน ใช้ topical antibiotics 1 เดือนไม่ดีขึ้น PE: 5 mm diameter mass movable no tenderness ถาม management\n\nChronic painless eyelid mass + movable + non-tender + failed topical antibiotics → chalazion\n\nChalazion เป็น chronic granulomatous inflammation ของ meibomian gland (tarsal gland) จาก gland obstruction เกิด lipogranuloma ที่เป็น painless firm nodule ใน eyelid ต่างจาก hordeolum (stye) ที่เป็น acute painful infection\n\nChalazion ที่ persistent > 4-6 สัปดาห์ ไม่ตอบสนองต่อ conservative treatment → incision and curettage (I&C) ทำโดย incise tarsal conjunctiva side + curettage ของ granulomatous tissue\n\n✅ E. Incision & curettage ถูกต้อง Definitive treatment สำหรับ persistent chalazion ที่ failed conservative therapy\n\n❌ A. Observe and follow-up ไม่ถูกต้อง Already 3 เดือน + failed antibiotics ไม่ควร observe ต่อ\n\n❌ B. Warm compression ไม่ถูกต้อง Warm compress เป็น initial conservative treatment สำหรับ early chalazion 3 เดือนผ่านมาแล้ว ไม่ดีขึ้น\n\n❌ C. Topical antibiotic ointment ไม่ถูกต้อง Already failed 1 เดือน chalazion เป็น granulomatous ไม่ใช่ active infection ที่ antibiotics จะช่วย\n\n❌ D. Oral antibiotic ไม่ถูกต้อง ไม่ effective สำหรับ chronic granulomatous chalazion";

reasons['NL2-2023-Q205'] = "หญิง 20 ขวบ right upper eyelid swelling 1 วัน tender erythematous warm no fluctuation ถาม management\n\nAcute painful eyelid swelling + tender + erythematous + warm + NO fluctuation → hordeolum (stye) ในระยะ early inflammatory/cellulitis\n\nHordeolum เป็น acute bacterial infection ของ eyelid glands (external = Zeis/Moll gland, internal = meibomian gland) จาก S. aureus ระยะแรกเป็น inflammation ยังไม่เป็น abscess (no fluctuation)\n\nWarm compression เป็น first-line treatment ช่วย promote drainage ของ gland ทำ 10-15 min 4 ครั้ง/วัน ส่วนใหญ่หายเองใน 1-2 สัปดาห์ ถ้าไม่ดีขึ้นอาจเพิ่ม topical antibiotic ointment\n\n✅ B. Warm compression ถูกต้อง First-line treatment สำหรับ early hordeolum without fluctuation\n\n❌ A. Needle aspiration ไม่ถูกต้อง No fluctuation = no abscess ไม่มีอะไรให้ aspirate\n\n❌ C. Incision and curettage ไม่ถูกต้อง สำหรับ chronic chalazion ไม่ใช่ acute hordeolum\n\n❌ D. Pressure patch ไม่ถูกต้อง ไม่ใช่ treatment สำหรับ hordeolum\n\n❌ E. Incisional biopsy ไม่ถูกต้อง ไม่จำเป็นสำหรับ acute inflammatory lesion ที่ clearly hordeolum";

reasons['NL2-2023-Q206'] = "หญิง 70 ขวบ mass ที่ upper eyelid + on/off discharge 1 ปี erythematous + excessive tearing ถาม diagnosis\n\nChronic mass near lacrimal system + discharge + excessive tearing (epiphora) → dacryocystitis\n\nDacryocystitis เป็น infection/inflammation ของ lacrimal sac จาก nasolacrimal duct obstruction (NLDO) ทำให้ tears ไม่สามารถ drain ลงจมูกได้ → stasis → bacterial infection → เกิด mass + discharge + epiphora\n\nChronic dacryocystitis ในผู้สูงอายุมักเกิดจาก acquired NLDO จาก chronic inflammation/fibrosis อาการ on/off discharge + epiphora เป็นลักษณะเรื้อรัง definitive treatment: dacryocystorhinostomy (DCR)\n\n✅ C. Dacryocystitis ถูกต้อง Chronic mass + discharge + epiphora = chronic dacryocystitis จาก NLDO\n\n❌ A. Hordeolum ไม่ถูกต้อง Hordeolum เป็น acute painful eyelid mass ที่หายใน 1-2 สัปดาห์ ไม่ persistent 1 ปี\n\n❌ B. Lacrimal sac tumor ไม่ถูกต้อง Lacrimal sac tumor พบน้อยมาก มักเป็น painless mass ที่ progressively enlarges without on/off discharge pattern\n\n❌ D. Canaliculitis ไม่ถูกต้อง Canaliculitis มี pouting punctum + concretions (sulfur granules จาก Actinomyces) ไม่ใช่ mass ที่ eyelid\n\n❌ E. Chalazion ไม่ถูกต้อง Chalazion เป็น painless mass ใน eyelid จาก meibomian gland obstruction ไม่มี excessive tearing เป็น feature หลัก";

reasons['NL2-2023-Q207'] = "ชายหนุ่มถูกตีที่ orbital area ด้วย baseball bat anterior chamber มี blood ที่ half-level (hyphema) VA: hand movement only X-ray: no orbital fracture ถาม management\n\nTraumatic hyphema (blood ใน anterior chamber) + severely reduced VA (hand movement) = serious eye injury ที่ต้อง management อย่างระมัดระวัง\n\nHyphema management ประกอบด้วย 1) Absolute bed rest + head elevation 30-45 degrees (ให้ blood settle ลง inferior AC ด้วย gravity ไม่บัง visual axis + prevent rebleed) 2) Eye shield (protect จาก further trauma) 3) Cycloplegic drops (atropine) ลด ciliary spasm + pain + stabilize blood-aqueous barrier 4) Topical steroid ลด inflammation 5) Avoid aspirin/NSAIDs (increase bleeding risk) 6) Monitor IOP (blood อาจ obstruct trabecular meshwork → acute glaucoma)\n\n✅ D. Absolute bed rest, head elevation ถูกต้อง เป็น cornerstone ของ hyphema management\n\n❌ A. CT orbit ไม่ถูกต้อง X-ray ไม่มี fracture CT อาจทำเพิ่มแต่ไม่ใช่ primary management\n\n❌ B. Topical antibiotic ไม่ถูกต้อง ไม่ใช่ primary management สำหรับ hyphema\n\n❌ C. Pressure patch ไม่ถูกต้อง Pressure patch อาจเพิ่ม IOP ไม่แนะนำใน hyphema ใช้ eye shield แทน\n\n❌ E. Artificial tear drops ไม่ถูกต้อง ไม่ใช่ primary treatment";

reasons['NL2-2023-Q208'] = "ชาย 18 ขวบ left ear pain 1 วัน หลังแคะหูด้วย cotton swab otoscopic exam shown ถาม treatment\n\nEar pain หลัง cotton swab use → otitis externa หรือ ear canal trauma + infected debris Otoscopic exam สมมติแสดง debris/cerumen/inflammation ใน ear canal\n\nEar toilet (aural toilet) เป็น cleaning ของ ear canal โดย remove debris, cerumen, discharge ออกด้วย suction หรือ cotton-tipped applicator ภายใต้ otoscopic visualization เป็น initial step ที่สำคัญที่สุดก่อนให้ topical treatment เพราะ debris ที่อุดจะ block topical medication ไม่ให้ถึง infected tissue\n\n✅ A. Ear toilet ถูกต้อง Initial management เพื่อ clean ear canal ก่อนให้ topical treatment\n\n❌ B. Topical antibiotic ไม่ถูกต้อง Topical antibiotic อาจจำเป็นหลัง ear toilet แต่ต้อง clean canal ก่อน ถ้า canal full of debris topical drops จะไม่ effective\n\n❌ C. Myringoplasty ไม่ถูกต้อง Surgery สำหรับ TM perforation ไม่ใช่ initial management สำหรับ ear pain จาก cotton swab\n\n❌ D. Tympanoplasty ไม่ถูกต้อง Surgery สำหรับ chronic ear disease + hearing reconstruction ไม่ใช่ initial treatment\n\n❌ E. Paper patch ไม่ถูกต้อง Paper patch ใช้สำหรับ small TM perforation ไม่ใช่ initial management สำหรับ ear pain";

reasons['NL2-2023-Q209'] = "Thai boxer ชาย 25 ขวบ right ear pain 2 วัน PE picture shown ถาม most appropriate antibiotics\n\nThai boxer + ear pain + ภาพ (สมมติ auricular perichondritis/otitis externa จาก trauma) → need antibiotic ที่ครอบคลุม Pseudomonas aeruginosa\n\nAuricular perichondritis/otitis externa ที่เกิดจาก trauma (จาก boxing) มี risk สูงสำหรับ Pseudomonas aeruginosa infection ซึ่งเป็น common pathogen ใน ear infections โดยเฉพาะเมื่อมี trauma/moisture exposure\n\nCiprofloxacin เป็น fluoroquinolone ที่มี excellent activity ต่อ Pseudomonas aeruginosa เป็น drug of choice สำหรับ ear infections ที่สงสัย Pseudomonas (malignant otitis externa, perichondritis, otitis externa)\n\n✅ C. Ciprofloxacin ถูกต้อง Covers Pseudomonas ซึ่งเป็น common pathogen ใน traumatic ear infections\n\n❌ A. Amoxicillin ไม่ถูกต้อง ไม่ครอบคลุม Pseudomonas\n\n❌ B. Ceftriaxone ไม่ถูกต้อง 3rd gen ceph มี variable Pseudomonal activity ไม่ใช่ optimal choice\n\n❌ D. Clindamycin ไม่ถูกต้อง ไม่ครอบคลุม Pseudomonas ครอบคลุม gram-positive + anaerobes\n\n❌ E. Erythromycin ไม่ถูกต้อง ไม่ครอบคลุม Pseudomonas";

reasons['NL2-2023-Q210'] = "ผู้ป่วย 40 ขวบ dizziness + spinning sensation เมื่อนอนตะแคงซ้าย ear exam + otoscopy ปกติ ถาม diagnosis\n\nPositional vertigo (spinning เมื่อเปลี่ยน position นอนตะแคง) + normal ear exam → BPPV (Benign Paroxysmal Positional Vertigo)\n\nBPPV เป็น most common cause ของ peripheral vertigo เกิดจาก otoconia (calcium carbonate crystals) หลุดจาก utricle ไปอยู่ใน semicircular canal (มักเป็น posterior canal) เมื่อเปลี่ยน position ของศีรษะ otoconia เคลื่อนตัวใน canal ทำให้ endolymph flow ผิดปกติ → stimulate hair cells → vertigo + nystagmus\n\nCharacteristic features: brief episodes (10-60 sec) ของ vertigo ที่ triggered by specific head positions (นอนตะแคง, ก้มหัว, แหงนหัว) มี latency 1-5 sec ก่อน onset + fatigable (ทำซ้ำอาการลดลง)\n\nDiagnosis: Dix-Hallpike maneuver (positive = upbeat torsional nystagmus) Treatment: Epley maneuver (canalith repositioning)\n\n✅ D. BPPV ถูกต้อง Positional vertigo + normal ear exam = classic BPPV\n\n❌ A. Acute otitis media ไม่ถูกต้อง AOM มี ear pain + fever + abnormal TM (erythematous, bulging) ear exam ปกติ rule out AOM\n\n❌ B. Meniere's disease ไม่ถูกต้อง Meniere มี triad: episodic vertigo (นาทีถึงชั่วโมง) + sensorineural hearing loss + tinnitus + aural fullness ไม่ใช่ positional vertigo ที่เป็นวินาที\n\n❌ C. Vestibular insufficiency ไม่ถูกต้อง Vestibular hypofunction มี chronic imbalance + gait unsteadiness ไม่ใช่ brief positional vertigo\n\n❌ E. Vestibular neuritis ไม่ถูกต้อง มี acute onset severe continuous vertigo (นานหลายวัน) + nausea/vomiting ไม่ใช่ brief positional episodes";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');
  mongoose.disconnect();
}).catch(err => console.error(err.message));
