const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q161'] = "ทารกชาย 3 เดือน URI + dark urine 2 วัน BT 38 anicteric sclera liver 1 fb BRCM (span 7 cm) spleen not palpable CBC: Hb 7 Hct 20% MCV 85 (normocytic) Platelet 160,000 WBC 5,500 ถาม investigation\n\nInfection trigger (URI, fever) → acute hemolysis (dark urine, severe anemia Hb 7) + MCV 85 (normocytic ไม่ใช่ microcytic) → G6PD deficiency เป็น most likely diagnosis\n\nMCV 85 ช่วยแยก thalassemia (MCV ต่ำ/microcytic) ออก ในเด็กที่มี acute hemolysis จาก infection trigger + normocytic anemia → G6PD deficiency\n\nSupravital stain จะเห็น Heinz bodies (denatured hemoglobin precipitates จาก oxidative damage) ซึ่งเป็น diagnostic finding ของ G6PD deficiency\n\n✅ B. Supravital stain ถูกต้อง Detect Heinz bodies ที่เป็น hallmark ของ G6PD deficiency acute hemolysis\n\n❌ A. Urinalysis ไม่ถูกต้อง UA เห็น hemoglobinuria ได้แต่ไม่ specify cause\n\n❌ C. OF test ไม่ถูกต้อง สำหรับ hereditary spherocytosis ไม่ใช่ G6PD\n\n❌ D. DAT ไม่ถูกต้อง สำหรับ AIHA ซึ่ง uncommon ในทารก 3 เดือน\n\n❌ E. Bone marrow aspiration ไม่ถูกต้อง Invasive ไม่จำเป็นเมื่อ peripheral blood test สามารถ diagnose ได้";

reasons['NL2-2023-Q162'] = "เด็กชาย 7 ขวบ frequent brief staring spells 1 เดือน ครูบอกว่ามี staring spells บ่อย ไม่ตอบสนองเมื่อเรียก ผลการเรียนลดลง ถาม diagnosis\n\nFrequent brief staring episodes + unresponsive during episodes + declining school performance ในเด็กวัยเรียน → absence seizure (petit mal)\n\nAbsence seizure เป็น primary generalized seizure ที่พบบ่อยในเด็กอายุ 4-12 ปี ลักษณะเฉพาะคือ sudden onset + brief duration (5-30 วินาที) ของ behavioral arrest (staring) + unresponsiveness + abrupt offset ผู้ป่วยไม่ทราบว่าเกิด seizure (amnesia during episode) กลับมา alert ทันทีหลัง episode หมด ไม่มี post-ictal confusion\n\nEEG จะแสดง 3 Hz generalized spike-and-wave discharges ซึ่งเป็น pathognomonic Hyperventilation สามารถ provoke absence seizure ได้ (ใช้เป็น activation procedure ใน EEG)\n\nFirst-line treatment: ethosuximide (สำหรับ absence only) หรือ valproic acid (สำหรับ absence + GTC)\n\n✅ B. Absence seizure ถูกต้อง Brief staring + unresponsiveness + frequent episodes + declining school performance เป็น classic presentation\n\n❌ A. Daydreaming ไม่ถูกต้อง Daydreaming สามารถ interrupt ได้เมื่อเรียก ไม่มี true unresponsiveness ต่างจาก absence seizure ที่ truly unresponsive\n\n❌ C. Complex partial seizure ไม่ถูกต้อง Complex partial seizure มี aura, automatisms (lip smacking, hand fumbling), post-ictal confusion และ duration นานกว่า (1-2 นาที) ไม่ใช่ brief staring 5-30 วินาทีแบบ absence\n\n❌ D. Delayed development ไม่ถูกต้อง ผู้ป่วยเคย perform ได้ปกติก่อนหน้า school performance เพิ่งลดลง ไม่ใช่ delayed development\n\n❌ E. ADHD ไม่ถูกต้อง ADHD มี inattention + hyperactivity + impulsivity แต่ไม่มี true unresponsive staring episodes ที่เป็น seizure";

reasons['NL2-2023-Q163'] = "เด็กชาย 10 ขวบ behavioral problems 2 ปี humming + cough ตลอดวัน ทำให้เพื่อนรำคาญ พ่อแม่ถามว่าเป็นเพราะต้องการ attention ไหม เพราะเขา control ได้บางครั้ง ถาม diagnosis\n\nChronic (>1 ปี) involuntary motor tics (humming) + vocal tics (cough-like) ที่เกิดตลอดวัน + can suppress temporarily (แต่ไม่ได้ control ได้จริง) → Tourette's syndrome\n\nTourette's syndrome (TS) เป็น neurodevelopmental disorder ที่มี multiple motor tics + at least one vocal tic ดำเนินมานานกว่า 1 ปี เริ่มก่อนอายุ 18 ปี Tics เป็น sudden, rapid, recurrent, non-rhythmic motor movements หรือ vocalizations ที่ involuntary แม้ผู้ป่วยอาจ suppress ได้ชั่วคราวแต่จะเกิด buildup of inner tension จนต้อง tic ออกมา (premonitory urge)\n\nHumming เป็น phonic/vocal tic, repetitive cough-like sounds เป็น vocal tic ทั้งสองเกิดมานาน 2 ปี ร่วมกับ behavioral problems\n\n✅ D. Tourette's syndrome ถูกต้อง Multiple motor + vocal tics > 1 ปี + childhood onset\n\n❌ A. Epilepsy ไม่ถูกต้อง Seizures เป็น paroxysmal events ที่มี altered consciousness ไม่ใช่ repetitive vocalizations ตลอดวัน\n\n❌ B. Malingering ไม่ถูกต้อง Malingering คือ intentional production ของ symptoms เพื่อ secondary gain TS tics เป็น involuntary แม้ suppress ได้บ้างก็ไม่ใช่ malingering\n\n❌ C. Tic syndrome ไม่ถูกต้อง Provisional tic disorder = tics < 1 ปี Chronic tic disorder = motor OR vocal tics > 1 ปี TS = motor AND vocal tics > 1 ปี ผู้ป่วยรายนี้มีทั้ง motor + vocal tics > 1 ปี จึงเป็น TS\n\n❌ E. ADD ไม่ถูกต้อง ADD/ADHD มี inattention ± hyperactivity ไม่มี tics แม้ ADHD อาจ comorbid กับ TS ได้ แต่ primary diagnosis คือ TS";

reasons['NL2-2023-Q164'] = "หญิง 12 สัปดาห์ vaginal bleeding os closed TVS: fetus present without heart sound ถาม diagnosis\n\nVaginal bleeding + closed cervical os + fetus present แต่ไม่มี heart sound → missed abortion\n\nMissed abortion (missed miscarriage) คือ fetal death in utero ที่ยังไม่ถูกขับออก (retained in uterus) ผู้ป่วยมักไม่ทราบว่า fetus เสียชีวิตแล้ว อาจมี vaginal bleeding เล็กน้อย cervical os ยังปิดอยู่ TVS จะเห็น fetus ที่ไม่มี cardiac activity\n\n✅ B. Missed abortion ถูกต้อง Fetus present + no heart sound + closed os = fetal death without expulsion\n\n❌ A. Inevitable abortion ไม่ถูกต้อง Inevitable abortion มี open cervical os ± ruptured membranes แสดงว่า process ของการแท้งเริ่มแล้ว ผู้ป่วยรายนี้ os ปิด\n\n❌ C. Incomplete abortion ไม่ถูกต้อง Incomplete abortion มี open os + partial expulsion ของ products of conception ยังมี tissue เหลืออยู่ใน uterus\n\n❌ D. Complete abortion ไม่ถูกต้อง Complete abortion คือ expulsion ของ products ทั้งหมด os ปิดแล้ว uterus ว่าง TVS จะไม่เห็น fetus\n\n❌ E. Threatened abortion ไม่ถูกต้อง Threatened abortion มี vaginal bleeding + closed os + fetus มี heart sound (viable) ต่างจาก missed abortion ที่ไม่มี heart sound";

reasons['NL2-2023-Q165'] = "หญิง primigravida 32 ขวบ ได้ rubella vaccination 2 สัปดาห์ก่อน แล้วพบว่า pregnant GA 8 สัปดาห์ ถาม management\n\nRubella vaccine เป็น live attenuated vaccine ตาม guidelines แนะนำให้หลีกเลี่ยงตั้งครรภ์หลังฉีด 1 เดือน (CDC) หรือ 3 เดือน (WHO) อย่างไรก็ตาม จาก data ของ CDC Vaccine in Pregnancy Registry ที่ติดตาม pregnant women ที่ได้รับ rubella vaccine โดยไม่ทราบว่าตั้งครรภ์ ไม่พบ case ใดที่เกิด congenital rubella syndrome จากวัคซีน\n\nDespite theoretical risk ตาม CDC guidelines ไม่แนะนำ termination of pregnancy เมื่อได้ rubella vaccine ระหว่างตั้งครรภ์หรือก่อนตั้งครรภ์ เพราะ evidence แสดงว่า risk of CRS จากวัคซีน negligible\n\n✅ A. Reassurance ถูกต้อง ไม่มี documented case ของ CRS จาก rubella vaccination ระหว่างตั้งครรภ์ reassure ผู้ป่วยว่า risk ต่ำมาก ไม่ต้อง terminate\n\n❌ B. Maternal rubella IgG ไม่ถูกต้อง IgG จะ positive จากวัคซีน ไม่ช่วย differentiate vaccine strain จาก wild-type infection\n\n❌ C. Cordocentesis for rubella IgM ไม่ถูกต้อง Invasive procedure ที่ไม่จำเป็นเมื่อ risk ต่ำมาก\n\n❌ D. Amniocentesis for rubella PCR ไม่ถูกต้อง ไม่จำเป็น เพราะ vaccine strain ไม่ทำให้ CRS\n\n❌ E. Termination of pregnancy ไม่ถูกต้อง ไม่มี indication สำหรับ termination จากการได้รับ rubella vaccine ตาม CDC guidelines";

reasons['NL2-2023-Q166'] = "หญิง primigravida 32 ขวบ GA 12 สัปดาห์ severe nausea + vomiting ไม่มี vaginal bleeding ไม่มี abdominal pain ตรวจพบ fundal height 2/3 above pubic symphysis (ใหญ่กว่า dates) other PE + lab normal ถาม most beneficial investigation\n\nSevere nausea/vomiting ใน first trimester + fundal height larger than expected for GA 12 สัปดาห์ → need to rule out molar pregnancy (hydatidiform mole) หรือ multiple gestation\n\nFundal height 2/3 above pubic symphysis ที่ GA 12 สัปดาห์ ถือว่า larger than expected เพราะ uterus ปกติที่ 12 สัปดาห์ ควรจะอยู่ที่ pubic symphysis พอดี ขนาดที่ใหญ่กว่าอาจเกิดจาก molar pregnancy (trophoblastic proliferation), multiple pregnancy หรือ wrong dates\n\nTransabdominal ultrasonography (TAS) เป็น investigation ที่ beneficial ที่สุดเพราะสามารถ visualize ว่ามี viable intrauterine pregnancy, molar pregnancy (snowstorm pattern), twins หรือ wrong dates ได้ทันที\n\n✅ E. Transabdominal ultrasonography ถูกต้อง เป็น most beneficial investigation ที่ให้ diagnosis ได้ทันที\n\n❌ A. Serum beta-hCG ไม่ถูกต้อง beta-hCG สูงใน molar pregnancy + normal pregnancy + twins ไม่ differentiate ได้ดีเท่า US\n\n❌ B. 75 g OGTT ไม่ถูกต้อง GDM screening ทำที่ 24-28 สัปดาห์ ไม่ใช่ 12 สัปดาห์\n\n❌ C. Serum electrolytes ไม่ถูกต้อง Check dehydration จาก vomiting ได้ แต่ไม่ให้ diagnosis\n\n❌ D. Thyroid function test ไม่ถูกต้อง Hyperthyroidism สัมพันธ์กับ hyperemesis gravidarum ได้ (จาก hCG ที่มี TSH-like activity) แต่ TFT ไม่ให้ root cause diagnosis เท่า US";

reasons['NL2-2023-Q167'] = "หญิง 20 ขวบ GA 12 สัปดาห์ severe nausea/vomiting + vaginal bleeding ใช้ clomiphene สำหรับ pregnancy fundal height 2/3 above pubic symphysis (larger than expected) ถาม most beneficial investigation\n\nSevere N/V + vaginal bleeding + fundal height larger than dates + clomiphene use (increased risk of multiple pregnancy) → similar to Q166 need US to evaluate\n\nClomiphene citrate เป็น ovulation induction drug ที่เพิ่ม risk ของ multiple gestation (twins 5-8%) + มี small increased risk ของ molar pregnancy\n\nVaginal bleeding ที่ 12 สัปดาห์ อาจเป็น threatened abortion, molar pregnancy หรือ subchorionic hemorrhage US จะ differentiate ได้\n\n✅ E. Transabdominal ultrasound ถูกต้อง Evaluate fetal viability, number of fetuses, molar pregnancy, cause of vaginal bleeding\n\n❌ A. Serum beta-hCG ไม่ถูกต้อง ไม่ให้ structural diagnosis เท่า US\n\n❌ B. Serum electrolytes ไม่ถูกต้อง ไม่ให้ diagnosis\n\n❌ C. Thyroid function test ไม่ถูกต้อง ไม่ให้ root cause diagnosis\n\n❌ D. 75 g OGTT ไม่ถูกต้อง ไม่เกี่ยวข้องกับ presentation นี้";

reasons['NL2-2023-Q168'] = "หญิง G2P1 GA 12 สัปดาห์ first ANC ลูกคนก่อน 4,700 g (macrosomia) 50g GCT = 130 mg/dL ถาม management\n\nPrevious macrosomia (4,700 g) เป็น risk factor สำหรับ gestational diabetes mellitus (GDM) 50g GCT 130 mg/dL ≥ 130 mg/dL (หรือ 140 ขึ้นกับ cut-off) ถือว่า screen positive ต้องทำ confirmatory test ด้วย 100g OGTT\n\n100g OGTT (3-hour glucose tolerance test) เป็น gold standard confirmatory test สำหรับ GDM ตาม Carpenter-Coustan criteria: fasting ≥ 95, 1hr ≥ 180, 2hr ≥ 155, 3hr ≥ 140 mg/dL ต้อง abnormal ≥ 2 ค่าจึง diagnose GDM\n\n✅ D. 100 g OGTT ถูกต้อง เป็น confirmatory test หลัง positive screening (50g GCT ≥ 130)\n\n❌ A. Monitor 2 hr postprandial blood sugar ไม่ถูกต้อง ใช้ monitor GDM หลัง diagnosis ไม่ใช่ diagnostic test\n\n❌ B. HbA1C at GA 24 week ไม่ถูกต้อง HbA1C ไม่แนะนำเป็น diagnostic test สำหรับ GDM เพราะ physiologic changes ของ pregnancy ทำให้ HbA1C ต่ำลง\n\n❌ C. 50 g GCT at GA 28 week ไม่ถูกต้อง ผู้ป่วย screen positive แล้ว ไม่ต้อง repeat screening ต้อง proceed to confirmatory test\n\n❌ E. Fasting plasma glucose ไม่ถูกต้อง FPG alone ไม่เพียงพอเป็น confirmatory test สำหรับ GDM";

reasons['NL2-2023-Q169'] = "หญิง 18 ขวบ GA 23 สัปดาห์ ANC visit PE ปกติ UA: trace glucosuria ถาม management\n\nTrace glucosuria ใน pregnancy ที่ PE ปกติ → physiological glucosuria of pregnancy\n\nใน pregnancy renal threshold สำหรับ glucose ลดลง (จาก increased GFR + decreased tubular reabsorption) ทำให้ glucose รั่วใน urine ได้แม้ blood glucose ปกติ พบได้ถึง 50% ของ pregnant women ไม่จำเป็นต้อง further workup เมื่อเป็น trace amount และไม่มี risk factors สำหรับ GDM\n\n✅ A. Reassure ถูกต้อง Trace glucosuria เป็น physiological finding ใน pregnancy\n\n❌ B. 50 g GCT ไม่ถูกต้อง GCT screening ทำที่ 24-28 สัปดาห์ ผู้ป่วย 23 สัปดาห์ยังไม่ถึง screening time และ trace glucosuria alone ไม่ใช่ indication สำหรับ early screening ในผู้ป่วยที่ไม่มี risk factors\n\n❌ C. 100 g OGTT ไม่ถูกต้อง ทำหลัง positive GCT screening ไม่ใช่ทำเลย\n\n❌ D. Fasting plasma glucose ไม่ถูกต้อง ไม่จำเป็นสำหรับ trace glucosuria ใน pregnancy\n\n❌ E. HbA1C ไม่ถูกต้อง ไม่แนะนำสำหรับ GDM screening";

reasons['NL2-2023-Q170'] = "หญิง G1P0 GA 23 สัปดาห์ รู้สึก quickening 4 สัปดาห์ก่อน (GA 19 สัปดาห์) อื่นๆ unremarkable fundal height 23 cm ไม่ detect fetal movement + heart sound ถาม management\n\nGA 23 สัปดาห์ ไม่ได้ยินเสียงหัวใจทารก ไม่ detect fetal movement ทั้งที่เคย quickening → ต้องสงสัย fetal demise หรือ wrong dates\n\nTransabdominal ultrasound เป็น investigation ที่เหมาะสมที่สุดเพื่อ evaluate fetal viability, cardiac activity, fetal growth, amniotic fluid volume\n\n✅ D. Transabdominal ultrasound ถูกต้อง ประเมิน fetal viability + cardiac activity ได้ทันที\n\n❌ A. Reassurance ไม่ถูกต้อง ไม่ detect fetal heart sound + movement ที่ 23 สัปดาห์ต้อง evaluate ไม่สามารถ reassure ได้\n\n❌ B. Fetal movement counting ไม่ถูกต้อง ไม่ detect fetal movement อยู่แล้ว ต้อง US ก่อน\n\n❌ C. Vibroacoustic stimulation ไม่ถูกต้อง ใช้ stimulate fetal movement ใน NST ไม่ใช่ initial evaluation\n\n❌ E. 1 week appointment ไม่ถูกต้อง Delay 1 สัปดาห์ไม่เหมาะสมเมื่อสงสัย fetal demise ต้อง evaluate ทันที";

reasons['NL2-2023-Q171'] = "หญิง 25 ขวบ GA 29 สัปดาห์ PROM 4 ชม. ไม่มี uterine contraction os closed amniotic fluid leaking TAS: single viable fetus no anomalies FHR 140 deep vertical pocket 3 cm ถามนอกจาก corticosteroid ให้อะไร\n\nPreterm PROM (PPROM) ที่ GA 29 สัปดาห์ — ทารก viable แต่ preterm management หลักคือ 1) Corticosteroid สำหรับ fetal lung maturation 2) Antibiotics เพื่อ prolong latency period + reduce infection 3) Close monitoring\n\nAntibiotics ใน PPROM ช่วย prolong latency (ยืดเวลาจาก ROM ถึง delivery) + ลด chorioamnionitis + ลด neonatal sepsis Regimen ที่แนะนำ: ampicillin IV 48 ชม. + erythromycin IV 48 ชม. ตามด้วย amoxicillin + erythromycin PO 5 วัน\n\nDeep vertical pocket 3 cm แสดงว่ายังมี amniotic fluid เพียงพอ (oligohydramnios = DVP < 2 cm)\n\n✅ A. Antibiotics for prolonged latent phase ถูกต้อง ช่วยยืดเวลาก่อนคลอด + ลด infection risk\n\n❌ B. MgSO4 for neuroprotective ไม่ถูกต้อง MgSO4 สำหรับ neuroprotection ให้เมื่อ delivery imminent ที่ < 32 สัปดาห์ ผู้ป่วยรายนี้ไม่มี contraction ยังไม่ imminent delivery\n\n❌ C. Tocolytic ไม่ถูกต้อง Tocolysis ใน PPROM ไม่แนะนำเป็น routine เพราะไม่ improve neonatal outcomes และอาจ mask signs of chorioamnionitis\n\n❌ D. Oxytocin ไม่ถูกต้อง Oxytocin induction ที่ 29 สัปดาห์ไม่เหมาะสม ต้องพยายาม prolong pregnancy\n\n❌ E. Emergency C/S ไม่ถูกต้อง ไม่มี indication สำหรับ emergency C/S (no fetal distress, no infection, no cord prolapse)";

reasons['NL2-2023-Q172'] = "Normal labor เกิด anterior shoulder dystocia ถาม initial management\n\nShoulder dystocia เป็น obstetric emergency ที่ anterior shoulder ติด pubic symphysis หลัง delivery ของ head การ manage ต้องทำอย่างเป็นระบบตาม HELPERR mnemonic\n\nMcRoberts maneuver เป็น first-line intervention ที่มี success rate สูง (42% สำเร็จด้วย McRoberts alone) ทำโดย hyperflexion ของ maternal hips (ดึง thighs ชิดหน้าอก) ซึ่งทำให้ sacrum flatten, pubic symphysis ยกขึ้น เพิ่ม anteroposterior diameter ของ pelvic outlet ทำให้ anterior shoulder หลุดจาก pubic symphysis\n\n✅ C. McRoberts maneuver ถูกต้อง First-line initial management สำหรับ shoulder dystocia\n\n❌ A. Rubin maneuver ไม่ถูกต้อง Rubin I (suprapubic pressure) ทำพร้อม McRoberts, Rubin II (rotate shoulder) เป็น second-line หลัง McRoberts ล้มเหลว\n\n❌ B. Zavanelli maneuver ไม่ถูกต้อง Last resort = cephalic replacement (push head back in) แล้ว C/S ทำเมื่อทุก maneuver อื่นล้มเหลว\n\n❌ D. Posterior shoulder delivery ไม่ถูกต้อง (Woods screw + posterior arm delivery) เป็น second/third-line maneuver\n\n❌ E. Wood-corkscrew maneuver ไม่ถูกต้อง เป็น rotational maneuver ที่เป็น second-line";

reasons['NL2-2023-Q173'] = "หญิง G2P1 GA 38 สัปดาห์ severe headache 60 นาที BP 200/105 PR 90 ไม่มี contraction ขณะตรวจเกิด drowsiness + GTC seizure นอกจาก airway management ถาม management\n\nPregnant + severe hypertension (200/105) + headache + seizure → eclampsia\n\nEclampsia คือ preeclampsia ที่มี seizure เกิดจาก cerebral vasospasm + edema ของ brain จาก severe hypertension เป็น obstetric emergency\n\nMgSO4 (Magnesium sulfate) เป็น drug of choice สำหรับ eclamptic seizure ออกฤทธิ์ 1) CNS depression ลด seizure threshold 2) Vasodilation ของ cerebral vessels ลด vasospasm 3) Competitive inhibition ของ calcium ที่ neuromuscular junction Loading dose: 4-6 g IV ใน 15-20 นาที Maintenance: 1-2 g/hr IV infusion Monitor: deep tendon reflexes, respiratory rate, urine output, serum Mg level\n\n✅ D. MgSO4 ถูกต้อง Drug of choice สำหรับ eclamptic seizure prevention + treatment\n\n❌ A. Nicardipine ไม่ถูกต้อง ใช้ lower BP แต่ไม่ prevent/treat seizure ใน eclampsia MgSO4 ทำได้ทั้ง anti-seizure + mild BP lowering\n\n❌ B. Labetalol ไม่ถูกต้อง ใช้ lower BP ใน preeclampsia แต่ไม่ใช่ anti-seizure drug\n\n❌ C. Methyldopa ไม่ถูกต้อง Oral antihypertensive สำหรับ chronic management ไม่ใช่ acute eclampsia\n\n❌ E. Diazepam ไม่ถูกต้อง Benzodiazepine สามารถหยุด seizure ได้ แต่ MgSO4 เป็น superior choice ในดรรชนี eclampsia เพราะ prevent recurrent seizure ได้ดีกว่า + ไม่กด respiratory ของทารก";

reasons['NL2-2023-Q174'] = "หญิง GA 37 สัปดาห์ labor pain fundal height 3/4 above umbilicus fully dilated effacement 100% station 0 EFM shown ถาม management\n\nGA 37 สัปดาห์ fully dilated (10 cm) effacement 100% station 0 → active second stage of labor EFM shown (สมมติ normal/reassuring)\n\nเมื่อ cervix fully dilated + EFM reassuring → observe labor progression ให้ maternal effort (pushing) ทำงาน ทารก descend ผ่าน birth canal\n\n✅ A. Observe labor progression ถูกต้อง เมื่อ fully dilated + EFM reassuring → allow natural progression ของ second stage\n\n❌ B. Vacuum extraction ไม่ถูกต้อง ต้องมี indication (prolonged 2nd stage, non-reassuring FHR) + station ≥ +2 ก่อนใช้ vacuum ปัจจุบัน station 0 ยังสูงเกินไป\n\n❌ C. Forceps extraction ไม่ถูกต้อง เหมือน vacuum ต้องมี indication + adequate station\n\n❌ D. IV oxytocin ไม่ถูกต้อง Oxytocin augmentation ใน 2nd stage อาจพิจารณาเมื่อ inadequate contractions + prolonged 2nd stage แต่ยังไม่ prolonged ยังไม่ต้อง augment\n\n❌ E. Emergency C/S ไม่ถูกต้อง ไม่มี indication (no fetal distress, fully dilated)";

reasons['NL2-2023-Q175'] = "หญิง G2P1 GA 39 สัปดาห์ labor pain ไม่มี complications uterine contraction interval 2-3 min duration 50 sec cervix 8 cm dilated effacement 100% station +1 ถาม management\n\nG2P1 active labor: cervix 8 cm (near fully dilated), adequate contractions (q 2-3 min, 50 sec), station +1, EFM pattern? → normal labor progression\n\nMultipara ที่ cervix 8 cm + adequate contractions + station +1 → labor progressing well ควร observe ต่อ 1 ชม. แล้ว reassess cervical dilatation + descent\n\n✅ B. Observe labor progression for 1 hour ถูกต้อง Labor progressing normally ไม่ต้อง intervention\n\n❌ A. IV oxytocin ไม่ถูกต้อง Contractions adequate (q 2-3 min) ไม่ต้อง augment\n\n❌ C. NST ไม่ถูกต้อง EFM กำลัง monitor อยู่แล้ว ไม่ต้อง formal NST แยกต่างหาก\n\n❌ D. Sedation ไม่ถูกต้อง ไม่มี indication สำหรับ sedation ที่ cervix 8 cm ที่ใกล้ fully dilated\n\n❌ E. Intrauterine resuscitation ไม่ถูกต้อง ไม่มี non-reassuring FHR pattern ที่ต้อง resuscitate";

reasons['NL2-2023-Q176'] = "หญิง GA 37+ สัปดาห์ labor pain fundal height 3/4 above umbilicus contraction q 2-2.5 min duration 40-50 sec moderate intensity fully dilated ruptured membrane EFM: FHR drop after uterine contraction ถาม management\n\nFully dilated + ruptured membrane + FHR drop AFTER contraction → late deceleration ซึ่งบ่งบอก uteroplacental insufficiency (fetal hypoxia)\n\nLate deceleration เกิดจาก decreased uteroplacental blood flow ขณะ contraction ทำให้ fetal hypoxemia เป็น ominous pattern ที่ต้อง intrauterine resuscitation ทันที\n\nIntrauterine resuscitation ประกอบด้วย 1) Left lateral position (ลด aortocaval compression) 2) IV fluid bolus (เพิ่ม intravascular volume) 3) Supplemental O2 (เพิ่ม maternal oxygenation) 4) Stop oxytocin (ถ้ามี) 5) Consider tocolysis (terbutaline) เพื่อลด contraction\n\n✅ A. Intrauterine resuscitation ถูกต้อง เป็น immediate management สำหรับ late deceleration\n\n❌ B. Terbutaline ไม่ถูกต้อง Terbutaline เป็นส่วนหนึ่งของ intrauterine resuscitation แต่โจทย์ถาม overall management ซึ่ง intrauterine resuscitation ครอบคลุมกว่า\n\n❌ C. Oxytocin ไม่ถูกต้อง Late decel ต้อง STOP oxytocin ไม่ใช่ให้เพิ่ม\n\n❌ D. Vacuum extraction ไม่ถูกต้อง Station ไม่ได้ระบุ อาจยังสูงเกินไป ต้อง resuscitate ก่อน\n\n❌ E. Emergency C/S ไม่ถูกต้อง ต้อง try intrauterine resuscitation ก่อน ถ้าไม่ดีขึ้นจึง C/S";

reasons['NL2-2023-Q177'] = "หญิง G4P3 GA 39 สัปดาห์ labor pain fundal height 35 cm transverse lie FHR 152 contraction q 3 min duration 50 sec cervix 5 cm effacement 80% station -3 ถาม management\n\nTransverse lie + cervix 5 cm dilated (active labor) → cannot deliver vaginally → emergency C/S\n\nTransverse lie ในผู้ป่วยที่ cervix dilated แล้ว (active labor) เป็น absolute indication สำหรับ cesarean section เพราะ 1) ทารกไม่สามารถ engage + descend ได้ 2) Risk ของ cord prolapse 3) Risk ของ uterine rupture ถ้าปล่อยให้ contract ต่อ\n\nInternal podalic version ไม่แนะนำอีกต่อไปเพราะ risk สูง (uterine rupture, cord prolapse) ยกเว้น delivery ของ second twin\n\n✅ D. Emergency C/S ถูกต้อง Transverse lie in active labor = absolute indication สำหรับ C/S\n\n❌ A. IV oxytocin ไม่ถูกต้อง Oxytocin augmentation ใน transverse lie จะเพิ่ม risk ของ uterine rupture\n\n❌ B. Observe ไม่ถูกต้อง ไม่สามารถ deliver vaginally ได้ ปล่อยต่อเสี่ยง uterine rupture\n\n❌ C. Internal podalic version ไม่ถูกต้อง ไม่แนะนำ (high risk) ยกเว้น 2nd twin delivery\n\n❌ E. Amniotomy ไม่ถูกต้อง Amniotomy ใน transverse lie เสี่ยง cord prolapse สูงมาก";

reasons['NL2-2023-Q178'] = "หญิงเพิ่งคลอด term newborn ด้วย vacuum extraction ยังมี bleeding หลัง 3rd stage (delivery ของ placenta) ตรวจพบ good uterine tone fundal height at umbilicus ถาม most likely cause\n\nPostpartum hemorrhage (PPH) + good uterine tone + vacuum delivery → ไม่ใช่ uterine atony (uterine tone ดี) → ต้องนึกถึง cause อื่น\n\n4 T's ของ PPH: Tone (atony), Tissue (retained products), Trauma (laceration), Thrombin (coagulopathy)\n\nGood uterine tone = ไม่ใช่ atony (ruled out) Vacuum extraction = risk สำหรับ vaginal/cervical laceration (trauma) จึง vaginal laceration เป็น most likely cause\n\n✅ A. Vaginal laceration ถูกต้อง Vacuum delivery + bleeding despite good tone → traumatic laceration\n\n❌ B. Uterine atony ไม่ถูกต้อง Good uterine tone = ruled out atony\n\n❌ C. Retained placenta ไม่ถูกต้อง โจทย์บอก bleeding หลัง 3rd stage = placenta delivered แล้ว\n\n❌ D. Coagulopathy ไม่ถูกต้อง Less likely เมื่อไม่มี risk factors (DIC, anticoagulant use)\n\n❌ E. Uterine inversion ไม่ถูกต้อง Uterine inversion มักมา profound hypotension + pain + visible/palpable mass ที่ vagina ไม่ใช่ typical presentation";

reasons['NL2-2023-Q179'] = "หญิง puerperium severe pain 4 ชม.ก่อน ตรวจพบ 5 cm bluish mass ที่ episiotomy wound ถาม management\n\nBluish mass ที่ episiotomy site postpartum → vulvar/perineal hematoma จาก bleeding ใน tissue planes ที่ episiotomy\n\nPerineal hematoma ที่ขนาด 5 cm + severe pain → ต้อง evacuate (incise + drain hematoma + ligate bleeding vessels + repair)\n\n✅ D. Evacuation ถูกต้อง เป็น definitive management สำหรับ perineal hematoma ที่ expanding/symptomatic\n\n❌ A. Broad spectrum ATB ไม่ถูกต้อง ATB อาจให้เป็น prophylaxis หลัง evacuation แต่ไม่ใช่ primary treatment\n\n❌ B. Cold packing ไม่ถูกต้อง Cold pack อาจช่วยลด swelling ของ small hematoma แต่ 5 cm hematoma ที่ severe pain ต้อง surgical evacuation\n\n❌ C. Aspiration ไม่ถูกต้อง Needle aspiration ของ hematoma ไม่เพียงพอ เพราะ blood clot ไม่สามารถ aspirate ได้ดี ต้อง incise + evacuate\n\n❌ E. Observation with analgesics ไม่ถูกต้อง 5 cm expanding hematoma ที่ severe pain ไม่ควร observe ต้อง evacuate";

reasons['NL2-2023-Q180'] = "เด็กหญิง 8 ขวบ vaginal bleeding ตรวจพบ Tanner stage: pubic hair II breast II ถาม diagnosis\n\nVaginal bleeding (menstruation) ที่อายุ 8 ขวบ ร่วมกับ Tanner stage PH2 B2 (เริ่มมี secondary sexual characteristics) → puberty ที่เริ่มก่อนวัย\n\nPrecocious puberty ในเด็กหญิง = การเริ่มต้นของ puberty ก่อนอายุ 8 ปี (breast development) หรือ menstruation ก่อนอายุ 10 ปี ผู้ป่วยรายนี้อายุ 8 ปี มี breast development (Tanner B2) + pubic hair (Tanner PH2) + vaginal bleeding = precocious puberty\n\n✅ B. Precocious puberty ถูกต้อง Secondary sexual development + menstruation ที่อายุ 8 ปี = precocious puberty\n\n❌ A. Early puberty ไม่ถูกต้อง ในทางการแพทย์ precocious puberty เป็น specific term สำหรับ puberty ก่อนอายุ 8 ปีในหญิง early puberty ไม่ใช่ standard medical term\n\n❌ C. Premature menarche ไม่ถูกต้อง Premature menarche = isolated vaginal bleeding โดยไม่มี other secondary sexual characteristics ผู้ป่วยรายนี้มี breast + pubic hair development ร่วมด้วย ไม่ใช่ isolated menarche\n\n❌ D. Premature pubarche ไม่ถูกต้อง = isolated pubic/axillary hair development ก่อนวัย ผู้ป่วยมี breast + menarche ร่วมด้วย ไม่ใช่ isolated pubarche\n\n❌ E. Premature thelarche ไม่ถูกต้อง = isolated breast development ก่อนวัย ผู้ป่วยมี pubic hair + menarche ร่วมด้วย ไม่ใช่ isolated thelarche";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');
  mongoose.disconnect();
}).catch(err => console.error(err.message));
