const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q181'] = "เด็กหญิง 16 ปี chronic cyclic pelvic pain ไม่เคย menstruate ตรวจภาพ pelvic exam shown ถาม diagnosis\n\nPrimary amenorrhea (ไม่เคยมี menstruation) + cyclic pelvic pain (แสดงว่ามี functioning uterus ที่สร้าง endometrium แต่เลือดออกไม่ได้) → outflow tract obstruction → imperforate hymen\n\nImperforate hymen เป็น most common obstructive anomaly ของ female reproductive tract เกิดจาก failure ของ hymen ที่จะ perforate ตามปกติ ทำให้ menstrual blood สะสมหลัง hymen (hematocolpos) เกิด cyclic pain ทุกเดือน PE จะเห็น bulging bluish membrane ที่ introitus จาก accumulated dark blood\n\n✅ A. Imperforate hymen ถูกต้อง Primary amenorrhea + cyclic pain + PE findings consistent with obstructed outflow\n\n❌ B. PCOS ไม่ถูกต้อง PCOS มี oligomenorrhea/amenorrhea แต่ไม่มี cyclic pain มี hirsutism acne obesity\n\n❌ C. Prolactinoma ไม่ถูกต้อง ทำให้ amenorrhea + galactorrhea จาก hyperprolactinemia ไม่มี cyclic pain\n\n❌ D. Anorexia ไม่ถูกต้อง ทำให้ amenorrhea จาก hypothalamic suppression ไม่มี cyclic pain มี weight loss extreme\n\n❌ E. Mullerian agenesis (MRKH) ไม่ถูกต้อง Absent uterus + absent upper vagina ทำให้ primary amenorrhea แต่ไม่มี cyclic pain เพราะไม่มี functioning endometrium";

reasons['NL2-2023-Q182'] = "หญิง 50 ขวบ hot/cold flashes cannot sleep vaginal pain during sex mood swings ทำ hysterectomy 2 ปีก่อนจาก myoma ถาม treatment\n\nMenopausal symptoms (vasomotor: hot flashes, sleep disturbance, mood changes + urogenital: dyspareunia) ในหญิงที่ทำ hysterectomy แล้ว → HRT ที่เหมาะสม\n\nHRT ในหญิงที่ไม่มี uterus (post-hysterectomy) = estrogen-only therapy ไม่ต้อง progesterone เพราะ progesterone ใช้ protect endometrium จาก estrogen-induced hyperplasia เมื่อไม่มี uterus ไม่มี endometrium ที่ต้อง protect จึงไม่ต้อง progesterone\n\n✅ B. Estrogen-only pill ถูกต้อง เป็น appropriate HRT สำหรับ post-hysterectomy menopausal symptoms\n\n❌ A. Oral combined OCP ไม่ถูกต้อง OCP มี estrogen + progesterone ไม่จำเป็นต้อง progesterone เมื่อไม่มี uterus\n\n❌ C. Progesterone-only pill ไม่ถูกต้อง Progesterone alone ไม่ช่วย vasomotor symptoms ได้ดีเท่า estrogen\n\n❌ D. Cyclic estrogen + progesterone ไม่ถูกต้อง ไม่ต้อง progesterone เมื่อไม่มี uterus\n\n❌ E. Continuous estrogen + progesterone ไม่ถูกต้อง ไม่ต้อง progesterone เมื่อไม่มี uterus";

reasons['NL2-2023-Q183'] = "หญิงมี agalactorrhea (ไม่มีน้ำนม) + amenorrhea คลอดลูกคนแรก 10 ปีก่อน ถาม investigation for diagnosis\n\nAgalactorrhea + amenorrhea → ต้องนึกถึง hyperprolactinemia เป็นอันดับแรก\n\nProlactin สูงผิดปกติทำให้ 1) Amenorrhea จาก inhibition ของ GnRH → ลด FSH/LH → anovulation 2) Galactorrhea (น้ำนมไหลผิดปกติ) แต่ในบางกรณีอาจมี agalactorrhea ถ้า prolactin สูงมากจนกด lactation paradoxically หรือ mammary gland ไม่ตอบสนอง\n\nสาเหตุ: prolactinoma (pituitary adenoma), medications (antipsychotics, metoclopramide), hypothyroidism, renal failure\n\nProlactin level เป็น initial investigation ที่สำคัญที่สุดเพื่อ confirm hyperprolactinemia\n\n✅ B. Prolactin ถูกต้อง เป็น initial investigation สำหรับ amenorrhea + galactorrhea/agalactorrhea\n\n❌ A. FSH ไม่ถูกต้อง FSH ช่วย differentiate ovarian failure (สูง) จาก hypothalamic/pituitary cause (ต่ำ) แต่ prolactin เป็น more specific initial test\n\n❌ C. Estrogen ไม่ถูกต้อง Estrogen level ไม่ให้ specific diagnosis\n\n❌ D. Thyroid function test ไม่ถูกต้อง TFT ตรวจได้แต่ prolactin เป็น primary investigation\n\n❌ E. MRI brain ไม่ถูกต้อง MRI ทำหลัง confirm hyperprolactinemia เพื่อหา prolactinoma ไม่ใช่ initial investigation";

reasons['NL2-2023-Q184'] = "หญิง 49 ขวบ obese continuous scanty vaginal bleeding 3 เดือน no HRT PE normal PAP: NILM ถาม management\n\nPerimenopausal obese woman + abnormal uterine bleeding (continuous scanty 3 เดือน) + PAP normal → ต้อง rule out endometrial pathology (hyperplasia/cancer)\n\nRisk factors สำหรับ endometrial cancer: age >45, obesity (peripheral conversion ของ androgens เป็น estrogen ใน adipose tissue), perimenopausal/postmenopausal bleeding\n\nEndometrial sampling (biopsy) เป็น gold standard investigation สำหรับ evaluate abnormal uterine bleeding ในหญิงอายุ >45 ปี หรือมี risk factors เพื่อ rule out endometrial hyperplasia/cancer\n\nPAP smear normal = cervix ปกติ ไม่ได้ evaluate endometrium\n\n✅ D. Endometrial sampling ถูกต้อง Gold standard สำหรับ evaluate endometrial pathology ในหญิง >45 + AUB + risk factors\n\n❌ A. Serum FSH, estriol ไม่ถูกต้อง FSH ช่วย confirm menopausal status แต่ไม่ rule out endometrial pathology\n\n❌ B. Oral cyclic progestin ไม่ถูกต้อง Progestin ใช้ treat AUB ได้ แต่ต้อง rule out malignancy ก่อน treat\n\n❌ C. TVS ไม่ถูกต้อง TVS ช่วย measure endometrial thickness แต่ endometrial sampling เป็น more definitive investigation ที่ให้ histological diagnosis\n\n❌ E. Hysterectomy ไม่ถูกต้อง ต้อง diagnosis ก่อน surgery ไม่ถูก";

reasons['NL2-2023-Q185'] = "หญิง 20 ขวบ swollen right vulva 3 วัน very painful walking PE: 3 cm fluctuated mass + marked tenderness ที่ right vulva ถาม management\n\nFluctuant tender vulvar mass → Bartholin gland abscess\n\nBartholin gland อยู่ที่ posterior aspect ของ labia majora (5 + 7 o'clock position) เมื่อ duct อุดตัน → Bartholin cyst ถ้า infected → Bartholin abscess\n\nFluctuation = pus collection ต้อง I&D (incision and drainage) ร่วมกับ Word catheter insertion หรือ marsupialization เพื่อป้องกัน recurrence\n\n✅ E. Incision and drainage ถูกต้อง เป็น treatment สำหรับ Bartholin abscess\n\n❌ A. Wide excision ไม่ถูกต้อง Excision สำหรับ recurrent abscess ไม่ใช่ first-line\n\n❌ B. Needle aspiration ไม่ถูกต้อง Aspiration alone มี high recurrence rate ไม่ดีเท่า I&D + Word catheter\n\n❌ C. Incision biopsy ไม่ถูกต้อง Biopsy สำหรับ suspected malignancy ใน older women (>40) ไม่ใช่ abscess treatment\n\n❌ D. Topical antibiotics ไม่ถูกต้อง ไม่เพียงพอสำหรับ abscess ที่ต้อง drainage";

reasons['NL2-2023-Q186'] = "Homogeneous white-grayish foul smell vaginal discharge + itchiness PE: contact bleeding at cervix wet smear: numerous PMNs ถาม causative etiology\n\nContact bleeding at cervix + mucopurulent discharge + numerous PMNs → cervicitis สาเหตุที่พบบ่อยที่สุดของ mucopurulent cervicitis คือ Chlamydia trachomatis ตามด้วย Neisseria gonorrhoeae\n\nContact bleeding (bleeding เมื่อสัมผัส cervix) เป็น hallmark ของ cervicitis ที่ cervical columnar epithelium อักเสบ fragile เลือดออกง่าย\n\nPMNs จำนวนมากใน wet smear บ่งบอก cervical inflammation ไม่เห็น organisms specific เช่น clue cells (BV), trichomonads, yeast\n\n✅ B. Chlamydia trachomatis ถูกต้อง Most common cause ของ mucopurulent cervicitis with contact bleeding\n\n❌ A. Gardnerella vaginalis ไม่ถูกต้อง ทำให้ BV ที่มี homogeneous gray discharge + fishy odor แต่ไม่ทำให้ contact bleeding ที่ cervix BV มี clue cells ใน wet smear\n\n❌ C. Trichomonas vaginalis ไม่ถูกต้อง ทำให้ vaginitis with frothy greenish-yellow discharge + strawberry cervix wet smear จะเห็น motile flagellated organisms\n\n❌ D. Candida albicans ไม่ถูกต้อง ทำให้ thick white curd-like discharge + erythematous vulva/vagina wet smear เห็น pseudohyphae/budding yeast\n\n❌ E. Neisseria gonorrhoeae ไม่ถูกต้อง ทำให้ cervicitis ได้เช่นกัน แต่ Chlamydia พบบ่อยกว่า Gonorrhea 3-5 เท่า ถ้าโจทย์ไม่มี specific clue สำหรับ Gonorrhea (เช่น intracellular gram-negative diplococci) → Chlamydia เป็น answer";

reasons['NL2-2023-Q187'] = "หญิง 25 ขวบ yellowish vaginal discharge 5 วัน PE: mucopurulent discharge + contact bleeding at cervix no uterine/adnexal motion tenderness wet smear: numerous PMN without organisms ถาม management\n\nMucopurulent cervicitis + contact bleeding + PMN without visible organisms + no PID (no motion tenderness) → Chlamydia cervicitis → treatment ด้วย doxycycline\n\nDoxycycline 100 mg BID x 7 วัน เป็น first-line treatment สำหรับ Chlamydia ตาม CDC STI guidelines (2021) Alternative: azithromycin 1g single dose\n\n✅ C. Doxycycline ถูกต้อง First-line treatment สำหรับ Chlamydia cervicitis\n\n❌ A. Ceftriaxone ไม่ถูกต้อง ใช้สำหรับ Gonorrhea ไม่ใช่ Chlamydia\n\n❌ B. Metronidazole ไม่ถูกต้อง ใช้สำหรับ BV + Trichomonas ไม่ใช่ Chlamydia\n\n❌ D. Ofloxacin ไม่ถูกต้อง Fluoroquinolone เคยใช้สำหรับ Chlamydia แต่ปัจจุบันไม่ใช่ first-line\n\n❌ E. Clindamycin ไม่ถูกต้อง ใช้สำหรับ BV (alternative) ไม่ใช่ Chlamydia";

reasons['NL2-2023-Q188'] = "หญิง 32 ขวบ sexually active odorous vaginal discharge + pruritus 1 สัปดาห์ ไม่ดีขึ้นด้วย OTC medication PE: excoriated vulva erythematous vaginal mucosa frothy watery greyish discharge inflamed cervix ถาม causative organism\n\nFrothy watery discharge + erythematous vaginal mucosa + pruritus + excoriated vulva + inflamed cervix → Trichomonas vaginalis\n\nTrichomonas vaginalis เป็น flagellated protozoan ที่ทำให้ vaginitis + cervicitis อาการ classic ได้แก่ frothy greenish-yellow/grayish discharge, foul odor, pruritus, dysuria, strawberry cervix (colpitis macularis) วินิจฉัยด้วย wet mount (motile flagellated organisms) หรือ NAAT\n\nKey differentiating features: \"frothy\" discharge เป็น hallmark ของ Trichomonas ต่างจาก BV (homogeneous thin) และ Candida (thick curd-like)\n\n✅ B. Trichomonas vaginalis ถูกต้อง Frothy discharge + erythematous vagina + pruritus + inflamed cervix\n\n❌ A. Gardnerella vaginalis ไม่ถูกต้อง BV มี thin homogeneous discharge ไม่ frothy ไม่ค่อย pruritic ไม่ erythematous\n\n❌ C. Neisseria gonorrhoeae ไม่ถูกต้อง Gonorrhea ทำให้ mucopurulent cervicitis ไม่ใช่ frothy vaginitis\n\n❌ D. Chlamydia trachomatis ไม่ถูกต้อง ทำให้ mucopurulent cervicitis มักไม่ค่อยมี vaginal symptoms เด่น\n\n❌ E. Ureaplasma urealyticum ไม่ถูกต้อง ทำให้ urethritis/cervicitis ที่ mild ไม่ทำให้ frothy discharge";

reasons['NL2-2023-Q189'] = "หญิง pregnant มี bacterial vaginosis (BV) ถาม treatment\n\nBV ใน pregnancy ต้อง treat เพราะ associated กับ preterm labor, PPROM, chorioamnionitis\n\nFirst-line treatment สำหรับ BV ใน pregnancy คือ metronidazole (oral 500 mg BID x 7 วัน หรือ vaginal gel) Metronidazole เป็น nitroimidazole ที่ effective ต่อ anaerobic bacteria ที่เป็นสาเหตุของ BV (Gardnerella, Atopobium, Prevotella) CDC classifies metronidazole เป็น safe ใน pregnancy (Category B)\n\n✅ A. Metronidazole ถูกต้อง First-line treatment สำหรับ BV ใน pregnancy\n\n❌ B. Doxycycline ไม่ถูกต้อง Contraindicated ใน pregnancy (Category D) ทำให้ teeth discoloration + bone growth inhibition ในทารก\n\n❌ C. Clindamycin ไม่ถูกต้อง Clindamycin เป็น alternative สำหรับ BV แต่ metronidazole เป็น first-line\n\n❌ D. Azithromycin ไม่ถูกต้อง ไม่ใช่ standard treatment สำหรับ BV\n\n❌ E. Amoxicillin ไม่ถูกต้อง ไม่ effective สำหรับ BV เพราะ BV เป็น polymicrobial anaerobic infection";

reasons['NL2-2023-Q190'] = "ชาย 58 ขวบ chronic elbow pain 3 เดือน worse lifting heavy objects aggravated by resisting wrist flexion right elbow tender + mildly swollen ถาม diagnosis\n\nChronic medial elbow pain + aggravated by resisting wrist flexion → medial epicondylitis (golfer's elbow)\n\nMedial epicondylitis เกิดจาก overuse/repetitive strain ของ flexor-pronator muscle group ที่ origin จาก medial epicondyle ของ humerus ทำให้ tendinopathy ของ common flexor tendon อาการปวดที่ medial epicondyle แย่ลงเมื่อ resisted wrist flexion + forearm pronation\n\n✅ B. Medial epicondylitis ถูกต้อง Pain aggravated by resisted wrist flexion = pathognomonic\n\n❌ A. Pulled elbow (nursemaid's elbow) ไม่ถูกต้อง เป็น radial head subluxation ในเด็ก 1-4 ปี ไม่ใช่ผู้ใหญ่\n\n❌ C. Olecranon bursitis ไม่ถูกต้อง มี swelling ที่ posterior elbow (olecranon) ไม่ aggravate by resisted wrist flexion\n\n❌ D. Myofascial pain ไม่ถูกต้อง มี trigger points ใน muscle belly ไม่ specific ที่ medial epicondyle\n\n❌ E. OA elbow ไม่ถูกต้อง OA มี joint stiffness, crepitus, reduced ROM ไม่ aggravate specifically by resisted wrist flexion";

reasons['NL2-2023-Q191'] = "หญิง 39 ขวบ left elbow pain ที่ medial epicondyle worse resisting pronation ไม่ aggravated by passive motion ถาม diagnosis\n\nMedial epicondyle pain + worse with resisted pronation + not aggravated by passive motion → medial epicondylitis (golfer's elbow)\n\nMedial epicondylitis มี pain ที่ medial epicondyle ที่แย่ลงเมื่อ active/resisted movements (flexion + pronation) แต่ passive ROM มักปกติเพราะเป็น tendinopathy ไม่ใช่ joint pathology\n\n✅ B. Golfer's elbow ถูกต้อง Medial epicondyle pain + resisted pronation aggravates + passive motion OK\n\n❌ A. Tennis elbow ไม่ถูกต้อง Tennis elbow = lateral epicondylitis ปวดที่ lateral epicondyle aggravated by resisted wrist extension\n\n❌ C. Olecranon bursitis ไม่ถูกต้อง ปวด + บวมที่ posterior elbow ไม่เกี่ยวกับ pronation\n\n❌ D. Reactive arthritis ไม่ถูกต้อง มี joint inflammation (swelling, warmth) ที่ joint space ไม่ใช่ epicondyle + มี associated urethritis, conjunctivitis\n\n❌ E. Rheumatoid arthritis ไม่ถูกต้อง RA มี symmetric joint inflammation + morning stiffness >30 min + multiple joints ไม่ใช่ isolated epicondyle pain";

reasons['NL2-2023-Q192'] = "เด็กชาย 6 ขวบ สุขภาพดี fever + painful left elbow 3 วัน holds elbow in mid-flexion refuses to move warm erythematous edematous passive tenderness exacerbated by movement BT 39 ถาม investigation\n\nChild + fever + painful swollen joint + refuses to move + warm/erythematous → septic arthritis vs osteomyelitis จนกว่าจะ prove otherwise\n\nInitial investigation สำหรับ acute painful joint ในเด็กที่มี fever คือ X-ray เพื่อ 1) ดู joint effusion (widened joint space, fat pad displacement) 2) Rule out fracture 3) ดู bony changes (osteomyelitis มี periosteal reaction/lytic lesion ในระยะหลัง)\n\nX-ray เป็น initial investigation ที่ทำง่าย เร็ว ราคาถูก ให้ baseline information ก่อน proceed ไป further investigation (US, MRI, joint aspiration)\n\n✅ C. X-ray plain film left elbow (AP, Lateral) ถูกต้อง Initial investigation สำหรับ acute painful joint ในเด็ก\n\n❌ A. ESR, CRP ไม่ถูกต้อง Inflammatory markers ช่วย support infection แต่ไม่ให้ structural information ควร X-ray ก่อน\n\n❌ B. ASO titer ไม่ถูกต้อง ใช้สำหรับ post-streptococcal reactive arthritis/ARF ไม่ใช่ initial investigation สำหรับ acute septic joint\n\n❌ D. Ultrasound elbow ไม่ถูกต้อง US ช่วยเห็น effusion ได้ดี แต่ X-ray เป็น standard initial imaging\n\n❌ E. Arthrocentesis ไม่ถูกต้อง Joint aspiration เป็น definitive diagnostic procedure สำหรับ septic arthritis แต่ต้อง initial imaging ก่อนเพื่อ rule out fracture + guide approach";

reasons['NL2-2023-Q193'] = "ชาย 25 ขวบ left arm pain หลัง motorcycle accident ไม่สามารถ extend left wrist X-ray: fracture 1/3 distal shaft left humerus ถาม structure ที่ injured\n\nFracture mid-distal shaft of humerus + wrist drop (cannot extend wrist) → radial nerve injury\n\nRadial nerve วิ่งอยู่ใน radial (spiral) groove ที่ posterior aspect ของ mid-shaft humerus ทำให้ vulnerable ต่อ injury เมื่อมี humeral shaft fracture โดยเฉพาะ mid-distal third\n\nRadial nerve innervates wrist extensors (extensor carpi radialis longus/brevis, extensor digitorum) + finger extensors + thumb extensors เมื่อ injured จะเกิด wrist drop (ไม่สามารถ extend wrist) + finger drop + loss of sensation ที่ dorsal hand (anatomical snuffbox area)\n\n✅ B. Radial nerve ถูกต้อง Humeral shaft fracture + wrist drop = classic radial nerve injury\n\n❌ A. Ulnar nerve ไม่ถูกต้อง Ulnar nerve injury มี claw hand (ring + little finger flexion), loss of finger abduction/adduction, numbness ที่ ulnar side ของ hand injured ที่ medial epicondyle ไม่ใช่ humeral shaft\n\n❌ C. Axillary nerve ไม่ถูกต้อง Axillary nerve injured ใน anterior shoulder dislocation + surgical neck fracture ของ humerus ทำให้ deltoid weakness + loss of sensation ที่ regimental badge area\n\n❌ D. Median nerve ไม่ถูกต้อง Median nerve injury มี loss of thumb opposition + ape hand + loss of sensation ที่ palmar side ของ lateral 3.5 fingers injured ที่ supracondylar fracture (proximal) หรือ carpal tunnel\n\n❌ E. Musculocutaneous nerve ไม่ถูกต้อง Injured ที่ upper arm ทำให้ biceps weakness (cannot flex forearm) + loss of lateral forearm sensation ไม่ใช่ wrist drop";

reasons['NL2-2023-Q194'] = "เด็กมี foot deformity ตามรูป ถาม diagnosis\n\nFoot deformity ในเด็กที่มีลักษณะ CAVE: Cavus (high arch) + Adductus (forefoot medial deviation) + Varus (hindfoot inversion) + Equinus (plantarflexion/toe walking) → congenital clubfoot (talipes equinovarus)\n\nClubfoot เป็น congenital deformity ที่พบ 1:1000 live births ชายมากกว่าหญิง 2:1 50% bilateral สาเหตุ multifactorial (genetic + environmental) Treatment: Ponseti method (serial casting) เป็น gold standard เริ่มทำตั้งแต่ 1-2 สัปดาห์หลังคลอด\n\n✅ A. Congenital clubfoot ถูกต้อง CAVE deformity เป็น pathognomonic\n\n❌ B. Calcaneovalgus ไม่ถูกต้อง ตรงข้ามกับ clubfoot — เท้า dorsiflexed + everted (hindfoot valgus) มักเป็น positional deformity ที่หายเอง\n\n❌ C. Metatarsus adductus ไม่ถูกต้อง มีแค่ forefoot adduction ไม่มี equinus + varus ของ hindfoot\n\n❌ D. Pes planus (flatfoot) ไม่ถูกต้อง Flat medial longitudinal arch ไม่มี equinus + varus\n\n❌ E. Congenital vertical talus (CVT) ไม่ถูกต้อง Rocker-bottom foot ที่มี rigid flatfoot เป็นตรงข้ามกับ clubfoot (equinus ของ hindfoot + dorsiflexion ของ forefoot)";

reasons['NL2-2023-Q195'] = "หญิง 68 ขวบ chronic knee pain 10 ปี morning stiffness <10 min genu varum crepitation both knees ถาม diagnosis\n\nChronic bilateral knee pain 10 ปี + morning stiffness <30 min + genu varum (bow legs) + crepitation → osteoarthritis (OA)\n\nOA เป็น degenerative joint disease ที่พบบ่อยที่สุดในผู้สูงอายุ เกิดจาก cartilage degeneration + subchondral bone changes + osteophyte formation อาการหลักคือ joint pain ที่ worse with activity + better with rest, morning stiffness <30 min (ต่างจาก RA ที่ >60 min), crepitus, bony enlargement Genu varum (medial compartment narrowing) เป็น common deformity ใน knee OA\n\n✅ B. OA ถูกต้อง Chronic joint pain + short morning stiffness + crepitus + genu varum = classic OA\n\n❌ A. Septic arthritis ไม่ถูกต้อง มี acute onset + fever + hot swollen joint ไม่ใช่ chronic 10 ปี\n\n❌ C. RA ไม่ถูกต้อง RA มี morning stiffness >60 min + symmetric small joint involvement + soft tissue swelling ต่างจาก OA\n\n❌ D. Gouty arthritis ไม่ถูกต้อง Gout มี acute episodic monoarthritis (โดยเฉพาะ 1st MTP) ไม่ใช่ chronic bilateral knee pain\n\n❌ E. Lateral collateral ligament injury ไม่ถูกต้อง Ligament injury เป็น acute traumatic ไม่ใช่ chronic degenerative";

reasons['NL2-2023-Q196'] = "ชาย back pain radiating to right leg worse bending over SLR positive ถาม diagnosis\n\nBack pain + radiculopathy (radiating to leg) + worse with flexion (bending) + positive SLR (Straight Leg Raise test) → herniated nucleus pulposus (HNP/disc herniation)\n\nHNP เกิดจาก nucleus pulposus herniate ผ่าน annulus fibrosus ไปกดทับ nerve root ทำให้ radicular pain ที่ radiates ตาม dermatome ของ nerve ที่ถูกกด L4-L5 (L5 root) หรือ L5-S1 (S1 root) พบบ่อยที่สุด\n\nPositive SLR test คือ pain reproduced เมื่อ raise leg 30-70 degrees ใน supine position เป็น sensitive test สำหรับ L4-S1 nerve root compression sensitivity 91%\n\n✅ A. Herniated nucleus pulposus ถูกต้อง Radicular pain + positive SLR + worse with flexion = classic HNP\n\n❌ B. Spondylolisthesis ไม่ถูกต้อง Anterior slippage ของ vertebra มี back pain ที่ worse with extension ไม่ใช่ flexion SLR อาจ positive ได้แต่ไม่ใช่ primary feature\n\n❌ C. Spinal stenosis ไม่ถูกต้อง มี neurogenic claudication (leg pain worse with walking/standing better with sitting/flexion) ต่างจาก HNP ที่ worse with flexion\n\n❌ D. Ankylosing spondylitis ไม่ถูกต้อง มี inflammatory back pain (worse at rest/morning, better with exercise) + sacroiliitis + young male ไม่มี radicular pattern\n\n❌ E. Mechanical low back pain ไม่ถูกต้อง Mechanical LBP ไม่มี radiculopathy (no leg radiation) + negative SLR";

reasons['NL2-2023-Q197'] = "ชาย 60 ขวบ right knee pain + swelling + positive patellar ballottement joint aspiration: rhomboid-shaped crystals ถาม management\n\nJoint effusion + rhomboid-shaped crystals → pseudogout (calcium pyrophosphate deposition disease/CPPD)\n\nRhomboid-shaped crystals ที่ weakly positive birefringent ภายใต้ polarized microscopy เป็น CPPD crystals ต่างจาก gout ที่มี needle-shaped negatively birefringent monosodium urate crystals\n\nTreatment ของ acute pseudogout คือ NSAIDs หรือ colchicine หรือ intra-articular steroid injection NSAIDs เป็น first-line ถ้าไม่มี contraindications\n\nCelecoxib เป็น selective COX-2 inhibitor ที่มี GI side effects น้อยกว่า non-selective NSAIDs เหมาะสำหรับผู้สูงอายุ\n\n✅ C. Celecoxib ถูกต้อง NSAIDs เป็น first-line สำหรับ acute pseudogout celecoxib เป็น COX-2 selective ที่ safe กว่าใน elderly\n\n❌ A. Cold compression ไม่ถูกต้อง Adjunctive measure ไม่ใช่ primary pharmacological treatment\n\n❌ B. Ketoprofen gel ไม่ถูกต้อง Topical NSAIDs ไม่เพียงพอสำหรับ moderate-severe joint inflammation\n\n❌ D. Colchicine ไม่ถูกต้อง Colchicine ใช้สำหรับ acute gout เป็นหลัก แม้ใช้ใน pseudogout ได้แต่ NSAIDs เป็น first-line\n\n❌ E. Tramadol ไม่ถูกต้อง Opioid analgesic ที่ช่วยปวดแต่ไม่ลด inflammation ไม่ใช่ first-line";

reasons['NL2-2023-Q198'] = "ผู้ป่วย joint pain 4 วัน เริ่มที่ right ankle 3 วันก่อน แล้วย้ายไป left knee joints มี signs of inflammation ถาม management\n\nMigratory polyarthritis (ย้ายจากข้อหนึ่งไปอีกข้อ) + signs of inflammation → gonococcal arthritis (disseminated gonococcal infection/DGI)\n\nMigratory/additive arthritis เป็น key feature ของ DGI — ปวดข้อที่ย้ายจากข้อหนึ่งไปอีกข้อภายในวัน ต่างจาก reactive arthritis (additive, asymmetric), gout (monoarticular, acute), RA (symmetric, bilateral)\n\nDGI เกิดจาก Neisseria gonorrhoeae ที่แพร่จาก mucosal infection (genitourinary/pharyngeal) เข้า bloodstream มี 2 phases: bacteremic phase (fever, rash, tenosynovitis, migratory arthralgia) และ septic arthritis phase (purulent monoarthritis)\n\nTreatment: antibiotics (ceftriaxone 1g IM/IV daily) เป็น drug of choice\n\n✅ C. Antibiotics ถูกต้อง Migratory arthritis = suspect infectious (gonococcal) ต้อง antibiotics\n\n❌ A. NSAIDs ไม่ถูกต้อง NSAIDs ช่วยปวดแต่ไม่ treat infection migratory pattern ชี้ infection\n\n❌ B. Colchicine ไม่ถูกต้อง ใช้สำหรับ gout ซึ่งเป็น monoarticular ไม่ migrate\n\n❌ D. Cold compression ไม่ถูกต้อง Adjunctive ไม่ treat infection\n\n❌ E. Intra-articular steroid ไม่ถูกต้อง Steroid injection ใน septic joint จะทำให้ infection แย่ลง ห้ามให้เมื่อสงสัย infection";

reasons['NL2-2023-Q199'] = "เด็ก 4 ขวบ impaired night vision + diarrhea ตรวจพบ triangular dry whitish foamy-appearing lesions ที่ eyes (Bitot's spots) + follicular keratosis ที่ elbows + knees ถาม most useful investigation\n\nNight blindness (nyctalopia) + Bitot's spots + follicular keratosis → vitamin A deficiency (xerophthalmia)\n\nVitamin A (retinol) เป็น fat-soluble vitamin ที่จำเป็นสำหรับ 1) vision (retinal = component ของ rhodopsin ใน rod cells) 2) epithelial cell differentiation 3) immune function Deficiency มีหลายระดับตาม WHO classification: night blindness (XN) → conjunctival xerosis → Bitot's spots (X1B) → corneal xerosis → corneal ulceration → keratomalacia\n\nBitot's spots เป็น pathognomonic finding ของ vitamin A deficiency = triangular foamy white deposits บน conjunctiva จาก keratinized epithelium Follicular keratosis (keratosis pilaris-like) ที่ extensor surfaces เป็น skin manifestation ของ vitamin A deficiency\n\nSerum retinol level เป็น most useful investigation เพื่อ confirm vitamin A deficiency (normal 30-70 mcg/dL, deficient <20 mcg/dL)\n\n✅ C. Serum retinol ถูกต้อง Gold standard investigation สำหรับ confirm vitamin A deficiency\n\n❌ A. EEG ไม่ถูกต้อง ไม่เกี่ยวข้องกับ vitamin A deficiency\n\n❌ B. Slit lamp examination ไม่ถูกต้อง Slit lamp ช่วยดู corneal involvement ใน xerophthalmia แต่ไม่ใช่ diagnostic investigation สำหรับ vitamin A status\n\n❌ D. Ocular tonometry ไม่ถูกต้อง ใช้วัด intraocular pressure สำหรับ glaucoma ไม่เกี่ยว\n\n❌ E. Skin biopsy ไม่ถูกต้อง ไม่จำเป็นเมื่อ clinical diagnosis ชัดเจน serum retinol เป็น less invasive + more specific";

reasons['NL2-2023-Q200'] = "เด็กมี orthotropia (ตาตรง) + ptosis ถาม complication ถ้าไม่รักษา\n\nPtosis ในเด็กที่มี orthotropia (ตาไม่เหล่) → ถ้าปล่อยไว้ไม่รักษา → deprivation amblyopia\n\nPtosis ที่รุนแรงพอจะบัง visual axis (แกนการมองเห็น) ในเด็กที่อยู่ใน critical period ของ visual development (0-7 ปี) จะทำให้ retina ไม่ได้รับ formed image ที่ชัดเจน สมองจึง suppress สัญญาณจากตาข้างนั้น เกิด deprivation amblyopia (ตาขี้เกียจจากการถูกบดบัง)\n\nDeprivation amblyopia เป็น most severe form ของ amblyopia เพราะสมองถูกตัดขาดจาก visual input โดยสิ้นเชิง ยิ่งปล่อยนานยิ่งแก้ไขยาก\n\n✅ A. Deprivation amblyopia ถูกต้อง Ptosis บัง visual axis ในเด็ก → visual deprivation → amblyopia\n\n❌ B. Cataract ไม่ถูกต้อง Ptosis ไม่ทำให้เกิด cataract\n\n❌ C. Glaucoma ไม่ถูกต้อง ไม่เกี่ยวกับ ptosis\n\n❌ D. Strabismus ไม่ถูกต้อง โจทย์ระบุ orthotropia (ตาตรง) ptosis ไม่ทำให้เกิด strabismus โดยตรง\n\n❌ E. Optic atrophy ไม่ถูกต้อง Ptosis ไม่ทำลาย optic nerve เป็น mechanical obstruction ที่ eyelid level";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');
  mongoose.disconnect();
}).catch(err => console.error(err.message));
