const mongoose = require('mongoose');
const uri = 'mongodb+srv://doadmin:461KbE859Fhe02AL@db-mongodb-sgp1-medninja-57a9a153.mongo.ondigitalocean.com/nlex?tls=true&authSource=admin';
const reasons = {};

reasons['NL2-2023-Q211'] = "ชาย 78 ขวบ มา health check-up ทำ ADL ได้เอง ลูกชายกังวลว่าเป็น Alzheimer เพราะไม่เข้าใจสิ่งที่คนในครอบครัวพูด PE: BP 130/80 no impacted cerumen otherwise normal ถาม investigation\n\nผู้สูงอายุที่มีปัญหาเข้าใจคำพูด (comprehension difficulty) + ทำ ADL ได้เอง + ไม่มี cerumen impaction → presbycusis (age-related hearing loss) มากกว่า dementia\n\nPresbycusis เป็น sensorineural hearing loss จาก aging ของ cochlea + auditory nerve พบบ่อยในผู้สูงอายุ เริ่มจาก high-frequency hearing loss ทำให้ difficulty understanding speech โดยเฉพาะใน noisy environment อาจถูกเข้าใจผิดว่าเป็น cognitive decline/dementia\n\n✅ D. Audiometry ถูกต้อง เป็น investigation ที่เหมาะสมที่สุดเพื่อ evaluate hearing loss ก่อนที่จะสงสัย dementia\n\n❌ A. Reassure as normal aging ไม่ถูกต้อง Hearing loss ต้อง evaluate + treat (hearing aid) ไม่ควร dismiss\n\n❌ B. TMSE test ไม่ถูกต้อง Cognitive screening อาจทำเพิ่ม แต่ต้อง rule out hearing loss ก่อน เพราะ hearing loss ทำให้ TMSE score ต่ำปลอม\n\n❌ C. Geriatric depression test ไม่ถูกต้อง ไม่มี depressive symptoms ที่ชัดเจนจากโจทย์\n\n❌ E. CT brain ไม่ถูกต้อง ไม่มี focal neurological signs หรือ rapid cognitive decline ที่ต้อง CT";

reasons['NL2-2023-Q212'] = "หญิง 60 ขวบ left side epistaxis 2 ครั้ง/วัน 3 วัน PE stable vitals minimal blood oozing จาก left anterior nasal septum normal nasal mucosa no discharge ถาม management\n\nAnterior epistaxis (จาก anterior nasal septum = Kiesselbach's/Little's area) + minimal oozing + visible bleeding point → cauterization\n\nAnterior epistaxis ที่เห็น bleeding point ชัดเจนที่ anterior septum (Kiesselbach's plexus) สามารถ cauterize ได้ด้วย silver nitrate stick หรือ electrocautery เพื่อ seal bleeding vessel ป้องกัน recurrence\n\n✅ C. Cauterization ถูกต้อง Visible anterior bleeding point ที่ minimal oozing → chemical/electrical cauterization\n\n❌ A. Antibiotic ointment ไม่ถูกต้อง ใช้หลัง cauterization เพื่อ prevent crusting + infection ไม่ใช่ primary treatment\n\n❌ B. Cold packing ไม่ถูกต้อง Cold compress ช่วยลด bleeding ชั่วคราว ไม่ definitive\n\n❌ D. Anterior nasal packing ไม่ถูกต้อง Packing ใช้เมื่อ cauterization ไม่ได้/ไม่เห็น bleeding point/bleeding มาก ผู้ป่วยรายนี้ minimal oozing + visible bleeding point cauterize ง่ายกว่า\n\n❌ E. Posterior nasal packing ไม่ถูกต้อง ใช้สำหรับ posterior epistaxis ที่ anterior packing ไม่สามารถหยุดเลือดได้";

reasons['NL2-2023-Q213'] = "เด็กชาย 5 ขวบ ALL มา epistaxis 50 mL direct pressure ไม่หยุดเลือด ถาม management\n\nALL (leukemia) + epistaxis 50 mL + direct pressure ล้มเหลว → significant epistaxis ในผู้ป่วย thrombocytopenic\n\nLeukemia ทำให้ thrombocytopenia จาก bone marrow infiltration + chemotherapy ทำให้ bleeding tendency ผู้ป่วยที่ direct pressure (first-line สำหรับ epistaxis) ไม่สามารถหยุดเลือดได้ ต้อง escalate treatment\n\nAnterior nasal packing เป็น next step เมื่อ direct pressure ล้มเหลว packing ใช้ ribbon gauze หรือ nasal tampon สอดเข้าไปใน nasal cavity กดอัด bleeding site + promote hemostasis\n\n✅ B. Anterior nasal packing ถูกต้อง Next step เมื่อ direct pressure ล้มเหลว\n\n❌ A. Cold packing ไม่ถูกต้อง Cold alone ไม่เพียงพอเมื่อ direct pressure ล้มเหลว\n\n❌ C. Posterior nasal packing ไม่ถูกต้อง ใช้เมื่อ anterior packing ล้มเหลว ไม่ใช่ first step\n\n❌ D. Cauterization ไม่ถูกต้อง ใน thrombocytopenic patient cauterization อาจไม่ effective และ may worsen bleeding ที่ cauterized site packing เป็น safer option\n\n❌ E. Platelet transfusion alone ไม่ถูกต้อง Platelet transfusion อาจจำเป็น (ถ้า platelet ต่ำมาก) แต่ต้อง local hemostasis (packing) ร่วมด้วย platelet alone ไม่หยุดเลือดได้ทันที";

reasons['NL2-2023-Q214'] = "เด็กหญิง 12 ขวบ left nasal obstruction + mucoid discharge 2 เดือน anterior rhinoscopy: no mass posterior rhinoscopy: glistening mass fully obstructing with discharge Valsalva maneuver ไม่เปลี่ยนขนาด ถาม diagnosis\n\nUnilateral nasal obstruction + mucoid discharge + posterior nasal mass (glistening) + no change with Valsalva → antrochoanal polyp\n\nAntrochoanal polyp เกิดจาก maxillary sinus แล้วยืดออกผ่าน accessory ostium ไป posterior choana เป็น benign solitary polyp ที่พบบ่อยในเด็กและวัยรุ่น ลักษณะ glistening (เงาวาว) smooth surface ดูเหมือน cluster of grapes\n\nValsalva maneuver ไม่เปลี่ยนขนาด = ไม่ใช่ meningocele/encephalocele ที่จะ enlarge เมื่อ increase intracranial pressure (positive Furstenberg test)\n\n✅ D. Antrochoanal polyp ถูกต้อง Unilateral posterior nasal mass + glistening + child + no change with Valsalva\n\n❌ A. Foreign body ไม่ถูกต้อง FB มัก unilateral foul-smelling purulent discharge + visible on anterior rhinoscopy ไม่ใช่ glistening mass ที่ posterior choana\n\n❌ B. Glioma ไม่ถูกต้อง Nasal glioma เป็น congenital midline nasal mass มักเห็นที่ nasal bridge ไม่ใช่ posterior choana\n\n❌ C. Meningocele ไม่ถูกต้อง Meningocele จะ enlarge with Valsalva (positive Furstenberg test) ผู้ป่วยรายนี้ไม่เปลี่ยนขนาด\n\n❌ E. Dermoid cyst ไม่ถูกต้อง เป็น congenital midline nasal mass ที่ external nose ไม่ใช่ posterior choana";

reasons['NL2-2023-Q215'] = "หญิง 50 ขวบ DM facial pain X-ray: increased opacity maxillary antrum PE: pale nasal mucosa nasal obstruction purulent discharge ถาม next step management\n\nDM + facial pain + maxillary sinus opacity + purulent nasal discharge → acute/chronic sinusitis ใน diabetic patient ต้อง evaluate สำหรับ fungal sinusitis (invasive fungal sinusitis) ซึ่งเป็น life-threatening condition ใน immunocompromised/DM patients\n\nCT scan เป็น next step เพื่อ 1) Evaluate extent ของ sinus disease 2) Look for bony erosion (suggestive of invasive fungal sinusitis) 3) Evaluate extension ไปยัง orbit/intracranial 4) Guide surgical planning\n\n✅ C. CT ถูกต้อง Essential investigation ใน DM patient กับ sinusitis เพื่อ rule out invasive fungal sinusitis + evaluate extent\n\n❌ A. Irrigation ไม่ถูกต้อง Sinus irrigation อาจทำได้แต่ต้อง evaluate extent ด้วย CT ก่อน โดยเฉพาะใน DM ที่เสี่ยง invasive fungal disease\n\n❌ B. Nasal swab culture ไม่ถูกต้อง Nasal swab ไม่ reflect sinus pathogen accurately ต้อง endoscopic-guided culture ถ้าจำเป็น\n\n❌ D. MRI ไม่ถูกต้อง MRI ดี กว่า CT สำหรับ soft tissue detail แต่ CT เป็น preferred initial imaging สำหรับ sinus disease เพราะเห็น bony anatomy ดีกว่า\n\n❌ E. Antifungal drug ไม่ถูกต้อง ต้อง diagnosis ก่อน treat ยังไม่ confirm ว่าเป็น fungal sinusitis";

reasons['NL2-2023-Q216'] = "เด็กชาย 5 ขวบ watery rhinorrhea sneezing eye itching 5 วัน/สัปดาห์ 3 เดือน ขาดเรียนบ่อย BT 37 bilateral inferior turbinate swelling ถาม investigation\n\nWatery rhinorrhea + sneezing + eye itching + >4 วัน/สัปดาห์ + >4 สัปดาห์ + affects school = moderate-severe persistent allergic rhinitis ตาม ARIA classification\n\nIntranasal corticosteroid เป็น first-line treatment สำหรับ moderate-severe persistent allergic rhinitis ตาม ARIA guidelines เป็น most effective monotherapy ที่ลดทุกอาการ (congestion, rhinorrhea, sneezing, itching, ocular symptoms)\n\n✅ B. Intranasal corticosteroids ถูกต้อง First-line สำหรับ moderate-severe persistent allergic rhinitis\n\n❌ A. Inhaled corticosteroids ไม่ถูกต้อง Inhaled (via MDI) ใช้สำหรับ lower airway (asthma) ไม่ใช่ nasal symptoms\n\n❌ C. Leukotriene receptor antagonist ไม่ถูกต้อง Montelukast เป็น add-on therapy ไม่ใช่ first-line สำหรับ allergic rhinitis ตาม ARIA\n\n❌ D. Oral prednisone ไม่ถูกต้อง Systemic steroid สงวนไว้สำหรับ severe symptoms ที่ไม่ตอบสนองต่อ topical ไม่ใช่ first-line\n\n❌ E. Salbutamol MDI ไม่ถูกต้อง ใช้สำหรับ bronchospasm/asthma ไม่ช่วย nasal symptoms";

reasons['NL2-2023-Q217'] = "เด็กชาย 3 ขวบ สุขภาพดี snoring 4 เดือน RR 25 tonsil 3+ ทั้งสองข้าง pale inferior turbinate ถาม management\n\nSnoring + tonsil 3+ (significantly enlarged) + pale turbinate (allergic rhinitis) ในเด็ก 3 ขวบ ที่ไม่มี obstructive sleep apnea symptoms (no apnea, desaturation, failure to thrive)\n\nIntranasal corticosteroid เป็น first-line medical treatment ที่สามารถ reduce adenotonsillar size ได้ 10-20% + reduce nasal congestion จาก allergic rhinitis ทำให้ airway patency ดีขึ้น ลด snoring ได้โดยไม่ต้อง surgery เป็น trial of medical therapy ก่อน adenotonsillectomy\n\n✅ D. Intranasal corticosteroid ถูกต้อง First-line medical trial ก่อนพิจารณา surgery\n\n❌ A. Topical pseudoephedrine ไม่ถูกต้อง Decongestant ไม่แนะนำใช้ long-term ใน children เพราะ rhinitis medicamentosa + systemic effects\n\n❌ B. Oral pseudoephedrine ไม่ถูกต้อง Oral decongestant ไม่แนะนำใน children < 6 ปี เพราะ side effects (insomnia, agitation)\n\n❌ C. Oral chlorpheniramine ไม่ถูกต้อง First-gen antihistamine ช่วยลด rhinorrhea + sneezing แต่ไม่ลด congestion/tonsillar size มี sedation + anticholinergic side effects\n\n❌ E. Nasal irrigation ไม่ถูกต้อง Saline irrigation เป็น adjunctive measure ไม่ลด tonsillar hypertrophy";

reasons['NL2-2023-Q218'] = "หญิง 40 ขวบ hoarseness ทันทีหลังตื่นจาก GA สำหรับ cholecystectomy ถาม cause\n\nHoarseness immediately after GA (ทันทีหลังถอด tube) → intubation-related injury\n\nDifferential ของ hoarseness หลัง GA: 1) Cricoarytenoid joint dislocation (จาก traumatic intubation/extubation) 2) Vocal cord paralysis (จาก recurrent laryngeal nerve injury - พบบ่อยหลัง thyroid surgery) 3) Intubation granuloma (มักเกิดหลังหลายสัปดาห์) 4) Laryngeal edema\n\nCricoarytenoid joint dislocation เกิดจาก laryngoscope blade หรือ ETT กดกระทบ arytenoid cartilage ขณะ intubation ทำให้ cricoarytenoid joint subluxation/dislocation อาการเกิด immediately หลัง extubation มี hoarseness, vocal fatigue, pain with phonation ต่างจาก recurrent laryngeal nerve injury ที่มักเกิดจาก thyroid/neck surgery ไม่ใช่ cholecystectomy\n\n✅ E. Cricoarytenoid joint dislocation ถูกต้อง Immediate hoarseness post-GA from non-neck surgery = most likely cause\n\n❌ A. Laryngeal web ไม่ถูกต้อง Congenital หรือ post-surgical cicatricial web ไม่เกิดทันทีหลัง routine intubation\n\n❌ B. Vocal cord nodule ไม่ถูกต้อง เกิดจาก chronic voice abuse ไม่เกิดทันทีหลัง GA\n\n❌ C. Vocal cord paralysis ไม่ถูกต้อง Recurrent laryngeal nerve injury จาก intubation พบได้แต่น้อยกว่า joint dislocation พบบ่อยหลัง thyroid surgery\n\n❌ D. Intubation granuloma ไม่ถูกต้อง เกิดหลังหลายสัปดาห์ถึงเดือนหลัง intubation ไม่ใช่ immediately";

reasons['NL2-2023-Q219'] = "หญิง 62 ขวบ DM breathing difficulty 1 วัน tooth extraction 2 สัปดาห์ก่อน mouth swelling 5 วันก่อน BT 38 RR 23 PR 100 BP 120/70 stridor dyspnea marked swelling ที่ submandibular + sublingual area ถาม management\n\nDM + dental procedure → deep neck space infection (Ludwig's angina = bilateral submandibular + sublingual + submental space infection) ที่ progress จนมี airway compromise (stridor + dyspnea)\n\nLudwig's angina เป็น rapidly progressive cellulitis ของ floor of mouth ที่ life-threatening จาก airway obstruction submandibular/sublingual swelling ดัน tongue ขึ้น + posterior ทำให้ airway narrow\n\nเมื่อมี stridor + dyspnea แล้ว = impending airway obstruction ต้อง secure airway ทันที Tracheostomy เป็น airway ที่เหมาะสมที่สุดเพราะ 1) Oral intubation ยากมาก (severe swelling ของ floor of mouth ดัน tongue ขึ้น ไม่เห็น larynx) 2) Tracheostomy bypass obstruction ที่ supraglottic level\n\n✅ E. Tracheostomy ถูกต้อง Definitive airway management สำหรับ Ludwig's angina with impending airway obstruction\n\n❌ A. Needle aspiration ไม่ถูกต้อง Ludwig's angina เป็น cellulitis (ไม่ใช่ abscess ที่ loculated) needle aspiration ไม่ช่วย + ไม่ secure airway\n\n❌ B. I&D ไม่ถูกต้อง I&D จำเป็นหลัง secure airway แล้ว ไม่ใช่ first priority เมื่อมี airway compromise\n\n❌ C. Debridement ไม่ถูกต้อง ทำหลัง secure airway ไม่ใช่ first step\n\n❌ D. Endotracheal intubation ไม่ถูกต้อง Difficult/impossible intubation ใน Ludwig's angina เพราะ severe submandibular/sublingual swelling tracheostomy เป็น safer option";

reasons['NL2-2023-Q220'] = "หญิง 40 ขวบ gas explosion burn 45% TBSA superficial partial-thickness ที่ face + neck singed facial hair + raw oral mucosa BP 140/80 PR 130 RR 20 SpO2 95% ถาม initial management\n\nFacial burn + singed facial hair + raw oral mucosa → inhalation injury signs ที่ต้อง immediate airway management\n\nInhalation injury signs: facial/neck burns, singed nasal hair/eyebrows, carbonaceous sputum, hoarseness, stridor, raw oral/pharyngeal mucosa เมื่อมี signs เหล่านี้ ต้อง early endotracheal intubation ก่อนที่ airway edema จะ progress จน impossible to intubate (ภายใน 12-24 ชม. airway edema จะ peak)\n\nSpO2 95% + facial burns + singed hair + raw oral mucosa = inhalation injury จนกว่าจะ prove otherwise ต้อง intubate early\n\n✅ A. Endotracheal intubation ถูกต้อง Early prophylactic intubation สำหรับ suspected inhalation injury ก่อน airway edema worsen\n\n❌ B. Rinse with cold water ไม่ถูกต้อง Cooling สำหรับ burn wound management ไม่ใช่ priority เมื่อมี inhalation injury\n\n❌ C. Measure carboxyhemoglobin ไม่ถูกต้อง COHb level ช่วย assess CO poisoning แต่ airway management เป็น priority มากกว่า\n\n❌ D. Tracheobronchoscopy ไม่ถูกต้อง Bronchoscopy ช่วย diagnose + assess inhalation injury แต่ทำหลัง secure airway\n\n❌ E. Silver-containing cream ไม่ถูกต้อง Wound care ทำหลัง stabilize patient + secure airway ไม่ใช่ initial management";

reasons['NL2-2023-Q221'] = "หญิง 60 ขวบ dyspnea + fever 2 วัน no urine output 2 ชม. BT 37 HR 120 (regular) RR 30 BP 80/60 flat neck vein dry lips sunken eyeballs Na 150 ถาม fluid\n\nHypovolemic shock (hypotension + tachycardia + flat neck veins + dry mucous membranes + sunken eyes + oliguria) + hypernatremia (Na 150) = severe dehydration/hypovolemic shock\n\nInitial fluid resuscitation สำหรับ hypovolemic shock: isotonic crystalloid (0.9% NSS) เป็น first-line ตาม ATLS/sepsis guidelines ให้ bolus 20-30 mL/kg แล้ว reassess\n\n0.9% NSS (isotonic) เป็น appropriate initial fluid เพราะ 1) Expand intravascular volume ได้ effective 2) ไม่ทำให้ Na ลดเร็วเกินไป (Na 150 ต้อง correct ช้าๆ) 3) Standard resuscitation fluid\n\n✅ B. 0.9% NSS ถูกต้อง First-line resuscitation fluid สำหรับ hypovolemic shock\n\n❌ A. 0.45% NSS ไม่ถูกต้อง Hypotonic fluid ไม่เหมาะสำหรับ initial resuscitation เพราะ distribute ไป extravascular space มาก expand intravascular volume ไม่ดี อาจใช้หลัง stabilize เพื่อ slowly correct hypernatremia\n\n❌ C. 0.45% NSS + KCl ไม่ถูกต้อง ไม่ใช่ initial resuscitation fluid + ไม่ทราบ K level อย่าให้ KCl โดยไม่ check K ก่อน\n\n❌ D. 0.9% NSS + KCl ไม่ถูกต้อง ไม่ทราบ K level ต้อง resuscitate ด้วย NSS alone ก่อน check electrolytes แล้วค่อยเพิ่ม K ถ้าจำเป็น\n\n❌ E. 0.9% NSS + RI ไม่ถูกต้อง RI (Regular Insulin) ใช้สำหรับ DKA หรือ hyperkalemia ไม่มี indication จากโจทย์";

reasons['NL2-2023-Q222'] = "หญิง 36 ขวบ SOB at rest 1 ชม. PR 90 (regular) BP stable SpO2 95% clear lungs normal S1S2 S3 gallop JVP engorgement cold + clammy skin EKG: tachycardia normal sinus rhythm ถาม diagnosis\n\nAcute onset SOB + S3 gallop + JVP engorgement + cold/clammy skin + clear lungs + normal EKG → right heart failure pattern + clear lungs (no pulmonary edema) → pulmonary embolism (PE)\n\nPE ทำให้ acute right ventricular failure จาก sudden increase ใน pulmonary vascular resistance RV dilates → JVP สูง + S3 gallop (RV gallop) + cold/clammy skin (low cardiac output) lungs remain clear เพราะ obstruction อยู่ที่ pulmonary vasculature ไม่ใช่ alveoli\n\n✅ D. Pulmonary embolism ถูกต้อง Acute RV failure + clear lungs + JVP elevation = PE pattern\n\n❌ A. Cardiac tamponade ไม่ถูกต้อง Tamponade มี Beck's triad (hypotension, JVP elevation, muffled heart sounds) + pulsus paradoxus ไม่มี S3 gallop\n\n❌ B. Severe pneumonia ไม่ถูกต้อง Pneumonia มี abnormal lung findings (crackles, bronchial breathing) ไม่ใช่ clear lungs\n\n❌ C. Rupture chordae tendineae ไม่ถูกต้อง ทำให้ acute mitral regurgitation + pulmonary edema (wet lungs) + new systolic murmur ไม่ใช่ clear lungs\n\n❌ E. Tension pneumothorax ไม่ถูกต้อง มี absent breath sounds ข้างหนึ่ง + tracheal deviation + hypotension ไม่ใช่ bilateral clear lungs";

reasons['NL2-2023-Q223'] = "หญิง 20 ขวบ massive vaginal bleeding หลัง illegal abortion PR 120 RR 24 BP 90/60 Hct 25% ได้ NSS + PRC 10 นาทีหลังได้เลือดเกิด chest tightness + agitation BP 80/50 HR 140 ถาม diagnosis\n\nTransfusion → 10 นาที → chest tightness + agitation + worsening hypotension + tachycardia → acute transfusion reaction\n\nAcute hemolytic transfusion reaction (AHTR) จาก ABO mismatch เป็น most life-threatening transfusion reaction เกิดภายในนาทีหลังเริ่มให้เลือด อาการ: fever/chills, chest/back pain, hypotension, tachycardia, anxiety/agitation, hemoglobinuria (dark urine) เกิดจาก preformed anti-A/anti-B antibodies ทำลาย donor RBCs → complement activation → massive intravascular hemolysis → DIC + renal failure + shock\n\n✅ D. Mismatch transfusion ถูกต้อง Acute onset (10 min) หลังได้ PRC + chest tightness + agitation + hemodynamic instability = classic AHTR\n\n❌ A. Acute pulmonary edema ไม่ถูกต้อง TACO เกิดจาก volume overload ผู้ป่วยยังไม่ได้รับ fluid มากพอที่จะ overload + TACO มี hypertension ไม่ใช่ worsening hypotension\n\n❌ B. Pulmonary embolism ไม่ถูกต้อง PE เป็นไปได้หลัง abortion แต่ timing สัมพันธ์กับ transfusion มากกว่า + PE ไม่มี agitation เป็น feature เด่น\n\n❌ C. Amniotic embolism ไม่ถูกต้อง AFE เกิดระหว่าง labor/delivery/abortion ไม่ใช่ 10 นาทีหลัง blood transfusion ที่ทำทีหลัง\n\n❌ E. Septic shock ไม่ถูกต้อง Septic shock จาก septic abortion เป็นไปได้แต่ timing สัมพันธ์กับ transfusion + onset ภายใน 10 นาทีเร็วเกินไปสำหรับ sepsis ที่มักใช้เวลาหลายชั่วโมง";

reasons['NL2-2023-Q224'] = "ผู้ป่วย cardiac arrest CPR อยู่ EKG shown ถาม treatment for this arrhythmia\n\nCardiac arrest + EKG (สมมติ VF หรือ pulseless VT) → shockable rhythm → defibrillation + amiodarone\n\nAmiodarone เป็น class III antiarrhythmic (potassium channel blocker) ที่ใช้ใน ACLS สำหรับ VF/pulseless VT ที่ refractory ต่อ defibrillation + CPR + epinephrine ขนาด 300 mg IV bolus first dose ตามด้วย 150 mg second dose\n\n✅ A. Amiodarone ถูกต้อง Drug of choice สำหรับ refractory VF/pVT ใน ACLS\n\n❌ B. Lidocaine ไม่ถูกต้อง Alternative to amiodarone แต่ amiodarone เป็น preferred choice ตาม current ACLS guidelines\n\n❌ C. Magnesium sulfate ไม่ถูกต้อง ใช้สำหรับ Torsades de Pointes (polymorphic VT with prolonged QT) ไม่ใช่ standard VF/VT\n\n❌ D. Calcium gluconate ไม่ถูกต้อง ใช้สำหรับ cardiac arrest จาก hyperkalemia/hypocalcemia/calcium channel blocker toxicity\n\n❌ E. NaHCO3 ไม่ถูกต้อง ใช้สำหรับ cardiac arrest จาก severe metabolic acidosis/hyperkalemia/tricyclic antidepressant overdose";

reasons['NL2-2023-Q225'] = "ชาย 50 ขวบ DM HT DLP มี left chest pain radiating to left arm ขณะดู TV 20 นาที ไม่ดีขึ้นเมื่อ rest Troponin T normal ECG no ST-T change ถาม condition\n\nChest pain radiating to arm + 20 min duration + not relieved by rest + risk factors (DM, HT, DLP) → acute coronary syndrome (ACS)\n\nACS แบ่งเป็น 3 types ตาม troponin + ECG: 1) STEMI (ST elevation + troponin positive) 2) NSTEMI (no ST elevation + troponin positive) 3) Unstable angina (no ST elevation + troponin negative)\n\nผู้ป่วยรายนี้: Troponin T normal + ECG no ST-T change → unstable angina (UA)\n\nUA vs stable angina: stable angina เกิดขณะ exertion หายเมื่อ rest หรือ nitroglycerin ภายใน 5 นาที UA เกิดได้ขณะ rest, new onset, crescendo pattern ไม่หายเมื่อ rest ผู้ป่วยรายนี้ pain ขณะดู TV (rest) ไม่ดีขึ้นเมื่อ rest = UA\n\n✅ B. Unstable angina ถูกต้อง Rest pain + not relieved by rest + normal troponin + no ST changes\n\n❌ A. Stable angina ไม่ถูกต้อง Stable angina เกิดขณะ exertion หายเมื่อ rest ผู้ป่วยรายนี้ pain ขณะ rest ไม่หาย\n\n❌ C. NSTEMI ไม่ถูกต้อง NSTEMI มี troponin positive ผู้ป่วยรายนี้ troponin normal\n\n❌ D. Esophageal spasm ไม่ถูกต้อง Esophageal spasm มี dysphagia ร่วมด้วย ไม่ radiate to arm โดยทั่วไป\n\n❌ E. GERD ไม่ถูกต้อง GERD มี heartburn epigastric burning ไม่ radiate to arm มี risk factors สำหรับ CAD (DM HT DLP) ต้อง rule out ACS ก่อน";

reasons['NL2-2023-Q226'] = "หญิง 30 ขวบ face swelling + low-grade fever 4 สัปดาห์ 3 วันก่อน facial plethora arms swelling stridor BT 37.8 PR 100 RR 30 palpable left cervical LN 3 cm hepatomegaly ถาม management\n\nSVC syndrome (facial plethora + arms swelling + stridor) + cervical LAD + hepatomegaly → malignancy (likely lymphoma) causing SVC obstruction + now airway compromise (stridor)\n\nSVC syndrome with airway compromise (stridor + RR 30) เป็น oncological emergency ต้อง immediate treatment\n\nEmergency radiation เป็น most appropriate treatment สำหรับ SVC syndrome จาก malignancy ที่มี severe symptoms/airway compromise radiation ให้ผลเร็วภายใน 24-72 ชม. ลด tumor size + decompress SVC\n\n✅ C. Emergency radiation ถูกต้อง สำหรับ SVC syndrome from malignancy with airway compromise\n\n❌ A. Chemotherapy ไม่ถูกต้อง Chemotherapy เป็น definitive treatment แต่ออกฤทธิ์ช้ากว่า radiation สำหรับ acute SVC syndrome emergency radiation ให้ผลเร็วกว่า\n\n❌ B. Dexamethasone ไม่ถูกต้อง Steroid ช่วยลด edema รอบ tumor ได้บ้าง แต่ไม่ใช่ definitive treatment สำหรับ SVC syndrome with airway compromise\n\n❌ D. ETT ไม่ถูกต้อง Intubation อาจจำเป็นถ้า airway compromise สูง แต่ underlying cause ต้อง treat ด้วย radiation\n\n❌ E. Furosemide ไม่ถูกต้อง Diuretic ไม่ช่วย SVC obstruction จาก tumor compression";

reasons['NL2-2023-Q227'] = "ชาย 40 ขวบ unresponsive ในห้องนอน ประวัติ complex partial seizure ได้ phenytoin 5 ปี BT 37 RR 12 BP 140/85 neurologic: mid-gaze pinpoint pupils extensor posturing ถาม diagnosis\n\nUnresponsive + pinpoint pupils + extensor posturing → brainstem lesion at pontine level\n\nPinpoint pupils เป็น hallmark ของ pontine lesion (hemorrhage/infarction) เกิดจาก destruction ของ sympathetic fibers ที่ descend ผ่าน pons ไปยัง ciliospinal center (C8-T2) ร่วมกับ preservation ของ parasympathetic fibers ทำให้ pupils constrict maximally\n\nExtensor posturing (decerebrate) บ่งบอก lesion ที่ระดับ brainstem ต่ำกว่า red nucleus (midbrain-pontine level)\n\nPontine hemorrhage มักเกิดจาก hypertension (BP 140/85 แม้ไม่สูงมาก แต่อาจเคยสูงกว่า) มี mortality สูง มาด้วย sudden coma + pinpoint pupils + decerebrate posturing + respiratory depression + hyperthermia\n\n✅ A. Pontine hemorrhage ถูกต้อง Pinpoint pupils + extensor posturing + coma = classic pontine hemorrhage\n\n❌ B. Thalamic infarction ไม่ถูกต้อง Thalamic lesion ไม่ทำให้ pinpoint pupils โดยตรง อาจมี contralateral sensory loss + vertical gaze palsy (Parinaud syndrome)\n\n❌ C. Medullary hemorrhage ไม่ถูกต้อง Medullary lesion ทำให้ respiratory failure + cardiovascular instability ไม่มี pinpoint pupils เป็น hallmark\n\n❌ D. Encephalitis ไม่ถูกต้อง มี gradual onset + fever + focal signs ไม่ใช่ sudden coma + pinpoint pupils BT 37 ไม่มี fever\n\n❌ E. Phenytoin intoxication ไม่ถูกต้อง Phenytoin toxicity มี nystagmus, ataxia, drowsiness, dysarthria ไม่มี pinpoint pupils + extensor posturing phenytoin ทำให้ CNS depression แต่ไม่ localize ที่ pons";

reasons['NL2-2023-Q228'] = "ผู้ป่วย altered consciousness + head trauma PE: no fever no Cushing's reflex bilateral fixed dilated pupils absent oculocephalic reflex extensor motor response ถาม diagnosis\n\nHead trauma + bilateral fixed dilated pupils + absent oculocephalic reflex + extensor posturing → severe brainstem dysfunction\n\nBilateral fixed dilated pupils = bilateral CN III compression จาก bilateral uncal herniation → ซึ่งเกิดจาก severe elevated ICP จาก expanding intracranial mass (epidural/subdural hematoma) → progressive transtentorial herniation → secondary pontine hemorrhage (Duret hemorrhages)\n\nNo Cushing's reflex = brainstem function severely compromised (Cushing's reflex คือ hypertension + bradycardia จาก elevated ICP ซึ่งเป็น late sign ของ herniation เมื่อ absent แสดงว่า brainstem destroyed)\n\nPontine hemorrhage (secondary จาก herniation = Duret hemorrhages) เป็น most accurate diagnosis เพราะ bilateral fixed dilated pupils (จาก bilateral CN III compression) + absent oculocephalic (brainstem death) + extensor posturing (pontine level lesion)\n\n✅ A. Pontine hemorrhage ถูกต้อง Secondary pontine hemorrhage (Duret hemorrhages) จาก transtentorial herniation หลัง head trauma\n\n❌ B. Medullary hemorrhage ไม่ถูกต้อง Medullary lesion ทำให้ respiratory arrest + cardiovascular collapse ไม่ใช่ bilateral fixed dilated pupils\n\n❌ C. Thalamic infarction ไม่ถูกต้อง ไม่ทำให้ bilateral fixed dilated pupils + complete brainstem dysfunction\n\n❌ D. Encephalitis ไม่ถูกต้อง มี fever + gradual onset ผู้ป่วยรายนี้ no fever + head trauma\n\n❌ E. Epidural hematoma ไม่ถูกต้อง EDH เป็น cause ของ herniation ไม่ใช่ endpoint เมื่อมี bilateral fixed dilated + absent brainstem reflexes แสดงว่า herniation progressed ไปเป็น secondary brainstem hemorrhage แล้ว";

reasons['NL2-2023-Q229'] = "ชาย motorcycle accident 6 cm contusion ที่ right flank + tenderness ที่ RLQ BP 120/70 HR 80 FAST negative ถาม management\n\nBlunt abdominal trauma + right flank contusion + RLQ tenderness + hemodynamically stable + FAST negative → need further evaluation\n\nFAST negative ไม่ได้ rule out solid organ injury เพราะ sensitivity ของ FAST สำหรับ solid organ injury (โดยเฉพาะ retroperitoneal) เพียง 63-75% เมื่อมี mechanism + physical findings ที่สงสัย injury (flank contusion + RLQ tenderness) → CT abdomen เป็น most appropriate next step\n\nRight flank contusion → สงสัย right kidney/liver injury RLQ tenderness → สงสัย appendiceal/cecal/right colon injury\n\n✅ D. CT abdomen ถูกต้อง Most sensitive investigation สำหรับ blunt abdominal trauma ใน stable patient ที่มี suspicious findings\n\n❌ A. Serial abdominal examination ไม่ถูกต้อง Serial exam เหมาะเมื่อ low suspicion (no specific findings) ผู้ป่วยรายนี้มี flank contusion + tenderness ที่ suggest possible injury → CT\n\n❌ B. DPL ไม่ถูกต้อง Diagnostic peritoneal lavage ถูกแทนที่ด้วย CT ในยุคปัจจุบัน DPL ใช้เมื่อ CT ไม่ available\n\n❌ C. Diagnostic laparoscopy ไม่ถูกต้อง Invasive procedure ที่ต้อง GA ใช้เมื่อ CT equivocal หรือ penetrating trauma\n\n❌ E. Exploratory laparotomy ไม่ถูกต้อง ใช้เมื่อ hemodynamically unstable + positive FAST หรือ peritonitis ไม่ใช่ stable patient";

reasons['NL2-2023-Q230'] = "หญิง 30 ขวบ blunt abdominal injury FAST negative ถาม next step\n\nBlunt abdominal injury + FAST negative + hemodynamically stable (implied) + no specific findings → serial abdominal examination\n\nต่างจาก Q229 ที่มี specific findings (flank contusion + RLQ tenderness) ผู้ป่วยรายนี้ไม่มี specific findings ที่ suggest injury CT อาจไม่จำเป็น serial clinical examination เป็น appropriate approach\n\n✅ A. Serial abdominal examination ถูกต้อง Stable + FAST negative + no specific findings → observe + serial exam\n\n❌ B. CT abdomen ไม่ถูกต้อง CT เหมาะเมื่อมี specific findings หรือ mechanism ที่ high suspicion ผู้ป่วยรายนี้ไม่มี specific findings\n\n❌ C. DPL ไม่ถูกต้อง Invasive ไม่จำเป็นเมื่อ FAST negative + stable\n\n❌ D. Diagnostic laparoscopy ไม่ถูกต้อง Too invasive สำหรับ initial management\n\n❌ E. Exploratory laparotomy ไม่ถูกต้อง ไม่มี indication (stable + FAST negative)";

reasons['NL2-2023-Q231'] = "ผู้ป่วยถูกแทงท้อง (stab wound) ตรวจพบ omental evisceration ถาม management\n\nPenetrating abdominal trauma + omental evisceration (omentum ยื่นออกมาจากแผล) = absolute indication สำหรับ exploratory laparotomy\n\nEvisceration ของ abdominal contents (omentum, bowel) ผ่าน stab wound หมายความว่า peritoneum ถูก penetrate แล้ว + มี risk สูงสำหรับ intra-abdominal organ injury ต้อง surgical exploration เพื่อ 1) Assess all abdominal organs 2) Repair any injured organ 3) Reduce eviscerated omentum + close abdomen\n\n✅ E. Exploratory laparotomy ถูกต้อง Absolute indication สำหรับ evisceration จาก penetrating trauma\n\n❌ A. CT abdomen ไม่ถูกต้อง Evisceration = automatic surgical exploration ไม่ต้อง CT\n\n❌ B. FAST ไม่ถูกต้อง ไม่ต้อง FAST เมื่อมี surgical indication แล้ว\n\n❌ C. DPL ไม่ถูกต้อง ไม่ต้อง DPL peritoneal violation ชัดเจนแล้ว\n\n❌ D. Local wound exploration ไม่ถูกต้อง ไม่ต้อง explore locally เมื่อมี omental evisceration ที่ confirm peritoneal penetration แล้ว ต้อง full laparotomy";

reasons['NL2-2023-Q232'] = "หญิง 40 ขวบ ถูกสุนัขจรจัดกัด ประวัติ complete rabies vaccination 4 เดือนก่อน PE: abrasion wound ที่ left calf มีเลือดออก ถาม management\n\nDog bite + previously vaccinated (complete course 4 เดือนก่อน) + Category III wound (bleeding = broken skin) → booster vaccination\n\nWHO/Thai Red Cross guidelines สำหรับ previously vaccinated person ที่ถูกกัดอีก: 2 booster doses ของ rabies vaccine (วันที่ 0 + วันที่ 3) ไม่ต้อง rabies immunoglobulin (RIG) เพราะ anamnestic antibody response จะขึ้นเร็วพอ\n\n✅ C. 2 booster doses of rabies vaccine ถูกต้อง สำหรับ previously vaccinated person ที่ถูกกัดใหม่\n\n❌ A. Observe ไม่ถูกต้อง ต้อง booster vaccine แม้เคยฉีดครบ\n\n❌ B. 1 booster dose ไม่ถูกต้อง ต้อง 2 doses (Day 0 + Day 3)\n\n❌ D. 5 doses ไม่ถูกต้อง Full course 5 doses ใช้สำหรับ unvaccinated person\n\n❌ E. Rabies immunoglobulin ไม่ถูกต้อง RIG ใช้เฉพาะ unvaccinated person + Category III ไม่ต้องใน previously vaccinated";

reasons['NL2-2023-Q233'] = "เด็กหญิง 5 ขวบ ถูกแมวกัด small laceration with bleeding เคยถูกสุนัขกัด + ได้ full course rabies vaccine 2 ปีก่อน ถาม management\n\nCat bite (Category III - bleeding laceration) + previously vaccinated 2 ปีก่อน → 2 booster doses (Day 0 + Day 3) ไม่ต้อง RIG\n\n✅ C. Booster two dose rabies vaccine ถูกต้อง Previously vaccinated + animal bite → 2 boosters\n\n❌ A. Full course ไม่ถูกต้อง ไม่ต้อง full course เมื่อเคย vaccinated\n\n❌ B. Booster one dose ไม่ถูกต้อง ต้อง 2 doses ไม่ใช่ 1 dose\n\n❌ D. ERIG + one dose ไม่ถูกต้อง ไม่ต้อง RIG เมื่อ previously vaccinated\n\n❌ E. ERIG + two dose ไม่ถูกต้อง ไม่ต้อง RIG เมื่อ previously vaccinated";

reasons['NL2-2023-Q234'] = "เด็กหญิง 10 ขวบ complete EPI vaccination เคยถูกสุนัขกัด 4 เดือนก่อน ได้ full course rabies vaccine วันนี้ถูกสุนัขกัดอีก ถาม rabies vaccination\n\nPreviously vaccinated (full course 4 เดือนก่อน) + animal bite again → 2 booster doses (Day 0 + Day 3)\n\n✅ C. Booster 2 dose ถูกต้อง Standard recommendation สำหรับ previously vaccinated person\n\n❌ A. No need ไม่ถูกต้อง ต้อง booster ทุกครั้งที่มี new exposure\n\n❌ B. Booster 1 dose ไม่ถูกต้อง ต้อง 2 doses\n\n❌ D. Booster 1 dose + Ig ไม่ถูกต้อง ไม่ต้อง immunoglobulin\n\n❌ E. Booster 2 dose + Ig ไม่ถูกต้อง ไม่ต้อง immunoglobulin";

reasons['NL2-2023-Q235'] = "ชาย 25 ขวบ dizziness + blindness 4 ชม.หลังดื่ม local liquor ถาม management\n\nBlindness หลังดื่ม local/bootleg liquor → methanol poisoning\n\nMethanol (wood alcohol) ถูก metabolize โดย alcohol dehydrogenase เป็น formaldehyde แล้วเป็น formic acid ซึ่งเป็น toxic metabolite ที่ทำลาย retinal ganglion cells + optic nerve ทำให้ blindness Formic acid ยัง inhibit cytochrome c oxidase ทำให้ severe metabolic acidosis (high anion gap)\n\nTreatment: ethyl alcohol (ethanol) เป็น competitive inhibitor ของ alcohol dehydrogenase (มี higher affinity กว่า methanol) ป้องกัน conversion ของ methanol เป็น formaldehyde/formic acid Alternative: fomepizole (4-methylpyrazole) ซึ่งเป็น specific ADH inhibitor แต่ราคาแพงกว่ามาก\n\n✅ B. Ethyl alcohol ถูกต้อง Competitive ADH inhibitor ป้องกัน toxic metabolite formation\n\n❌ A. Sodium thiosulfate ไม่ถูกต้อง ใช้สำหรับ cyanide poisoning\n\n❌ C. N-Acetylcysteine ไม่ถูกต้อง ใช้สำหรับ acetaminophen (paracetamol) overdose\n\n❌ D. Naloxone ไม่ถูกต้อง ใช้สำหรับ opioid overdose\n\n❌ E. Fomepizole ไม่ถูกต้อง Fomepizole เป็น alternative สำหรับ methanol poisoning (specific ADH inhibitor) แต่ ethanol เป็น standard answer ในโจทย์ที่มีทั้ง ethanol + fomepizole เป็น choices";

reasons['NL2-2023-Q236'] = "คนสวน disorientation BP 100/60 pupil 1 mm (pinpoint) stupor hypersalivation (cholinergic toxidrome) ถาม antidote\n\nGardener + cholinergic toxidrome (miosis, hypersalivation, stupor) → organophosphate (OP) poisoning จาก pesticide\n\nOP inhibits acetylcholinesterase → acetylcholine accumulates → excessive stimulation ของ muscarinic + nicotinic receptors DUMBELS: Diarrhea, Urination, Miosis, Bradycardia/Bronchospasm, Emesis, Lacrimation, Salivation + Nicotinic: fasciculations, weakness, paralysis\n\nAtropine เป็น competitive muscarinic antagonist ที่ block excess acetylcholine ที่ muscarinic receptors ให้ atropine จนเห็น signs ของ atropinization (dry secretions, HR > 80, pupils dilate) ร่วมกับ pralidoxime (2-PAM) ที่ reactivate acetylcholinesterase\n\n✅ B. Atropine ถูกต้อง First-line antidote สำหรับ OP poisoning\n\n❌ A. Naloxone ไม่ถูกต้อง ใช้สำหรับ opioid overdose (pinpoint pupils ได้เหมือนกัน แต่ไม่มี cholinergic signs)\n\n❌ C. Magnesium sulphate ไม่ถูกต้อง ไม่ใช่ antidote สำหรับ OP\n\n❌ D. Ethyl alcohol ไม่ถูกต้อง ใช้สำหรับ methanol/ethylene glycol poisoning\n\n❌ E. Sodium thiosulfate ไม่ถูกต้อง ใช้สำหรับ cyanide poisoning";

reasons['NL2-2023-Q237'] = "เด็กชาย 12 ขวบ euphoria agitation pressured speech กินขนม + เครื่องดื่มที่งานวันเกิด PE: normal pupils rapid pulse red eyes dry mouth hyperactivity ถาม substance\n\nEuphoria + red eyes + dry mouth + rapid pulse + hyperactivity + normal pupils → cannabis\n\nKey differentiating features: 1) Red eyes (conjunctival injection) = hallmark ของ cannabis จาก vasodilation ของ conjunctival vessels 2) Normal pupils (ไม่ dilate) ต่างจาก amphetamine/cocaine ที่ mydriasis 3) Dry mouth (cottonmouth) = classic cannabis effect 4) Euphoria + hyperactivity + agitation อาจเกิดจาก cannabis โดยเฉพาะในเด็ก/วัยรุ่นที่ใช้ครั้งแรกหรือ high dose 5) Setting: งานวันเกิด อาจมี edible cannabis ใน sweets/beverages\n\n✅ D. Cannabis ถูกต้อง Red eyes + dry mouth + normal pupils + euphoria = cannabis\n\n❌ A. Ecstasy (MDMA) ไม่ถูกต้อง MDMA มี mydriasis + bruxism + hyperthermia + empathy/euphoria ไม่มี red eyes เป็น hallmark\n\n❌ B. Opioid ไม่ถูกต้อง Opioid มี miosis (pinpoint pupils) + sedation + respiratory depression ตรงข้ามกับ hyperactivity\n\n❌ C. Alcohol ไม่ถูกต้อง Alcohol มี sedation + slurred speech + ataxia ไม่ใช่ euphoria + hyperactivity + red eyes\n\n❌ E. Amphetamine ไม่ถูกต้อง Amphetamine มี mydriasis (dilated pupils) + tachycardia + agitation + paranoia ผู้ป่วยรายนี้ normal pupils ไม่เข้ากับ amphetamine";

reasons['NL2-2023-Q238'] = "เด็กหญิง 14 ขวบ กิน paracetamol 50 เม็ด (500 mg) = 25 g มา 8 ชม.ก่อน BT 36 PR 80 BP 110/60 conscious no jaundice normal ถาม management\n\nParacetamol overdose 25 g (25,000 mg) ที่ 8 ชม. → ต้องให้ N-Acetylcysteine (NAC) ทันที\n\nParacetamol overdose: toxic dose ≥ 150 mg/kg (หรือ ≥ 7.5 g ในผู้ใหญ่) 25 g เกิน toxic dose มาก ที่ 8 ชม. ผู้ป่วยอาจอยู่ใน phase 1 (0-24 ชม.: nausea, vomiting, malaise) หรือ ยังไม่มีอาการ (ดูปกติ) ซึ่งไม่ได้หมายความว่าปลอดภัย เพราะ liver damage เกิดใน phase 2-3 (24-72 ชม.)\n\nNAC เป็น glutathione precursor ที่ replenish hepatic glutathione stores ช่วย conjugate กับ toxic metabolite NAPQI (N-acetyl-p-benzoquinone imine) ป้องกัน hepatotoxicity มีประสิทธิภาพสูงสุดเมื่อให้ภายใน 8 ชม. (ผู้ป่วยรายนี้มาพอดี 8 ชม.) แต่ยังมีประโยชน์แม้ให้หลัง 8 ชม.\n\n✅ B. N-Acetylcysteine ถูกต้อง Must-give antidote สำหรับ significant paracetamol overdose\n\n❌ A. NG lavage ไม่ถูกต้อง Gastric lavage มีประโยชน์เฉพาะภายใน 1 ชม.หลัง ingestion ที่ 8 ชม. paracetamol ถูก absorb ไปหมดแล้ว\n\n❌ C. Activated charcoal ไม่ถูกต้อง Activated charcoal มีประโยชน์ภายใน 1-2 ชม.หลัง ingestion ที่ 8 ชม. ไม่มีประโยชน์\n\n❌ D. EGD ไม่ถูกต้อง ไม่มี indication สำหรับ paracetamol overdose\n\n❌ E. Observe + recheck LFT ไม่ถูกต้อง 25 g เกิน toxic dose มาก ไม่ควรแค่ observe ต้อง NAC ทันที";

reasons['NL2-2023-Q239'] = "ผู้ป่วยถูกงูเห่า (cobra) กัด ถาม what must be monitored\n\nCobra = Elapidae family = neurotoxic venom\n\nCobra venom ประกอบด้วย neurotoxins ที่ block neuromuscular junction (post-synaptic alpha-neurotoxins ที่ bind nicotinic ACh receptors + pre-synaptic beta-neurotoxins ที่ prevent ACh release) ทำให้ progressive descending paralysis เริ่มจาก ptosis → ophthalmoplegia → facial weakness → bulbar palsy (dysphagia, dysphonia) → respiratory muscle paralysis → respiratory failure\n\nSerial neurological assessment เป็น most important monitoring เพื่อ detect early signs ของ neurotoxicity ก่อนที่จะเกิด respiratory failure ที่ต้อง intubation + mechanical ventilation\n\n✅ B. Serial neurological deficit assessment ถูกต้อง Essential monitoring สำหรับ neurotoxic snake bite\n\n❌ A. Coagulation ไม่ถูกต้อง Coagulopathy เป็น feature ของ viper bite (Viperidae) ไม่ใช่ cobra\n\n❌ C. Serial venous bleeding time ไม่ถูกต้อง Bleeding time สำหรับ viper/pit viper venom ที่มี hemorrhagins ไม่ใช่ cobra\n\n❌ D. Serum creatinine ไม่ถูกต้อง Renal failure จาก snake bite มักเกิดจาก viper venom (myotoxins → rhabdomyolysis → AKI) ไม่ใช่ cobra\n\n❌ E. Wound debridement ไม่ถูกต้อง Wound care ทำได้แต่ไม่ใช่ most important monitoring";

reasons['NL2-2023-Q240'] = "หญิงพบในห้อง drowsy มี charcoal ใกล้ๆ ประวัติ drug overdose ตอนนี้ conscious ถาม management\n\nCharcoal burning + drug overdose + now conscious → CO poisoning (จากเผาถ่าน) + intentional self-harm\n\nCharcoal burning ใน enclosed space → CO (carbon monoxide) production → CO binds hemoglobin (250x affinity vs O2) → carboxyhemoglobin → tissue hypoxia เมื่อผู้ป่วย conscious แล้วแสดงว่า CO exposure ไม่รุนแรงมากหรือได้รับ fresh air แล้ว\n\nManagement สำหรับ conscious patient หลัง CO exposure + drug overdose: Observe ในโรงพยาบัย (monitor CO level, neurological status, cardiac monitor, psychiatric evaluation) เพราะ 1) CO poisoning อาจมี delayed neurological syndrome 2) Drug overdose ต้อง monitor 3) Suicide attempt ต้อง psychiatric evaluation\n\n✅ C. Observe ถูกต้อง Observe + monitor สำหรับ CO poisoning + drug overdose ที่ conscious\n\n❌ A. Gastric lavage ไม่ถูกต้อง ไม่ทราบว่ากิน drug อะไร + เวลาที่กิน lavage อาจไม่มีประโยชน์ถ้าเกิน 1 ชม.\n\n❌ B. EGD ไม่ถูกต้อง ไม่มี indication สำหรับ drug overdose\n\n❌ D. Activated charcoal ไม่ถูกต้อง ไม่ทราบว่ากิน drug เมื่อไร + charcoal ไม่ effective สำหรับ CO poisoning\n\n❌ E. Immediate psychiatric consultation ไม่ถูกต้อง Psychiatric evaluation จำเป็นแต่ต้อง medically stabilize + observe ก่อน ไม่ใช่ immediate priority";

mongoose.connect(uri).then(async () => {
  const col = mongoose.connection.db.collection('questions');
  let count = 0;
  for (const [qId, reason] of Object.entries(reasons)) {
    await col.updateOne({questionId: qId}, {'$set': {reason}});
    count++;
    console.log(count + '. ' + qId + ': updated (' + reason.length + ' chars)');
  }
  console.log('Done! Updated ' + count + ' questions');
  mongoose.disconnect();
}).catch(err => console.error(err.message));
